### ISSUE TITLE
help me how to scale out the rack and dc

### ISSUE THREAD

**Issue by xcl3721** [Netflix/dynomite#116]
we are using this with phpredis extension 
and we have two rack(rack1 rack2) and each have two node

the question is:
1.what's token ,it's mean the same dataset?
2.did i need set each node have same token or make the node different each.
3.how can we add rack .when i add a new rack to dc.it's cant get the "old" data.
4.we tried to make rack1(node1:token 1,node2:token2) rack2(node3:token2,node4:token1) we found only one token redis server have aof increased.and if this redis down the data lost too
5.when the write data redis down the data lost...

**Comment by timiblossom** [comment]
@xcl3721 Here are the answers.

1. A token along with DC and Rack is like an identifier for a node.  Based on this, nodes can know what subset of data they can own.  Of course, nodes in different rack/dc can own the same subset of data.
2. Look at this script and it gives you an idea how you should generate tokens:
    https://github.com/Netflix/dynomite/blob/master/scripts/generate_yamls.py
3. Answer is similar to #2.  Take a look at the output files from that script to understand the topology
4. I don't see this is the case.  Please explain in more details.  Probably you had a wrong configuration somewhere.
5. You can read this issue here as it relates to your question:
    https://github.com/Netflix/dynomite/issues/51
   Furthermore, we are currently working on data repair as additional process to fix bad data.

**Comment by xcl3721** [comment]
thank u sir
can we support php extension like dyo？

my config is here

dyn_o_mite:
  datacenter: dc
  rack: rack1
  dyn_listen: 172.1.1.61:8101
  dyn_seed_provider: simple_provider
  dyn_seeds:
  - 172.1.1.62:8101:rack1:dc:1721162
  - 172.1.1.63:8101:rack2:dc:1721161
  - 172.1.1.64:8101:rack2:dc:1721162
  listen: 0.0.0.0:6399
  timeout: 3000
  server_retry_timeout: 3000
  servers:
  - 127.0.0.1:6379:1
  tokens: '1721161'
  secure_server_option: datacenter
  server_connections: 4
  auto_eject_hosts: true
  server_failure_limit: 3
  pem_key_file: /etc/dynomite/dynomite.pem
  redis: true

--------------
dyn_o_mite:
  datacenter: dc
  rack: rack1
  dyn_listen: 172.1.1.62:8101
  dyn_seed_provider: simple_provider
  dyn_seeds:
  - 172.1.1.61:8101:rack1:dc:1721161
  - 172.1.1.63:8101:rack1:dc:1721161
  - 172.1.1.64:8101:rack1:dc:1721162
  listen: 0.0.0.0:6399
  timeout: 3000
  server_retry_timeout: 3000
  servers:
  - 127.0.0.1:6379:1
  tokens: '1721162'
  secure_server_option: datacenter
  server_connections: 4
  auto_eject_hosts: true
  server_failure_limit: 3
  pem_key_file: /etc/dynomite/dynomite.pem
  redis: true
----------
dyn_o_mite:
  datacenter: dc
  rack: rack2
  dyn_listen: 172.1.1.63:8101
  dyn_seed_provider: simple_provider
  dyn_seeds:
  - 172.1.1.61:8101:rack1:dc:1721161
  - 172.1.1.62:8101:rack1:dc:1721162
  - 172.1.1.64:8101:rack2:dc:1721162
  listen: 0.0.0.0:6399
  timeout: 3000
  server_retry_timeout: 3000
  servers:
  - 127.0.0.1:6379:1
  tokens: '1721161'
  secure_server_option: datacenter
  server_connections: 4
  auto_eject_hosts: true
  server_failure_limit: 3
  pem_key_file: /etc/dynomite/dynomite.pem
  redis: true
---------------
dyn_o_mite:
  datacenter: dc
  rack: rack2
  dyn_listen: 172.1.1.64:8101
  dyn_seed_provider: simple_provider
  dyn_seeds:
  - 172.1.1.61:8101:rack1:dc:1721161
  - 172.1.1.62:8101:rack1:dc:1721162
  - 172.1.1.63:8101:rack2:dc:1721161
  listen: 0.0.0.0:6399
  timeout: 3000
  server_retry_timeout: 3000
  servers:
  - 127.0.0.1:6379:1
  tokens: '1721162'
  secure_server_option: datacenter
  server_connections: 4
  auto_eject_hosts: true
  server_failure_limit: 3
  pem_key_file: /etc/dynomite/dynomite.pem
  redis: true

**Comment by timiblossom** [comment]
Sorry but we don't have the resource for PHP client like Dyno at this time. 
However, you can just use any Redis PHP client and take care of the failover in your application layer yourself?

**Comment by xcl3721** [comment]
ok  
:) ~ thank u~

**Comment by patademahesh** [comment]
How can we achieve failover in application layer using PHP redis client ?  

Any hints.. !!

Thanks
Mahesh
