### ISSUE TITLE
Why don't write operations scale as well as read operations?

### ISSUE THREAD

**Issue by mansoor-s** [Netflix/dynomite#117]
Hello,

Looking at this image from the intro blog post:

![scale](https://lh6.googleusercontent.com/xLGqWlGVdIXGF2KjPF3R6-NiY18XZvWQPuWkuq8JGt-8m-7mgAE5WX4LogMkmC1TI1DbHsAD61_Yyq4va0Y-c7bgD2zS8v1AE2IbFXvNHe0xMX8lC_JP5mstbLX9jdeIQg)

Why do we see the number of write operations not scale as well as the read operations. I understand that the total number of write operations might be lower than the number of read operations, but shouldn't the lines be parallel?
If Dynomite was waiting for confirmation from all nodes before accepting a write, this might make sense, but it is doing all of that asynchronously

**Comment by timiblossom** [comment]
They both scale linearly.  I believe our graph was for the test case 80% for reads and 20% for writes.

**Comment by mansoor-s** [comment]
@timiblossom Right. They are both linear.. but they don't have the same slope. 
Even given that the benchmark operation distribution was 80% read and 20% writes, shouldn't they both scale at the same rate?

**Comment by timiblossom** [comment]
No, they are not.

Rate = (y2-y1)/(x2-x1)

If delta(x) is the same and delta(y) is not, then the rates are not the same.
