### ISSUE TITLE
Uneven Key Distribution

### ISSUE THREAD

**Issue by ralfonso** [Netflix/dynomite#125]
I seem to get a predictably uneven key distribution depending on the tokens I use. For a three node rack, I consistently get an approximate 55%/37%/8% distribution of keys. For my testing, I'm creating 100k alphanumeric keys of varying length [10,25].

I used the generate_yamls.py script for this cluster, which of course generated random tokens. 

Since Dynomite does not yet have vnodes, is there a way to generate tokens based on the rack size that would offer a slightly more uniform distribution?

**Comment by timiblossom** [comment]
To help you out, here is our Java code to generate tokens:

    public static final BigInteger MAXIMUM_TOKEN = new BigInteger("2").pow(32).add(new BigInteger("-1"));

    /**
     * Calculate a token for the given position, evenly spaced from other size-1 nodes.  See
     *
     * @param size number of slots by which the token space will be divided
     * @param position slot number, multiplier
     * @param offset added to token
     * @return MAXIMUM_TOKEN / size * position + offset, if <= MAXIMUM_TOKEN, otherwise wrap around the MINIMUM_TOKEN
     */
    @VisibleForTesting BigInteger initialToken(int size, int position, int offset)
    {
        return MAXIMUM_TOKEN.divide(BigInteger.valueOf(size))
                .multiply(BigInteger.valueOf(position))
                .add(BigInteger.valueOf(offset)).mod(MAXIMUM_TOKEN);
    }

**Comment by ralfonso** [comment]
Thanks, that snippet helps us generate tokens to get a uniform distribution.
