### ISSUE TITLE
redis-cli can not get response from the dynomite process.

### ISSUE THREAD

**Issue by hexusheng** [Netflix/dynomite#130]
Hi,

There is 2 datacenters with a single rack each containing 2 nodes(4 machines). if I use the  redis-cli to do some test ,it shows:
192.168.7.215:8102> ping
(error) ERR Storage: Connection timed out
(24.12s)

192.168.7.215:8102>get "xx"

The dynomite did't give any response or until time out.

Using the config below:
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_listen: 192.168.7.215:8101
  dyn_seeds:
  - 192.168.7.216:8101:rack1:dc1:1234567892
  - 192.168.7.248:8101:rack2:dc2:1234567891
  - 192.168.7.78:8101:rack2:dc2:1234567892
  listen: 192.168.7.215:8102
  servers:
  - 192.168.7.215:6379:1
  tokens: '1234567891'
  redis: true 
  timeout: 30000

dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_listen: 192.168.7.216:8101
  dyn_seeds:
  - 192.168.7.215:8101:rack1:dc1:1234567891
  - 192.168.7.248:8101:rack2:dc2:1234567891
  - 192.168.7.78:8101:rack2:dc2:1234567892
  listen: 192.168.7.216:8102
  servers:
  - 192.168.7.216:6379:1
  tokens: '1234567892'
  redis: true
  timeout: 30000

dyn_o_mite:
  datacenter: dc2
  rack: rack2
  dyn_listen: 192.168.7.248:8101
  dyn_seeds:
  - 192.168.7.215:8101:rack1:dc1:1234567891
  - 192.168.7.216:8101:rack1:dc1:1234567892
  - 192.168.7.78:8101:rack2:dc2:1234567892
  listen: 192.168.7.248:8102
  servers:
  - 192.168.7.248:6379:1
  tokens: '1234567891'
  redis: true
  timeout: 30000

dyn_o_mite:
  datacenter: dc2
  rack: rack2
  dyn_listen: 192.168.7.78:8101
  dyn_seeds:
  - 192.168.7.215:8101:rack1:dc1:1234567891
  - 192.168.7.216:8101:rack1:dc1:1234567892
  - 192.168.7.248:8101:rack2:dc2:1234567891
  listen: 192.168.7.78:8102
  servers:
  - 192.168.7.78:6379:1
  tokens: '1234567892'
  redis: true
  timeout: 30000

Log from 192.168.7.215 below:

[Fri May 15 01:07:49 2015] dynomite.c:198 dynomite-0.1.19 built for Linux 2.6.32-358.el6.x86_64 x86_64 started on pid 15242
[Fri May 15 01:07:49 2015] dynomite.c:203 run, rabbit run / dig that hole, forget the sun / and when at last the work is done / don't sit down / it's time to dig another one
[Fri May 15 01:07:49 2015] dyn_mbuf.c:321 mbuf hsize 64 chunk size 16400 offset 16336 length 16336
[Fri May 15 01:07:49 2015] dyn_message.c:582 msg size 344
[Fri May 15 01:07:49 2015] dyn_connection.c:477 conn size 328
[Fri May 15 01:07:49 2015] dyn_conf.c:1533 setting secure_server_option to default value:none
[Fri May 15 01:07:49 2015] dyn_conf.c:1546 setting env to default value:aws
[Fri May 15 01:07:49 2015] dyn_conf.c:1551 setting pem key file to default value:conf/dynomite.pem
[Fri May 15 01:07:49 2015] dyn_conf.c:247 transform to server 0 '192.168.7.215:6379:1'
[Fri May 15 01:07:49 2015] dyn_server.c:158 init 1 servers in pool 0 'dyn_o_mite'
[Fri May 15 01:07:49 2015] dyn_conf.c:513 transform to pool 0 'dyn_o_mite'
[Fri May 15 01:07:49 2015] dyn_server.c:793 init 1 pools
[Fri May 15 01:07:49 2015] dyn_crypto.c:65 Private RSA structure filled
[Fri May 15 01:07:49 2015] dyn_stats.c:487 stats buffer size 2920
[Fri May 15 01:07:49 2015] dyn_stats.c:1192 m 5 listening on '0.0.0.0:22222'
[Fri May 15 01:07:49 2015] dyn_epoll.c:68 e 6 with nevent 1024
[Fri May 15 01:07:49 2015] dyn_server.c:505 connecting on s 8 to server '192.168.7.215:6379:1'
[Fri May 15 01:07:49 2015] dyn_proxy.c:211 p 9 listening on '192.168.7.215:8102' in redis pool 0 'dyn_o_mite' with 1 servers
[Fri May 15 01:07:49 2015] dyn_dnode_server.c:154 dyn: e 6 with nevent 1024
[Fri May 15 01:07:49 2015] dyn_dnode_server.c:195 dyn: p 10 listening on '192.168.7.215:8101' in redis pool 0 'dyn_o_mite' with 1 servers
[Fri May 15 01:07:49 2015] dyn_conf.c:300 transform to seed peer 0 '192.168.7.216:8101:rack1:dc1:1234567892'
[Fri May 15 01:07:49 2015] dyn_conf.c:300 transform to seed peer 1 '192.168.7.248:8101:rack2:dc2:1234567891'
[Fri May 15 01:07:49 2015] dyn_conf.c:300 transform to seed peer 2 '192.168.7.78:8101:rack2:dc2:1234567892'
[Fri May 15 01:07:49 2015] dyn_dnode_peer.c:161 dyn: transform to local node to peer 0 'dyn_o_mite'
[Fri May 15 01:07:49 2015] dyn_conf.c:300 transform to seed peer 1 '192.168.7.216:8101:rack1:dc1:1234567892'
[Fri May 15 01:07:49 2015] dyn_conf.c:300 transform to seed peer 2 '192.168.7.248:8101:rack2:dc2:1234567891'
[Fri May 15 01:07:49 2015] dyn_conf.c:300 transform to seed peer 3 '192.168.7.78:8101:rack2:dc2:1234567892'
[Fri May 15 01:07:49 2015] dyn_vnode.c:67 peer name       : '192.168.7.215'
[Fri May 15 01:07:49 2015] dyn_vnode.c:68 peer rack       : 'rack1'
[Fri May 15 01:07:49 2015] dyn_vnode.c:69 peer dc       : 'dc1'
[Fri May 15 01:07:49 2015] dyn_vnode.c:70 peer->processed = 0
[Fri May 15 01:07:49 2015] dyn_server.c:910 server_get_dc pool  'dc1'
[Fri May 15 01:07:49 2015] dyn_server.c:929 server_get_dc pool about to exit  'dc1'
[Fri May 15 01:07:49 2015] dyn_server.c:944 server_get_rack   'rack1'
[Fri May 15 01:07:49 2015] dyn_server.c:976 server_get_rack exiting  'rack1'
[Fri May 15 01:07:49 2015] dyn_vnode.c:47 **** printing continuums for rack 'rack1'
[Fri May 15 01:07:49 2015] dyn_vnode.c:51 next c[0]: idx = 0, token->mag = 1234567891
[Fri May 15 01:07:49 2015] dyn_vnode.c:53 **** end printing continuums for rack 'rack1'
[Fri May 15 01:07:49 2015] dyn_vnode.c:67 peer name       : '192.168.7.216'
[Fri May 15 01:07:49 2015] dyn_vnode.c:68 peer rack       : 'rack1'
[Fri May 15 01:07:49 2015] dyn_vnode.c:69 peer dc       : 'dc1'
[Fri May 15 01:07:49 2015] dyn_vnode.c:70 peer->processed = 0
[Fri May 15 01:07:49 2015] dyn_server.c:910 server_get_dc pool  'dc1'
[Fri May 15 01:07:49 2015] dyn_server.c:944 server_get_rack   'rack1'
[Fri May 15 01:07:49 2015] dyn_vnode.c:47 **** printing continuums for rack 'rack1'
[Fri May 15 01:07:49 2015] dyn_vnode.c:51 next c[0]: idx = 0, token->mag = 1234567891
[Fri May 15 01:07:49 2015] dyn_vnode.c:51 next c[1]: idx = 1, token->mag = 1234567892
[Fri May 15 01:07:49 2015] dyn_vnode.c:53 **** end printing continuums for rack 'rack1'
[Fri May 15 01:07:49 2015] dyn_vnode.c:67 peer name       : '192.168.7.248'
[Fri May 15 01:07:49 2015] dyn_vnode.c:68 peer rack       : 'rack2'
[Fri May 15 01:07:49 2015] dyn_vnode.c:69 peer dc       : 'dc2'
[Fri May 15 01:07:49 2015] dyn_vnode.c:70 peer->processed = 0
[Fri May 15 01:07:49 2015] dyn_server.c:910 server_get_dc pool  'dc2'
[Fri May 15 01:07:49 2015] dyn_server.c:929 server_get_dc pool about to exit  'dc2'
[Fri May 15 01:07:49 2015] dyn_server.c:944 server_get_rack   'rack2'
[Fri May 15 01:07:49 2015] dyn_server.c:976 server_get_rack exiting  'rack2'
[Fri May 15 01:07:49 2015] dyn_vnode.c:47 **** printing continuums for rack 'rack2'
[Fri May 15 01:07:49 2015] dyn_vnode.c:51 next c[0]: idx = 2, token->mag = 1234567891
[Fri May 15 01:07:49 2015] dyn_vnode.c:53 **** end printing continuums for rack 'rack2'
[Fri May 15 01:07:49 2015] dyn_vnode.c:67 peer name       : '192.168.7.78'
[Fri May 15 01:07:49 2015] dyn_vnode.c:68 peer rack       : 'rack2'
[Fri May 15 01:07:49 2015] dyn_vnode.c:69 peer dc       : 'dc2'
[Fri May 15 01:07:49 2015] dyn_vnode.c:70 peer->processed = 0
[Fri May 15 01:07:49 2015] dyn_server.c:910 server_get_dc pool  'dc2'
[Fri May 15 01:07:49 2015] dyn_server.c:944 server_get_rack   'rack2'
[Fri May 15 01:07:49 2015] dyn_vnode.c:47 **** printing continuums for rack 'rack2'
[Fri May 15 01:07:49 2015] dyn_vnode.c:51 next c[0]: idx = 2, token->mag = 1234567891
[Fri May 15 01:07:49 2015] dyn_vnode.c:51 next c[1]: idx = 3, token->mag = 1234567892
[Fri May 15 01:07:49 2015] dyn_vnode.c:53 **** end printing continuums for rack 'rack2'
[Fri May 15 01:07:49 2015] dyn_dnode_peer.c:274 init 3 seeds and peers in pool 0 'dyn_o_mite'
[Fri May 15 01:07:49 2015] dyn_core.c:523 =====================Peers info=====================
[Fri May 15 01:07:49 2015] dyn_core.c:527 Server pool          : 0
[Fri May 15 01:07:49 2015] dyn_core.c:530 ==============================================
[Fri May 15 01:07:49 2015] dyn_core.c:532       Peer DC            : 'dc1'
[Fri May 15 01:07:49 2015] dyn_core.c:533       Peer Rack          : 'rack1'
[Fri May 15 01:07:49 2015] dyn_core.c:535       Peer name          : '192.168.7.215'
[Fri May 15 01:07:49 2015] dyn_core.c:536       Peer pname         : '192.168.7.215:8101'
[Fri May 15 01:07:49 2015] dyn_core.c:538       Peer state         : 7
[Fri May 15 01:07:49 2015] dyn_core.c:539       Peer port          : 8101
[Fri May 15 01:07:49 2015] dyn_core.c:540       Peer is_local      : 1 
[Fri May 15 01:07:49 2015] dyn_core.c:541       Peer failure_count : 0 
[Fri May 15 01:07:49 2015] dyn_core.c:542       Peer num tokens    : 1
[Fri May 15 01:07:49 2015] dyn_token.c:96               Token : 1 1234567891 1 
[Fri May 15 01:07:49 2015] dyn_core.c:530 ==============================================
[Fri May 15 01:07:49 2015] dyn_core.c:532       Peer DC            : 'dc1'
[Fri May 15 01:07:49 2015] dyn_core.c:533       Peer Rack          : 'rack1'
[Fri May 15 01:07:49 2015] dyn_core.c:535       Peer name          : '192.168.7.216'
[Fri May 15 01:07:49 2015] dyn_core.c:536       Peer pname         : '192.168.7.216:8101:rack1:dc1:1234567892'
[Fri May 15 01:07:49 2015] dyn_core.c:538       Peer state         : 4
[Fri May 15 01:07:49 2015] dyn_core.c:539       Peer port          : 8101
[Fri May 15 01:07:49 2015] dyn_core.c:540       Peer is_local      : 0 
[Fri May 15 01:07:49 2015] dyn_core.c:541       Peer failure_count : 0 
[Fri May 15 01:07:49 2015] dyn_core.c:542       Peer num tokens    : 1
[Fri May 15 01:07:49 2015] dyn_token.c:96               Token : 1 1234567892 1 
[Fri May 15 01:07:49 2015] dyn_core.c:530 ==============================================
[Fri May 15 01:07:49 2015] dyn_core.c:532       Peer DC            : 'dc2'
[Fri May 15 01:07:49 2015] dyn_core.c:533       Peer Rack          : 'rack2'
[Fri May 15 01:07:49 2015] dyn_core.c:535       Peer name          : '192.168.7.248'
[Fri May 15 01:07:49 2015] dyn_core.c:536       Peer pname         : '192.168.7.248:8101:rack2:dc2:1234567891'
[Fri May 15 01:07:49 2015] dyn_core.c:538       Peer state         : 4
[Fri May 15 01:07:49 2015] dyn_core.c:539       Peer port          : 8101
[Fri May 15 01:07:49 2015] dyn_core.c:540       Peer is_local      : 0 
[Fri May 15 01:07:49 2015] dyn_core.c:541       Peer failure_count : 0 
[Fri May 15 01:07:49 2015] dyn_core.c:542       Peer num tokens    : 1
[Fri May 15 01:07:49 2015] dyn_token.c:96               Token : 1 1234567891 1 
[Fri May 15 01:07:49 2015] dyn_core.c:530 ==============================================
[Fri May 15 01:07:49 2015] dyn_core.c:532       Peer DC            : 'dc2'
[Fri May 15 01:07:49 2015] dyn_core.c:533       Peer Rack          : 'rack2'
[Fri May 15 01:07:49 2015] dyn_core.c:535       Peer name          : '192.168.7.78'
[Fri May 15 01:07:49 2015] dyn_core.c:536       Peer pname         : '192.168.7.78:8101:rack2:dc2:1234567892'
[Fri May 15 01:07:49 2015] dyn_core.c:538       Peer state         : 4
[Fri May 15 01:07:49 2015] dyn_core.c:539       Peer port          : 8101
[Fri May 15 01:07:49 2015] dyn_core.c:540       Peer is_local      : 0 
[Fri May 15 01:07:49 2015] dyn_core.c:541       Peer failure_count : 0 
[Fri May 15 01:07:49 2015] dyn_core.c:542       Peer num tokens    : 1
[Fri May 15 01:07:49 2015] dyn_token.c:96               Token : 1 1234567892 1 
[Fri May 15 01:07:49 2015] dyn_core.c:551 Peers Datacenters/racks/nodes .................................................
[Fri May 15 01:07:49 2015] dyn_core.c:555 Peer datacenter........'dc1'
[Fri May 15 01:07:49 2015] dyn_core.c:559       Peer rack........'rack1'
[Fri May 15 01:07:49 2015] dyn_core.c:560       Peer rack ncontinuumm    : 2
[Fri May 15 01:07:49 2015] dyn_core.c:561       Peer rack nserver_continuum    : 2
[Fri May 15 01:07:49 2015] dyn_core.c:555 Peer datacenter........'dc2'
[Fri May 15 01:07:49 2015] dyn_core.c:559       Peer rack........'rack2'
[Fri May 15 01:07:49 2015] dyn_core.c:560       Peer rack ncontinuumm    : 2
[Fri May 15 01:07:49 2015] dyn_core.c:561       Peer rack nserver_continuum    : 2
[Fri May 15 01:07:49 2015] dyn_core.c:566 ...............................................................................
[Fri May 15 01:07:49 2015] dyn_dnode_peer.c:1023 dnode_peer_connect dyn: connect to peer '192.168.7.216:8101:rack1:dc1:1234567892'
[Fri May 15 01:07:49 2015] dyn_dnode_peer.c:1037 dyn: connect to peer '192.168.7.216:8101:rack1:dc1:1234567892'
[Fri May 15 01:07:49 2015] dyn_dnode_peer.c:1082 dyn: connecting on s 11 to peer '192.168.7.216:8101:rack1:dc1:1234567892'
[Fri May 15 01:07:49 2015] dyn_dnode_peer.c:1023 dnode_peer_connect dyn: connect to peer '192.168.7.248:8101:rack2:dc2:1234567891'
[Fri May 15 01:07:49 2015] dyn_dnode_peer.c:1037 dyn: connect to peer '192.168.7.248:8101:rack2:dc2:1234567891'
[Fri May 15 01:07:49 2015] dyn_dnode_peer.c:1082 dyn: connecting on s 12 to peer '192.168.7.248:8101:rack2:dc2:1234567891'
[Fri May 15 01:07:49 2015] dyn_dnode_peer.c:1023 dnode_peer_connect dyn: connect to peer '192.168.7.78:8101:rack2:dc2:1234567892'
[Fri May 15 01:07:49 2015] dyn_dnode_peer.c:1037 dyn: connect to peer '192.168.7.78:8101:rack2:dc2:1234567892'
[Fri May 15 01:07:49 2015] dyn_dnode_peer.c:1082 dyn: connecting on s 13 to peer '192.168.7.78:8101:rack2:dc2:1234567892'
[Fri May 15 01:07:49 2015] dyn_gossip.c:793 Seed provider :::::: 'simple_provider'
[Fri May 15 01:07:49 2015] dyn_gossip.c:848 What?? No rack in Dict for rack         : 'dc1'
[Fri May 15 01:07:49 2015] dyn_gossip.c:848 What?? No rack in Dict for rack         : 'dc2'
[Fri May 15 01:07:49 2015] dyn_core.c:592 timeout = 30000
[Fri May 15 01:07:49 2015] dyn_core.c:573 length of C2G_OutQ : 0
[Fri May 15 01:07:49 2015] dyn_server.c:542 connected on s 8 to server '192.168.7.215:6379:1'
[Fri May 15 01:07:49 2015] dyn_core.c:592 timeout = 30000
[Fri May 15 01:07:49 2015] dyn_core.c:573 length of C2G_OutQ : 0
[Fri May 15 01:07:49 2015] dyn_dnode_peer.c:1121 dyn: peer connected on sd 11 to server '192.168.7.216:8101:rack1:dc1:1234567892'
[Fri May 15 01:07:49 2015] dyn_core.c:592 timeout = 30000
[Fri May 15 01:07:49 2015] dyn_core.c:573 length of C2G_OutQ : 0
[Fri May 15 01:07:49 2015] dyn_dnode_peer.c:1121 dyn: peer connected on sd 13 to server '192.168.7.78:8101:rack2:dc2:1234567892'
[Fri May 15 01:07:49 2015] dyn_core.c:592 timeout = 30000
[Fri May 15 01:07:49 2015] dyn_core.c:573 length of C2G_OutQ : 0
[Fri May 15 01:07:49 2015] dyn_dnode_peer.c:1121 dyn: peer connected on sd 12 to server '192.168.7.248:8101:rack2:dc2:1234567891'
[Fri May 15 01:07:49 2015] dyn_core.c:592 timeout = 30000
[Fri May 15 01:07:49 2015] dyn_core.c:573 length of C2G_OutQ : 0
[Fri May 15 01:07:58 2015] dyn_proxy.c:341 accepted c 14 on p 9 from '192.168.7.113:7595'
[Fri May 15 01:07:58 2015] dyn_proxy.c:285 accept on p 9 not ready - eagain
[Fri May 15 01:07:58 2015] dyn_core.c:592 timeout = 30000
[Fri May 15 01:07:58 2015] dyn_core.c:573 length of C2G_OutQ : 0
[Fri May 15 01:07:58 2015] dyn_core.c:592 timeout = 30000
[Fri May 15 01:07:58 2015] dyn_core.c:573 length of C2G_OutQ : 0
[Fri May 15 01:08:03 2015] dyn_message.c:227 alloc_msg_count : 1
[Fri May 15 01:08:03 2015] dyn_connection.c:508 recv on sd 14 14 of 16320
[Fri May 15 01:08:03 2015] dyn_redis.c:1621 parsed req 1 res 0 type 82 state 0 rpos 14 of 14
00000000  2a 31 0d 0a 24 34 0d 0a  70 69 6e 67 0d 0a         |*1..$4..ping..|
[Fri May 15 01:08:03 2015] dyn_server.c:910 server_get_dc pool  'dc1'
[Fri May 15 01:08:03 2015] dyn_server.c:944 server_get_rack   'rack1'
[Fri May 15 01:08:03 2015] dyn_dnode_peer.c:1254 Entering dnode_peer_pool_conn ................................
[Fri May 15 01:08:03 2015] dyn_vnode.c:67 peer name       : '192.168.7.215'
[Fri May 15 01:08:03 2015] dyn_vnode.c:68 peer rack       : 'rack1'
[Fri May 15 01:08:03 2015] dyn_vnode.c:69 peer dc       : 'dc1'
[Fri May 15 01:08:03 2015] dyn_vnode.c:70 peer->processed = 1
[Fri May 15 01:08:03 2015] dyn_vnode.c:67 peer name       : '192.168.7.216'
[Fri May 15 01:08:03 2015] dyn_vnode.c:68 peer rack       : 'rack1'
[Fri May 15 01:08:03 2015] dyn_vnode.c:69 peer dc       : 'dc1'
[Fri May 15 01:08:03 2015] dyn_vnode.c:70 peer->processed = 1
[Fri May 15 01:08:03 2015] dyn_vnode.c:67 peer name       : '192.168.7.248'
[Fri May 15 01:08:03 2015] dyn_vnode.c:68 peer rack       : 'rack2'
[Fri May 15 01:08:03 2015] dyn_vnode.c:69 peer dc       : 'dc2'
[Fri May 15 01:08:03 2015] dyn_vnode.c:70 peer->processed = 1
[Fri May 15 01:08:03 2015] dyn_vnode.c:67 peer name       : '192.168.7.78'
[Fri May 15 01:08:03 2015] dyn_vnode.c:68 peer rack       : 'rack2'
[Fri May 15 01:08:03 2015] dyn_vnode.c:69 peer dc       : 'dc2'
[Fri May 15 01:08:03 2015] dyn_vnode.c:70 peer->processed = 1
[Fri May 15 01:08:03 2015] dyn_dnode_peer.c:1239 dyn: key '' on dist 3 maps to server '192.168.7.215:8101'
[Fri May 15 01:08:03 2015] dyn_server.c:604 update pool 0 'dyn_o_mite' to add 0 servers
[Fri May 15 01:08:03 2015] dyn_request.c:491 forwarding request from client conn '192.168.7.113:7595' to storage conn '192.168.7.113:7595'
[Fri May 15 01:08:03 2015] dyn_message.c:171 insert msg 1 into tmo rbt with expiry of 30000 msec
[Fri May 15 01:08:03 2015] dyn_request.c:537 local forward from c 14 to s 8 req 1 len 14 type 82 with key ''
[Fri May 15 01:08:03 2015] dyn_core.c:592 timeout = 30000
[Fri May 15 01:08:03 2015] dyn_core.c:573 length of C2G_OutQ : 0
[Fri May 15 01:08:19 2015] dyn_gossip.c:726 Gossip is running ...
[Fri May 15 01:08:19 2015] dyn_gossip.c:755 I am still joining the ring!
[Fri May 15 01:08:22 2015] dyn_proxy.c:341 accepted c 15 on p 9 from '192.168.7.215:8960'
[Fri May 15 01:08:22 2015] dyn_proxy.c:285 accept on p 9 not ready - eagain
[Fri May 15 01:08:22 2015] dyn_core.c:592 timeout = 11685
[Fri May 15 01:08:22 2015] dyn_core.c:573 length of C2G_OutQ : 1
[Fri May 15 01:08:22 2015] dyn_dnode_peer.c:1023 dnode_peer_connect dyn: connect to peer '192.168.7.216:8101:rack1:dc1:1234567892'
[Fri May 15 01:08:22 2015] dyn_message.c:227 alloc_msg_count : 2
[Fri May 15 01:08:22 2015] dyn_dnode_peer.c:1023 dnode_peer_connect dyn: connect to peer '192.168.7.248:8101:rack2:dc2:1234567891'
[Fri May 15 01:08:22 2015] dyn_message.c:227 alloc_msg_count : 3
[Fri May 15 01:08:22 2015] dyn_dnode_peer.c:1023 dnode_peer_connect dyn: connect to peer '192.168.7.78:8101:rack2:dc2:1234567892'
[Fri May 15 01:08:22 2015] dyn_message.c:227 alloc_msg_count : 4
[Fri May 15 01:08:22 2015] dyn_core.c:523 =====================Peers info=====================
[Fri May 15 01:08:22 2015] dyn_core.c:527 Server pool          : 0
[Fri May 15 01:08:22 2015] dyn_core.c:530 ==============================================
[Fri May 15 01:08:22 2015] dyn_core.c:532       Peer DC            : 'dc1'
[Fri May 15 01:08:22 2015] dyn_core.c:533       Peer Rack          : 'rack1'
[Fri May 15 01:08:22 2015] dyn_core.c:535       Peer name          : '192.168.7.215'
[Fri May 15 01:08:22 2015] dyn_core.c:536       Peer pname         : '192.168.7.215:8101'
[Fri May 15 01:08:22 2015] dyn_core.c:538       Peer state         : 7
[Fri May 15 01:08:22 2015] dyn_core.c:539       Peer port          : 8101
[Fri May 15 01:08:22 2015] dyn_core.c:540       Peer is_local      : 1 
[Fri May 15 01:08:22 2015] dyn_core.c:541       Peer failure_count : 0 
[Fri May 15 01:08:22 2015] dyn_core.c:542       Peer num tokens    : 1
[Fri May 15 01:08:22 2015] dyn_token.c:96               Token : 1 1234567891 1 
[Fri May 15 01:08:22 2015] dyn_core.c:530 ==============================================
[Fri May 15 01:08:22 2015] dyn_core.c:532       Peer DC            : 'dc1'
[Fri May 15 01:08:22 2015] dyn_core.c:533       Peer Rack          : 'rack1'
[Fri May 15 01:08:22 2015] dyn_core.c:535       Peer name          : '192.168.7.216'
[Fri May 15 01:08:22 2015] dyn_core.c:536       Peer pname         : '192.168.7.216:8101:rack1:dc1:1234567892'
[Fri May 15 01:08:22 2015] dyn_core.c:538       Peer state         : 4
[Fri May 15 01:08:22 2015] dyn_core.c:539       Peer port          : 8101
[Fri May 15 01:08:22 2015] dyn_core.c:540       Peer is_local      : 0 
[Fri May 15 01:08:22 2015] dyn_core.c:541       Peer failure_count : 0 
[Fri May 15 01:08:22 2015] dyn_core.c:542       Peer num tokens    : 1
[Fri May 15 01:08:22 2015] dyn_token.c:96               Token : 1 1234567892 1 
[Fri May 15 01:08:22 2015] dyn_core.c:530 ==============================================
[Fri May 15 01:08:22 2015] dyn_core.c:532       Peer DC            : 'dc2'
[Fri May 15 01:08:22 2015] dyn_core.c:533       Peer Rack          : 'rack2'
[Fri May 15 01:08:22 2015] dyn_core.c:535       Peer name          : '192.168.7.248'
[Fri May 15 01:08:22 2015] dyn_core.c:536       Peer pname         : '192.168.7.248:8101:rack2:dc2:1234567891'
[Fri May 15 01:08:22 2015] dyn_core.c:538       Peer state         : 4
[Fri May 15 01:08:22 2015] dyn_core.c:539       Peer port          : 8101
[Fri May 15 01:08:22 2015] dyn_core.c:540       Peer is_local      : 0 
[Fri May 15 01:08:22 2015] dyn_core.c:541       Peer failure_count : 0 
[Fri May 15 01:08:22 2015] dyn_core.c:542       Peer num tokens    : 1
[Fri May 15 01:08:22 2015] dyn_token.c:96               Token : 1 1234567891 1 
[Fri May 15 01:08:22 2015] dyn_core.c:530 ==============================================
[Fri May 15 01:08:22 2015] dyn_core.c:532       Peer DC            : 'dc2'
[Fri May 15 01:08:22 2015] dyn_core.c:533       Peer Rack          : 'rack2'
[Fri May 15 01:08:22 2015] dyn_core.c:535       Peer name          : '192.168.7.78'
[Fri May 15 01:08:22 2015] dyn_core.c:536       Peer pname         : '192.168.7.78:8101:rack2:dc2:1234567892'
[Fri May 15 01:08:22 2015] dyn_core.c:538       Peer state         : 4
[Fri May 15 01:08:22 2015] dyn_core.c:539       Peer port          : 8101
[Fri May 15 01:08:22 2015] dyn_core.c:540       Peer is_local      : 0 
[Fri May 15 01:08:22 2015] dyn_core.c:541       Peer failure_count : 0 
[Fri May 15 01:08:22 2015] dyn_core.c:542       Peer num tokens    : 1
[Fri May 15 01:08:22 2015] dyn_token.c:96               Token : 1 1234567892 1 
[Fri May 15 01:08:22 2015] dyn_core.c:551 Peers Datacenters/racks/nodes .................................................
[Fri May 15 01:08:22 2015] dyn_core.c:555 Peer datacenter........'dc1'
[Fri May 15 01:08:22 2015] dyn_core.c:559       Peer rack........'rack1'
[Fri May 15 01:08:22 2015] dyn_core.c:560       Peer rack ncontinuumm    : 2
[Fri May 15 01:08:22 2015] dyn_core.c:561       Peer rack nserver_continuum    : 2
[Fri May 15 01:08:22 2015] dyn_core.c:555 Peer datacenter........'dc2'
[Fri May 15 01:08:22 2015] dyn_core.c:559       Peer rack........'rack2'
[Fri May 15 01:08:22 2015] dyn_core.c:560       Peer rack ncontinuumm    : 2
[Fri May 15 01:08:22 2015] dyn_core.c:561       Peer rack nserver_continuum    : 2
[Fri May 15 01:08:22 2015] dyn_core.c:566 ...............................................................................
[Fri May 15 01:08:22 2015] dyn_connection.c:561 sendv on sd 11 77 of 77 in 2 buffers
[Fri May 15 01:08:22 2015] dyn_dnode_request.c:334 dnode_req_send_done entering!!!
[Fri May 15 01:08:22 2015] dyn_connection.c:561 sendv on sd 12 30 of 30 in 1 buffers
[Fri May 15 01:08:22 2015] dyn_dnode_request.c:334 dnode_req_send_done entering!!!

Does the config file has something wrong?

**Comment by timiblossom** [comment]
It seems like your Dynomite process cannot connect to the local Redis process. 
Can you change your config to use redis' IP as "localhost" or 127.0.0.1 instead of the regular IP as you might add some overhead if you go through that path?

It is also a good idea if you set up each instance to make sure they work as  individual units first before adding more nodes.

**Comment by hexusheng** [comment]
Thanks for your quick response. 
 1) I have tried to use the "localhost" and "127.0.0.1" instead of the regular IP, but it also did't work.
Every time the dynomite process startup, it connected to the local Redis process successfully, but after several seconds the connection between Dynomite and Redis lost.
If gossip was disabled , redis-cli works well.It is so stange!

2) With 1 datacenter with 2 racks each containing 2 nodes, if one node was down, the dynomite could proxy to another node in different rack for reads?

**Comment by timiblossom** [comment]
1- Please run with gossip disable.  There were some changes that might break it. 
There are two way to supply network topology: gossip and using a local daemon (https://cloud.githubusercontent.com/assets/4102322/6461488/b16d3496-c1a0-11e4-808d-eea13164a006.png?raw=true%20=649x576).

2-Currently dynomite can't do that so you need to use our java client http://github.com/Netflix/dyno and if you use another language, you have to do this yourself.
