### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [Netflix/dynomite#137]
Would you like to replace more defines for constant values by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages) to stress their relationships?
* [DN_…](https://github.com/Netflix/dynomite/blob/1fd92c425c70ab0d98c3b12ffe670643c521da86/src/dyn_core.h#L66)
* [LOG_…](https://github.com/Netflix/dynomite/blob/c348e1aacd28ca8ffcb07b8f1ad755c1b4175e61/src/dyn_log.h#L33)

**Comment by timiblossom** [comment]
I think we are fine with this.  There would be too much code changes for us.  However, we would be happy to accept your patch.
