### ISSUE TITLE
Data Distribution

### ISSUE THREAD

**Issue by mfouilleul** [Netflix/dynomite#138]
Hi, 

Can you explain in few lines the logic of the consistent hashing, data distribution and some clues related to tokens? 

Is there a simple logic as we can find in Redis Cluster like HASH_SLOT = CRC16(key) mod 16384 ? 

I would like to know if I can test myself if a given key is in the good place but for that, I should understand how Dynomite routes my key. 

I know that Dynomite is mooving every day, we are following that with care and test it a lot since several months, it is quite hard to know what tag/version should be tested and what part of the doc/wiki is obsolete or not but we love the product and we'll try our best to contribute in our way.

Max

**Comment by timiblossom** [comment]
For consistent hashing, each node has a token that indicate what range of data it should own.
We use murmur for the hashing.  

We will come up with a tagging method and I will add this in the FAQ.  For now, just use the master branch and for  the new things, use Dev branch.

**Comment by ipapapa** [comment]
We have started to using tags in the latest version. Master branch will usually match the latest tag.
