### ISSUE TITLE
client TCP server on port 8102 dying

### ISSUE THREAD

**Issue by ralfonso** [Netflix/dynomite#141]
Unfortunately the logs are not helpful here, but the TCP server on port 8102 is going down. The peer server on 8101 and stats server on 22222 remain up with no problem. The only "troublesome" event that appears in the log prior to the TCP server crashing is several thousand ```alloc_msg_count: ######``` messages and then some "Connection reset by peer" messages.

**Comment by timiblossom** [comment]
Can you copy the last few lines of the dump file? You need to set your environment to generate the dump file and then open it using gdb, then give us the last 10-20 lines of it. Thanks.

**Comment by ralfonso** [comment]
Would a dump be present? There is no segfault here, the tcp server on 8102 simply leaves the LISTEN state.

**Comment by timiblossom** [comment]
You need to set up your env to generate a core dump file whenever there is a crash.  For ubuntu, here is a link: http://stackoverflow.com/questions/6152232/how-to-generate-core-dump-file-in-ubuntu

**Comment by ralfonso** [comment]
Yes, but there is no segfault. The dynomite process continues running.

**Comment by ipapapa** [comment]
@ralfonso it sounds to me that you are hitting the maximum allocated messages limit. Can you send us the last few lines of your logs, and then can you run Dynomite `-m 200000`?

**Comment by ralfonso** [comment]
I no longer use Dynomite. Thanks.
