### ISSUE TITLE
Dynomite failing to compile src/hashkit (openssl dir missing) 

### ISSUE THREAD

**Issue by willhughes** [Netflix/dynomite#172]
Compiling on Centos 7 x64 with Development Tools, and I'm getting this error when running make on the current git master for dynomite. 

    Making all in hashkit
    make[3]: Entering directory `/home/will/dynomite/src/hashkit'
    gcc -DHAVE_CONFIG_H -I. -I../..  -I ../../src -I ../../contrib/murmur3  -Wall -Wshadow -Wno-unused-parameter -Wno-unused-value -g -O2 -MT dyn_crc16.o -MD -MP -MF .deps/dyn_crc16.Tpo -c -o dyn_crc16.o dyn_crc16.c
    In file included from ../../src/dyn_core.h:136:0,
                     from ../../src/dyn_token.h:7,
                     from dyn_crc16.c:23:
    ../../src/dyn_crypto.h:14:25: fatal error: openssl/bio.h: No such file or directory
     #include <openssl/bio.h>
                             ^
    compilation terminated.
    make[3]: *** [dyn_crc16.o] Error 1
    make[3]: Leaving directory `/home/will/dynomite/src/hashkit'

Looking at dyn_crypto.h, I can see it's indeed referencing openssl/bio.h, along with a bunch of other stuff from an openssl directory - except that this directory doesn't exist, and I can't find any trace of that ever being in the src directory.

I followed the instructions, and didn't get any prior warnings that I could see in configure. 

The only reference to SSL I can find when running configure is this: 
   
    checking for SSL_read in -lssl... no
    checking for OPENSSL_init in -lcrypto... no

Forgive me, I'm not a C++ dev or familiar with the makefile syntax, so I'm a bit lost - am I supposed to have those installed or copied across from somewhere, or is it provided by a package that I'm supposed to have installed on the system.

**Comment by ipapapa** [comment]
I am assuming you are missing libssl-dev. This is the full list of dependencies:
	autoconf \
	build-essential \
	dh-autoreconf \
	git \
	libssl-dev \
	libtool \
	python-software-properties \
	redis-server \
	tcl8.5

**Comment by willhughes** [comment]
Sorry for the lag in responding - yep, that worked. Thanks!
