### ISSUE TITLE
client couldn't get the response when the node is standby

### ISSUE THREAD

**Issue by wuyingfengsui** [Netflix/dynomite#179]
After I make the node standby though the command `curl http://127.0.0.1:22222/state/standby`, I find redis-cli can't get any response and just be hanged. I think [this](https://github.com/Netflix/dynomite/commit/e270838613d02bd89b88b136b23d183b5be530ba) occasion it.

**Comment by shailesh33** [comment]
You are right and the change you pointed is the one causing the issue. The assumption is every  request has a selected response that needs to be sent back. But it seems there is some shortcut code which just sets the error in the request and we cook up a response while sending it. Now the code sees there is no selected response and bails out. I will see that I can do.

**Comment by shailesh33** [comment]
By the way, may I know why you put the node in standby?

**Comment by shailesh33** [comment]
I have fixed the issue and the pull request is merged to the dev branch.

**Comment by wuyingfengsui** [comment]
Thanks. I just try to bring up a new node with warm data by @timiblossom said in the #51.

**Comment by ipapapa** [comment]
@wuyingfengsui did you create a script to automate the process described in #51 i.e. in Python script? If yes, please consider submitting the script as others may be interested as well.

**Comment by wuyingfengsui** [comment]
@ipapapa No. This is just a test. If I take the decision to use it, I will consider it.

**Comment by shailesh33** [comment]
Feel free to get back to us if you have any issues.
