### ISSUE TITLE
Supporting glitchs

### ISSUE THREAD

**Issue by mfouilleul** [Netflix/dynomite#187]
Hi.

I try to simulate some networks issues with some iptables rules, if a node is "out" for a given time, can you confirm me that it losts for ever the keys written during this laps of time or is there some mecanism to replay the lost SETs. Is that the mbuf purpose? 

Thanks.

**Comment by ipapapa** [comment]
Hello @mfouilleul  mbufs are used to enable zero-copy between the data received from the client and forwarded to Redis. Currently, the aforementioned updates on the node that is "out" are lost. However, the data are [replicated](https://github.com/Netflix/dynomite/wiki/Replication) numerous times. Hence, if you use the [Dyno](https://github.com/netflix/dyno), the client will switch to another rack, and if you enable [consistency](https://github.com/Netflix/dynomite/wiki/Consistency) the client may see the correct data even when one node is out.

**Comment by ipapapa** [comment]
Hello @mfouilleul did I answer your question above?
