### ISSUE TITLE
Multiple nodes in Rack = Data stored only in 1 backend

### ISSUE THREAD

**Issue by nimeops** [Netflix/dynomite#191]
Hi,
i'm always using Dynomite for HA / Replication between Datacenters and Racks on each Memcached or Redis Servers (localhost). So, i'm using only one Node per Rack for perfect mirror.
Works great.

Trying to use more nodes in Racks, and it seems that data are always stored in the same backend (smallest token) in the Rack - (with memcached or Redis).

Data is available on every node (read / get)... no problem.
Data can be written from every node... no problem
But always stored on the same Memcached or Redis backend.

Is it normal?
No sharding?

Some guys told me that we need to use Dyno Client for that... 
Could you confirm?

Configurations : 
```javascript
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_seed_provider: simple_provider
  dyn_listen: backend1:8101
  listen: backend1:8102
  dyn_seeds:
  - backend2:8101:rack1:dc1:2
  - backend3:8101:rack2:dc2:3
  servers:
  - 127.0.0.1:11211:1
  tokens: '1'
  data_store: 1

dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_seed_provider: simple_provider
  dyn_listen: backend2:8101
  listen: backend2:8102
  dyn_seeds:
  - backend1:8101:rack1:dc1:1
  - backend3:8101:rack2:dc2:3
  servers:
  - 127.0.0.1:11211:1
  tokens: '2'
  data_store: 1

dyn_o_mite:
  datacenter: dc2
  rack: rack2
  dyn_seed_provider: simple_provider
  dyn_listen: backend3:8101
  listen: backend3:8102
  dyn_seeds:
  - backend1:8101:rack1:dc1:1
  - backend2:8101:rack1:dc1:2
  servers:
  - 127.0.0.1:11211:1
  tokens: '3'
  data_store: 1
```

**Comment by timiblossom** [comment]
Try to use this script to generate a list of yaml files and tokens for you:
https://github.com/Netflix/dynomite/blob/master/scripts/generate_yamls.py

You are assigning node 1 with token 1 and node 2 with token 2.  This means that node 2 will own the majority of the data while node 1 will only own data that has tokens betwen [1,2) which is almost nothing.

The way the token calculation works is that we take the max int (4294967295) and divide out to the number of nodes.

**Comment by nimeops** [comment]
Hi.
Sure, i'm stupid... i've forgotten it (4294967295).

My error makes me think about it.
 Note that : 
* node 1 / token 1000
* node 2 / token 2000

All datas are stored on node 1, not node 2 as you explain.

In my previous test, the same : all datas stored in node token 1, not 2

So 4294967295 with 2 nodes ??? => 2147483647,5... should be stored on token 2000 no?

Where am i wrong?

**Comment by timiblossom** [comment]
I think I got it wrong.  It should be the other way

**Comment by ipapapa** [comment]
Not any more activity on this question, so closing for now.
