### ISSUE TITLE
How to Build Florida

### ISSUE THREAD

**Issue by diegopacheco** [Netflix/dynomite#195]
Looks like Florida does not boot up by the default dynomite process, i trying to CURL the REST endpoints in Florida but i always get a connection  refused. 

I have installed dynomite doing this:
https://gist.github.com/diegopacheco/71985b88c28e07e02b49

IF i understood things correctly Florida is a side car like Prian and needs be build separately, here:
https://github.com/Netflix/dynomite/tree/master/src/seedsprovider

```bash
[ec2-user@ip-10-0-1-67 seedsprovider]$ ls
dyn_florida.c  dyn_florida.o  dyn_seeds_provider.h  libseedsprovider.a  Makefile  Makefile.am  Makefile.in
[ec2-user@ip-10-0-1-67 seedsprovider]$ sudo make install
make[1]: Entering directory `/opt/dynomite/src/seedsprovider'
make[1]: Nothing to be done for `install-exec-am'.
make[1]: Nothing to be done for `install-data-am'.
make[1]: Leaving directory `/opt/dynomite/src/seedsprovider'
[ec2-user@ip-10-0-1-67 seedsprovider]$ ls -lsa
total 128
 4 drwxr-xr-x 3 root root  4096 Nov 18 21:59 .
 4 drwxr-xr-x 8 root root  4096 Nov 18 21:59 ..
 4 drwxr-xr-x 2 root root  4096 Nov 18 21:59 .deps
 8 -rw-r--r-- 1 root root  4647 Oct 19 23:55 dyn_florida.c
28 -rw-r--r-- 1 root root 28600 Nov 18 21:59 dyn_florida.o
 4 -rw-r--r-- 1 root root   257 Oct 19 23:55 dyn_seeds_provider.h
32 -rw-r--r-- 1 root root 28830 Nov 18 21:59 libseedsprovider.a
20 -rw-r--r-- 1 root root 17379 Nov 18 21:58 Makefile
 4 -rw-r--r-- 1 root root   282 Oct 19 23:55 Makefile.am
20 -rw-r--r-- 1 root root 17739 Nov 18 21:58 Makefile.in
[ec2-user@ip-10-0-1-67 seedsprovider]$
```

How i build and install Florida?

**Comment by timiblossom** [comment]
Ah, Florida is a local proxy service that you need to build for dynomite process to consume the data.

You can take a look at a nodejs code and with a few lines, you can have a proxy http service:

http://blog.modulus.io/build-your-first-http-server-in-nodejs

Then, the data could be stored inside a mysql or some data file or whatever that you can update the entries.

**Comment by diegopacheco** [comment]
@timiblossom what are the parameters / commands  to build Florida properly? The source that is on seedsprovider is complete? Or you guys did not open source Florida completely?

**Comment by diegopacheco** [comment]
I found this out https://github.com/Netflix/dynomite/issues/93

**Comment by timiblossom** [comment]
Florida is just a name of the local proxy.  We have not opened source Florida yet.  You can write a simple nodejs to act as a local http server in its place to generate a list of nodes.  Yes, you need to add this into dynomite.yml to force dynomite to look for this service:

  dyn_seed_provider: florida_provider

**Comment by diegopacheco** [comment]
@timiblossom @ipapapa 

I did this:

  dyn_seed_provider: florida_provider

```bash
[ec2-user@ip-10-0-1-67 dynomite]$ cat redis_rack1_node.yml
dyn_o_mite:
  datacenter: dc
  rack: rack1
  dyn_seed_provider: florida_provider
  dyn_listen: 0.0.0.0:8101
  listen: 0.0.0.0:8102
  servers:
  - 127.0.0.1:6379:1
  tokens: 0
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
```

And it works, but looks like on this centralized static gossip we need point each to to each other as seed...

**Comment by diegopacheco** [comment]
@timiblossom  end up getting there too - i just saw it know.... thanks  :-)
