### ISSUE TITLE
Update scripts/dynomite.init to be LSB compliant

### ISSUE THREAD

**Issue by akbarahmed** [Netflix/dynomite#206]
Is there any interest in updating the `scripts/dynomite.init` script to be LSB compliant?

I've started to update this script in my forked repo. I'll issue a pull request when I'm done if this is a desired feature.

**Comment by shailesh33** [comment]
Sure go ahead. more helping hands are always welcome

**Comment by ipapapa** [comment]
@akbarahmed It is indeed great; please consider issuing the pull request to the "dev" branch.

**Comment by akbarahmed** [comment]
Quick status update. I'm almost done with a 1st draft of the LSB compliant init script.
