### ISSUE TITLE
Flush on memcached?

### ISSUE THREAD

**Issue by nimeops** [Netflix/dynomite#224]
Hi, 
it seems that "flush" command not applied with dynomite with memcached backend?

Bug or "normal"?

Thank you

**Comment by ipapapa** [comment]
@nimeops flushall is not yet supported by Dynomite for memcached. You can see most of the memcache implementation [here](https://github.com/Netflix/dynomite/blob/dev/src/proto/dyn_memcache.c). To be honest recently we have been focused a lot on the Redis protocol coverage, so we definitely need some help on improving the memcache protocol.

**Comment by ipapapa** [comment]
There are some discussions about enhancing Memcached protocol in https://github.com/Netflix/dynomite/issues/227 hence this is a duplicate issue.
