### ISSUE TITLE
Automation/DevOps

### ISSUE THREAD

**Issue by ipapapa** [Netflix/dynomite#225]
We have been developing a couple of Automation for Dynomite deployments. You may find some of these under scripts: https://github.com/Netflix/dynomite/tree/dev/scripts

For example:
* Redis RSS Healing if Redis Utilization goes high.
* Redis BGREWRITEAOF to append files to disk.
* Generate YML files with tokens

However, there are many more ideas around automation that it would be nice to have.

**Comment by marclop** [comment]
Hi,

I'm quite new to this project and have been reading about it and seems super interesting to me, I'm more than willing to provide any help I can provide around automation/DevOps.

What other ideas do you have?

**Comment by ipapapa** [comment]
Hello @marclop some ideas are (a) seed generator to become a bit more intelligent; (b) warm up functionality in case Dynomite node goes down to stream data from another node. If you want to build some more generic scripting tools, a script library to iterate across Dynomite nodes (provided a set of IP addresses) and then more specific scripts like restart dynomite and if needed the data store (grep the .yml file to see what data store is running and act accordingly if it is redis or memcached). If you have any of your ideas, please let us know.

**Comment by ipapapa** [comment]
Most of these have been done in one way or another, and there are some duplicate ones.
