### ISSUE TITLE
Polyglot Dynomite Client

### ISSUE THREAD

**Issue by ipapapa** [Netflix/dynomite#226]
Dynomite can support any Redis/Memcached client. For a complete list see of Redis and Memcached client APIs see here:
* http://redis.io/clients
* https://code.google.com/p/memcached/wiki/Clients

There are some features that can benefit from the distributed nature of Dynomite and exist currently in [Dyno](https://github.com/Netflix/dyno) (Dynomite's Java client). Since people tend to use different client libraries, it will be nice to make the python, node.js, golang redis/memcached clients to support some of the following features:

*List of interesting features*
* Connection pooling of persistent connections - this can help reduce connection churn on the Dynomite server with client connection reuse. 
* Topology aware load balancing (Token Aware) for avoiding any intermediate hops to a Dynomite coordinator node that is not the owner of the specified data. 
* Application specific local rack affinity based request routing to Dynomite nodes.
* Application resilience by intelligently failing over to remote racks when local Dynomite rack nodes fail.
* Application resilience against network glitches by constantly monitoring connection health and recycling unhealthy connections.   
* Capability of surgically routing traffic away from any nodes that need to be taken offline for maintenance. 
* Flexible retry policies such as exponential backoff etc.
* Insight into connection pool metrics
* Highly configurable and pluggable connection pool components for implementing your advanced features.

**Comment by SanjeevMurthy** [comment]
I believe Dyno is available only as Java client. When can we expect Dyno - **Nodejs** client ?

**Comment by ipapapa** [comment]
@SanjeevMurthy Correct Dyno client is a wrapper around Jedis (Redis Java client), nonetheless Dynomite works with any Redis client including NodeJs.

**Comment by SanjeevMurthy** [comment]
@ipapapa  thank you.

**Comment by ipapapa** [comment]
Moved this to the Projects: https://github.com/Netflix/dynomite/projects/3

**Comment by nghialt** [comment]
hi everyone, any update on this?

**Comment by ipapapa** [comment]
Any update on what client? We will Open Source soon our Dynomite-Explorer (UI) that will showcase some of the things we have done for Node.js. I do not have an estimate for that right now.

**Comment by mek-omkar** [comment]
I'm looking for Go lang dynomite client. is it available?

**Comment by ipapapa** [comment]
You can use the vanilla Go Redis client but you may miss some of the above features. You do not need a special client to use Dynomite. We currently do not provide a specialized client for Go.

**Comment by mek-omkar** [comment]
@ipapapa  thanks for the information.
