### ISSUE TITLE
Memcached Enhancements

### ISSUE THREAD

**Issue by ipapapa** [Netflix/dynomite#227]
As of today, most of our focus has been on enhancing the support of Redis as an underlying storage engine for Dynomite. 

Dynomite also supports Memcached. The protocol impelementaion needs some enhancements and proper testing. There is currently a working branch about it:
https://github.com/Netflix/dynomite/tree/memcacheFix

More info about the implemented protocol:
https://github.com/Netflix/dynomite/blob/memcacheFix/src/proto/dyn_memcache.c

**Comment by StephanDollberg** [comment]
How would you compare the performance of dynomite (twemproxy) proxying memcached vs proxying redis?

**Comment by ipapapa** [comment]
@StephanDollberg we have not compared the performance of the two, but I am sure in a production deployment those in-memory differences would not be significant. We have been mainly using Redis, because of the advanced data structure support (hashes, sets, lists etc). 

However, memcached has been out for more years than Redis, so there are several deployments that are still using memcached. We would love for somebody to enhance and test the memcached protocol parser.

**Comment by ipapapa** [comment]
Created new Project for it: https://github.com/Netflix/dynomite/projects/4
