### ISSUE TITLE
Multithreaded Dynomite

### ISSUE THREAD

**Issue by shailesh33** [Netflix/dynomite#231]
During all the performance testing done till now, it was evident that dynomite will gain a lot when it goes multithreaded. The idea here is that a single thread does a good amount of work processing each connection (client, peer server, server, peer client etc). And all is sequential. Some initial analysis indicate that the messages stay good amount of time in the in queue of the connection to be sent out or in the out queue to be picked up. If there is a thread servicing these connections, we believe we will see a lot more performance
So here is what we propose:
PHASE I
1) All client connections are handled by a single thread just like today, That thread has a connection to the underlying data store server. This is the existing code.
2) However Every dnode peer client and dnode peer server connection has its own thread. The inqueue of the peer connections is protected by a spin lock (?) and client connections can add to the inqueue. Also the peer connection has its own event epoll object which gets triggered just like we do today for the common event base (main thread).

For more understanding look at the dyn_stats thread which handles the requests on the stats port (22222). It has its own inqueue, its own epoll object.

PHASE II:
It will be further better if every Dnode peer thread that we created in step 2 above, has its own connection to the underlying data store that way the messages from all the peers do not compete with the messages (requests) from the client connection on the main thread.  With this, for the underlying data store, these extra connections are just like more client connections and its own "parallelism" will help get more performance out of the data store.

Feel free to comment, ask questions & clarifications.

**Comment by timiblossom** [comment]
One drawback of this is that we would have many threads over a much smaller number of cores.  For example, think of a 100 or more node cluster.  This would cause many context switches to compete over CPU cores.  There is a model that I am a fan of that there is a master thread created initially that do all of the initial works.  Then, the master thread would create a number of worker threads (same as the number of CPU cores).  Every single worker thread would then do all of the works just like our current single worker thread where there is a shared nothing architecture.  In this way, we can retain most of our data structures in the current code while not introducing any locking penalty on the performance.

**Comment by akbarahmed** [comment]
My $0.02. Multithreaded Dynomite will be valuable once the persistent backends are up and running. Most of the RESP servers with persistent backends are multithreaded including Ardb and SSDB.

**Comment by shailesh33** [comment]
@akbarahmed No. Infact, multithreaded will make things better in every case because we spend more than 50% cpu in replicating to other nodes.

**Comment by ipapapa** [comment]
@shailesh33 it seems that Github has added the notion of [Projects](https://github.com/Netflix/dynomite/projects). I think we can resolve this issue and move some of the description of the work to the project [Multi-threaded ](https://github.com/Netflix/dynomite/projects/1)
