### ISSUE TITLE
Product roadmap

### ISSUE THREAD

**Issue by akbarahmed** [Netflix/dynomite#237]
IMHO, the Dynomite project may benefit from a product roadmap. Performing some light product management tasks may help provide guidance to our development efforts and may help to ensure that we build features that deliver maximum value to users.

The goal of the product management (PM) tasks would be:

1. To speak with current users of Dynomite to understand how they use Dynomite
2. To understand current use cases (cache, pub/sub, volatile vs. persistent storage, etc)
3. To understand current pain points with Dynomite so that we develop solutions to these problems (packaging, deployment, scale up/down, monitoring, etc.)
4. To help us prioritize development tasks based on user requirements

Please let me know if this is something that you think would help the Dynomite project. If so, I'd be happy to take a first pass at creating the roadmap.

**Comment by timiblossom** [comment]
@akbarahmed This is great.  We are in the process of organizing our roadmap and how to present it out to the users and open source community.  If you can help to run this or organize this, this would be very helpful for us and the community in general.  

For a starting point, our roadmap is the issues that we labeled as "Need Help".  We still have other issues that we have discussed internally and have not opened one on github yet.

Please suggest us a better way of doing thing.

Thanks,

**Comment by akbarahmed** [comment]
@timiblossom I'll work on an overall action plan. I'll then share it so that it can be modified based on community input.

In general, I'm very interested in knowing how Dynomite is used currently and how we can improve the project for the current user base while also finding new users who are similar to the existing ones.

**Comment by timiblossom** [comment]
@akbarahmed  I suggest you just read through the issues that we have there and the architecture overview on the wiki as there are just too much details to repeat here.  I think we cover very much what a new user needs to know on our wiki page.  However, we still think we need to do better as our documents might not be so intuitive.

**Comment by akbarahmed** [comment]
@timiblossom Will do.

**Comment by ipapapa** [comment]
@akbarahmed are there any pending actions on this issue?

**Comment by akbarahmed** [comment]
@ipapapa No. This issue can be closed.
