### ISSUE TITLE
man page not included in the package

### ISSUE THREAD

**Issue by akbarahmed** [Netflix/dynomite#241]
Is there a reason why the following line is commented in `Makefile.am`? If not, I'd like to uncomment this line so that the man page is installed via `make install`.

```bash
#dist_man_MANS = man/dynomite.8
```

**Comment by timiblossom** [comment]
Good idea. I recall that is for the man page.  Please go ahead and address it.  Thanks.

**Comment by akbarahmed** [comment]
I'll make this change now and submit a pull request.

**Comment by shailesh33** [comment]
I am wondering what are the contents of the man page. @akbarahmed ?

**Comment by akbarahmed** [comment]
@shailesh33 It's the original man page located at https://github.com/Netflix/dynomite/blob/dev/man/dynomite.8

That said, I will review the man page to check if it needs to be updated.

**Comment by akbarahmed** [comment]
@shailesh33 The man page is out of date. I am taking the kids to the zoo right now. However, I'll update the man page and submit a PR this evening.
