### ISSUE TITLE
Redis EVAL/EVALSHA commands not replicated 

### ISSUE THREAD

**Issue by clemper** [Netflix/dynomite#245]
Hi,

I am testing a 2 rack Redis dynomite cluster.  Rack1 has 2 nodes with the keys equally distributed.  Rack2 has a single node owning all keys.  

If I connect to Rack1 and issue 4 INCR commands, I see the keys correctly distributed to each node in Rack1 and replicated to the single node in Rack2.

```
  >redis-cli -p 8102 incr ctl:123
  >redis-cli -p 8102 incr ctl:234
  >redis-cli -p 8102 incr ctl:345
  >redis-cli -p 8102 incr ctl:456
```

However, if I use EVAL with an equivalent Lua script, the keys are correctly distributed to each node in Rack1 but are not replicated at all to Rack2.

```
>redis-cli -p 8102 eval "redis.call('INCR',KEYS[1])" 1 ctl:123
>redis-cli -p 8102 eval "redis.call('INCR',KEYS[1])" 1 ctl:234
>redis-cli -p 8102 eval "redis.call('INCR',KEYS[1])" 1 ctl:345
>redis-cli -p 8102 eval "redis.call('INCR',KEYS[1])" 1 ctl:456
```

Thanks,
@clemper

**Comment by ipapapa** [comment]
EVAL and EVALSHA support is limited to scripts that take at least 1 key. If multiple keys are used, all keys must hash to the same server. If you use more than 1 key, the proxy does no checking to verify that all keys hash to the same server, and the entire command is forwarded to the server that the first key hashes to. See: https://github.com/Netflix/dynomite/blob/dev/notes/redis.md

**Comment by clemper** [comment]
@ipapapa thanks for your reply.  I'm not clear how this applies to my situation since all 4 of my commands are issued separately and contain only a single key.    The parameter 1 indicates the number of keys.   The 4 keys are actually distributed to the first rack exactly like using the INCR command directly, but are simply not replicated to the second rack as I expect.

**Comment by ipapapa** [comment]
@clemper let me take a look once I have a chance and will get back to you.

**Comment by ipapapa** [comment]
@clemper I am sorry for my delay. Here is what happens: The INCR command gets replicated because it is considered a write command (is_read = 0):
https://github.com/Netflix/dynomite/blob/dev/src/proto/dyn_redis.c#L620

The EVAL command is not replicated because it is considered a read command:
https://github.com/Netflix/dynomite/blob/dev/src/proto/dyn_redis.c#L732
