### ISSUE TITLE
Clarify Token Uniqueness

### ISSUE THREAD

**Issue by danchia** [Netflix/dynomite#248]
In C*, each node must have a token unique to the whole cluster.

In Dynamo, it seems things are a little different, and the tokens need only be unique to the rack.

@timiblossom does this seem right?

**Comment by akbarahmed** [comment]
@danchia This is not an answer to your question, but is a clarification on how Cassandra works. In Cassandra tokens are unique per data center (DC). Each DC has a complete token ring and therefore node tokens may repeat across, but not within, DCs.

**Comment by timiblossom** [comment]
@danchia @akbarahmed  In C*, they have some legacy code that use token id as node identification so it must be unique to the whole cluster across all DCs.

In Dynomite, we identify a node by tuple (DC, Rack, token id).  Therefore, token id uniqueness requirement is only within a rack, not DC nor cluster level.
