### ISSUE TITLE
dynomite -t conf-file

### ISSUE THREAD

**Issue by akbarahmed** [Netflix/dynomite#249]
The `-t` flag should accept a path to a configuration file.

## Current functionality

The `-t` flag tests the configuration file located at `conf/dynomite.yaml`.

## Desired functionality

`dynomite -t path-to-configuration-file`

## Reason for change in functionality

There are several reasons why `-t` should accept a path to a configuration file:

1. A user may not be using the default configuration file and needs to test it.
2. When Dynomite is installed via `yum` or `apt-get`, then the configuration file will be in `/etc/dynomite`, not the default location.
3. In a production environment, a user may need to test a new configuration file before restarting `dynomite` with the new configuration file.

**Comment by shailesh33** [comment]
Agree. sounds like a good idea.

**Comment by shailesh33** [comment]
do you plan to only test parsing or existence of nodes etc

**Comment by akbarahmed** [comment]
@shailesh33 The test for parsing is already written. However, the configuration file is hard coded to `conf/dynomite.yaml`. All I'm going to do is accept a path on the command line.

**Comment by akbarahmed** [comment]
Closing this issue. The proposed functionality already exists. All you have to do is add a `-c path-to-conf-file`.

**For example:**

`dynomite -t -c /etc/dynomite/dynomite.yml`
