### ISSUE TITLE
Integrating Dynomite with ARDB

### ISSUE THREAD

**Issue by timiblossom** [Netflix/dynomite#254]
ARDB (https://github.com/yinqiwen/ardb) seems like a forked Redis server that can store data on both disk and memory.  It already supports storage engines such as LMDB, LevelDB, RocksDB and probably others.  

What if we support this in Dynomite by swapping out our Redis with ARDB?  We still provide the same Redis protocol to clients and our internal communication protocol to the underline storage process is still Redis protocol.  Basically, we get all the juices running Dynomite with different storage engines with a "small" effort.

Later on, we can try to embed ARDB inside Dynomite to run as one process.

**Comment by ipapapa** [comment]
From the Dynomite side, there were minimal changes, i.e. other than of some minor changes in the core affinity scripts which I will make today in the OSS. The ARDB integration has been complete.
