### ISSUE TITLE
Config reload

### ISSUE THREAD

**Issue by axot** [Netflix/dynomite#255]
Does dynamite support reload config or graceful restart?

**Comment by ipapapa** [comment]
There are some configurations that you can pass runtime through REST calls like consistency level, log level, Dynomite state etc:  https://github.com/Netflix/dynomite/blob/dev/src/dyn_stats.c#L990-L1103

Configuration file loading is done once during the context creation, hence Dynomite requires a restart for configuration file changes to take effect: https://github.com/Netflix/dynomite/blob/dev/src/dyn_core.c#L59

Dynomite does not support graceful restart.

**Comment by axot** [comment]
The REST APIs is great for get Dynomite State. I will try to test Dynomite cluster for a Redis HA setup tomorrow, thank you for your quick reply.
