### ISSUE TITLE
Does it support resharding without restart?

### ISSUE THREAD

**Issue by hy05190134** [Netflix/dynomite#260]

**Comment by akbarahmed** [comment]
@hy05190134 If I understand your question correctly, you asking about rebalancing the cluster without restarting nodes within the cluster.

With Dynomite you currently want to minimize cluster resizing (scaling up or down) as this is (as of today) a manual process. However, the ability to auto scale up/down is on the development agenda (Ref: https://github.com/Netflix/dynomite/issues/229).

**Comment by hy05190134** [comment]
OK, I know, expect to support earlier then can be auto operation for operators.

**Comment by ipapapa** [comment]
@hy05190134 has your question been answered? If yes, I can proceed closing this issue.

**Comment by hy05190134** [comment]
@ipapapa  thanks,  I will watch the develop branch if it support the function.

**Comment by ipapapa** [comment]
@hy05190134 thank you; the best way to follow new supported features is to follow the release comments: https://github.com/Netflix/dynomite/releases
