### ISSUE TITLE
Sporadically occurring error - Error: Connection reset by peer

### ISSUE THREAD

**Issue by akbarahmed** [Netflix/dynomite#270]
I spent all day on this error trying to figure out how to get it to reproduce consistently. However, it is randomly occurring, but very real.

I don't have much information to add b/c I have not been able to track this one down. The obvious issue is that the Dynomite - Redis connection is being terminated. Importantly, `redis-cli` is still able to connect to Redis without issue even when this error is occurring. Also, if I build v0.5.6 and start it, then the error goes away (so it's not a basic configuration issue).

# Summary

My **guess** is that a commit after v0.5.6 causes the issue b/c I have not seen this issue with v0.5.6. However, this is a pure guess.

When I see the error, the following occurs:

```bash
# Start Redis
redis-server /etc/redis/6379.conf

# Start dynomite
src/dynomite -c ./conf/redis_single.yml

# Try to connect
redis-cli -h localhost -p 8102 ping
Error: Connection reset by peer
```

However, even repeat builds on the same source directory is not giving me reproducible results.

I do have Docker containers with a build that demonstrates the error. 

I have also reproduced the error on Ubuntu 14.04.4 without containers.

The error has been reproduced across the following combinations of OS + env + Dynomite + Redis:

- Ubuntu 14.04.4: Dynomite v0.5.7 + Redis (2.8.4)
- Ubuntu 14.04.4: Dynomite v0.5.7 + Redis (3.0.7)
- Ubuntu 14.04.4 host + Docker (w/Ubuntu 14.04.4 base) + Dynomite v0.5.7 + Redis (2.8.4)

However, if I startup a clean VM and install using the exact same instructions then sometimes the error occurs and sometimes it does not.

**Comment by timiblossom** [comment]
@akbarahmed we will scan through our commits and try to spot this out.
Thanks for reporting.

**Comment by shailesh33** [comment]
We might have seen something like that. Do you have some logs? Anything in
tcp dump?

**Comment by akbarahmed** [comment]
@timiblossom @shailesh33 I don't have any logs as I've been creating / destroying VMs. Saving the logs would have been smart.

I think I found a way to get this to reproduce by changing the `make` flags. I can now get this to reproduce on both 0.5.6 and 0.5.7.

I am using the following `redis_single.yml` file:

```yaml
dyn_o_mite:
  dyn_listen: 127.0.0.1:8101
  data_store: 0
  listen: 127.0.0.1:8102
  dyn_seed_provider: simple_provider
  servers:
  - 127.0.0.1:6379:1
  tokens: 437425602
  pem_key_file: conf/dynomite.pem
```

### Use `make` == no error

```bash
wget https://github.com/Netflix/dynomite/archive/v0.5.6.tar.gz

gzip -dc v0.5.6.tar.gz | tar xf -

cd dynomite-0.5.6/

autoreconf -fvi

./configure --enable-bug=log

make

./src/dynomite -c conf/redis_single.yml

redis-cli -h localhost -p 8102 ping
PONG
```

### Use `make` flag `FLORIDA_REQUEST` and don't start Florida server == error

```bash
wget https://github.com/Netflix/dynomite/archive/v0.5.6.tar.gz

gzip -dc v0.5.6.tar.gz | tar xf -

cd dynomite-0.5.6/

autoreconf -fvi

./configure --enable-bug=log

make CFLAGS=-DFLORIDA_REQUEST='"\"GET /REST/v1/admin/get_seeds HTTP/1.0\r\nHost: 127.0.0.1\r\nUser-Agent: HTMLGET 1.0\r\n\r\n\""'

./src/dynomite -c conf/redis_single.yml

redis-cli -h localhost -p 8102 ping
Error: Connection reset by peer
```

I'm spinning up a clean VM currently to verify my results above.

**Comment by akbarahmed** [comment]
Confirmed: Setting `FLORIDA_REQUEST` appears to be the issue. I'll continue on this in the morning.

**Comment by shailesh33** [comment]
Thanks. I don't recall, is this a dynomite variable.

**Comment by akbarahmed** [comment]
@shailesh33 I think I have this figured out.

#### Solution

Remove `FLORIDA_REQUEST` from `./build.sh`. 

#### Overview

`FLORIDA_REQUEST` is used in:
- `./build.sh`
- `src/seedsprovider/dyn_florida.c`

#### `build.sh`

`FLORIDA_REQUEST` should not be used in `build.sh`. 

I have updated the file and will issue a PR in a few minutes.

#### `dyn_florida.c`

In `dyn_florida.c`, `FLORIDA_REQUEST` can be overridden by the `DYNOMITE_FLORIDA_REQUEST` env var.

`dyn_florida.c` is fine and does not require any updates.

#### `scripts/Florida/florida.js`

`scripts/Florida/florida.js` should be updated to use the following env vars (not a source of error, but update is required to maintain consistent behavior):

- `DYNOMITE_FLORIDA_REQUEST`
- `DYNOMITE_FLORIDA_PORT`

#### Related history

For history, please see:
- https://github.com/Netflix/dynomite/pull/200
- https://github.com/Netflix/dynomite/pull/203

**Comment by shailesh33** [comment]
look at a previous pull request. I think this was added recently for a dns
seeds provider.

**Comment by akbarahmed** [comment]
@shailesh33 I just read through https://github.com/Netflix/dynomite/commit/1f205719453f2bbdf97fe4fb1e62cf8b6be2a301. The commit related to the DNS provider does not affect the Florida provider.

**Comment by timiblossom** [comment]
@akbarahmed setting that seed provider wrong can cause some side effect.  For simple single node configuration, you can just use simple_provider.  Take a look at https://github.com/Netflix/dynomite/blob/dev/conf/redis_single.yml#L5

This will avoid all of the dns and seed settings.

**Comment by timiblossom** [comment]
@akbarahmed I verified that this is not an issue with the latest Dev build, Redis 3.0.7 and Ubuntu 14.04.3 LTS when I do 10K reads and 10K writes.  I also used redis_single.yml configuration file.

**Comment by akbarahmed** [comment]
@timiblossom Agreed. I'll close this issue. Also, I'll remove `FLORIDA_REQUEST` from the `build.sh` script.
