### ISSUE TITLE
Compile error under Centos 6.7

### ISSUE THREAD

**Issue by mansoor-s** [Netflix/dynomite#290]
The latest commit on the dev branch is failing to build under Centos 6.7, but is building fine under OSX. (commit e160d1fb718aa1242cde3d62d65cfc0d5b7e9d2e). 
I'm not sure which exact commit broke it as my previous build is quite old.

Running `gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)`

Build output:
```
Making all in hashkit
make[3]: Entering directory `/home/vagrant/netflix/dynomite/src/hashkit'
gcc -DHAVE_CONFIG_H -I. -I../..  -I ../../src -I ../../contrib/murmur3  -Wall -Wshadow -Wpointer-arith -Winline -Wunused-function -Wunused-variable -Wunused-value -Wno-unused-parameter -Wno-unused-value -Wconversion -Wsign-compare -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wmissing-declarations -Werror=implicit-function-declaration -g -O2 -MT dyn_crc16.o -MD -MP -MF .deps/dyn_crc16.Tpo -c -o dyn_crc16.o dyn_crc16.c
In file included from ../../src/dyn_core.h:129,
                 from ../../src/dyn_token.h:7,
                 from dyn_crc16.c:23:
../../src/dyn_util.h:352: error: redefinition of typedef ‘msec_t’
../../src/dyn_types.h:2: note: previous declaration of ‘msec_t’ was here
../../src/dyn_util.h:353: error: redefinition of typedef ‘usec_t’
../../src/dyn_types.h:3: note: previous declaration of ‘usec_t’ was here
In file included from ../../src/dyn_message.h:29,
                 from ../../src/dyn_core.h:132,
                 from ../../src/dyn_token.h:7,
                 from dyn_crc16.c:23:
../../src/dyn_types.h:1: error: redefinition of typedef ‘msgid_t’
../../src/dyn_types.h:1: note: previous declaration of ‘msgid_t’ was here
../../src/dyn_types.h:2: error: redefinition of typedef ‘msec_t’
../../src/dyn_util.h:352: note: previous declaration of ‘msec_t’ was here
../../src/dyn_types.h:3: error: redefinition of typedef ‘usec_t’
../../src/dyn_util.h:353: note: previous declaration of ‘usec_t’ was here
dyn_crc16.c:62: warning: no previous prototype for ‘hash_crc16’
dyn_crc16.c: In function ‘hash_crc16’:
dyn_crc16.c:68: warning: conversion to ‘uint32_t’ from ‘char’ may change the sign of the result
make[3]: *** [dyn_crc16.o] Error 1
make[3]: Leaving directory `/home/vagrant/netflix/dynomite/src/hashkit'
```

**Comment by flaviotorres** [comment]
Hi, I got the same here but then I realized I was not using the master branch, are you ?

[root@host dynomite]# git branch
* master

try cloning with: git clone https://github.com/Netflix/dynomite.git --branch master

**Comment by shailesh33** [comment]
That could be the case. Please try on the master branch and let us know.

**Comment by ipapapa** [comment]
@shailesh33 I think @mansoor-s talks that the dev branch. I doubt though that the latest commit is the cause of the issue. Some of the recent redefinition?

**Comment by shailesh33** [comment]
Hey I do not have a setup to test this out, can you refresh latest dev and try again. Thanks.

**Comment by mansoor-s** [comment]
I can try this again with the latest dev branch commit a bit later today. Will let you know how it goes.

**Comment by mansoor-s** [comment]
Sorry for the long delay. 
The master branch is building successfully, however, the dev branch is still failing with the following error:

`
Making all in src
make[2]: Entering directory `/home/vagrant/dynomite/src'
Making all in hashkit
make[3]: Entering directory `/home/vagrant/dynomite/src/hashkit'
gcc -DHAVE_CONFIG_H -I. -I../..  -I ../../src -I ../../contrib/murmur3  -Wall -Wshadow -Wpointer-arith -Winline -Wunused-function -Wunused-variable -Wunused-value -Wno-unused-parameter -Wno-unused-value -Wconversion -Wsign-compare -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wmissing-declarations -Werror=implicit-function-declaration -g -O2 -MT dyn_crc16.o -MD -MP -MF .deps/dyn_crc16.Tpo -c -o dyn_crc16.o dyn_crc16.c
In file included from ../../src/dyn_core.h:130,
                 from ../../src/dyn_token.h:7,
                 from dyn_crc16.c:23:
../../src/dyn_util.h:352: error: redefinition of typedef ‘msec_t’
../../src/dyn_types.h:3: note: previous declaration of ‘msec_t’ was here
../../src/dyn_util.h:353: error: redefinition of typedef ‘usec_t’
../../src/dyn_types.h:4: note: previous declaration of ‘usec_t’ was here
dyn_crc16.c:62: warning: no previous prototype for ‘hash_crc16’
dyn_crc16.c: In function ‘hash_crc16’:
dyn_crc16.c:68: warning: conversion to ‘uint32_t’ from ‘char’ may change the sign of the result
make[3]: *** [dyn_crc16.o] Error 1
make[3]: Leaving directory `/home/vagrant/dynomite/src/hashkit'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/vagrant/dynomite/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/vagrant/dynomite'
make: *** [all] Error 2
`

**Comment by shailesh33** [comment]
you are right there is a redefinition. Let me see how to resolve this. I have been moving code and refactoring a bit lately.

**Comment by diegopacheco** [comment]
@mansoor-s @ipapapa  @shailesh33 

I build Dynomite in Amazon Linux - I never had issues - Here is a simple example how to build it.
https://gist.github.com/diegopacheco/37eee1c48c3cdce17b1fdbd7b5f23319

Cheers,
Diego Pacheco

**Comment by ipapapa** [comment]
@mansoor-s  @flaviotorres  We haven't heard back from you regarding this question. At this time, we're marking this case as resolved. If you want to follow up let us know and we can either reopen the issue, or please file a new issue.
