### ISSUE TITLE
Build a sidekick application similar to Priam - Florida

### ISSUE THREAD

**Issue by timiblossom** [Netflix/dynomite#3]
This sidekick apps (Florida) will help Dynomite nodes to bootstrap, update security setting, join Eureka (or Discovery), and others similar to some of the Priam's features.

**Comment by keen99** [comment]
when? :)

**Comment by timiblossom** [comment]
We have it internally.  However, it has some hooks to our internal libraries that I don't have time to remove them yet.  If you are interested, I can upload to github and let you peak at it to see if you can help.

**Comment by keen99** [comment]
uploading it with some docu on expected usage and behavior - and a note that it wont compile yet - might be a good path to getting some help on it. :)   Maybe reopen this issue as a pointer to it as a WIP?

(I can take a look - and if it's useful enough, I might be able to steal some resources to help, though right now I'm in prototype mode to figure out how to even use dynomite. :)
