### ISSUE TITLE
Why My Performance(get/set) Test so big difference between dynomite and redis 

### ISSUE THREAD

**Issue by tulun0551** [Netflix/dynomite#306]
The test results are as follows:

root@dynomite2:~# redis-benchmark -h 172.16.1.65 -p 8102 -c 1 -n 10000 -t set
====== SET ======
  10000 requests completed in 2.24 seconds
  1 parallel clients
  3 bytes payload
  keep alive: 1

99.95% <= 1 milliseconds
100.00% <= 1 milliseconds
4468.28 requests per second

root@dynomite2:~# 
root@dynomite2:~# 
root@dynomite2:~# 
root@dynomite2:~# redis-benchmark -h 172.16.1.65 -p 8102 -c 1 -n 10000 -t get
====== GET ======
  10000 requests completed in 2.27 seconds
  1 parallel clients
  3 bytes payload
  keep alive: 1

100.00% <= 1 milliseconds
4411.12 requests per second

root@dynomite2:~# 
root@dynomite2:~# 
root@dynomite2:~# redis-benchmark -h 172.16.1.65 -p 6379 -c 1 -n 10000 -t set
====== SET ======
  10000 requests completed in 1.70 seconds
  1 parallel clients
  3 bytes payload
  keep alive: 1

99.95% <= 1 milliseconds
100.00% <= 1 milliseconds
5899.70 requests per second

root@dynomite2:~# redis-benchmark -h 172.16.1.65 -p 6379 -c 1 -n 10000 -t get
====== GET ======
  10000 requests completed in 1.70 seconds
  1 parallel clients
  3 bytes payload
  keep alive: 1

100.00% <= 1 milliseconds
5892.75 requests per second

For two VMs of openstack, one is for dynomite and redis, one is for redis-benchmark.
Using redis-benchmark to test performance of dynomite, why so big difference? thank you

access dynomite:    get:4411/s    set:4468/s
directly access redis:   get:5892/s    set:5899/s

**Comment by ipapapa** [comment]
I am not sure what is your underlying hardware (below OpenStack),  but there is a performance hit in a single node scenario when using Dynomite since it is a proxy layer above Redis. Dynomite is useful for horizontally scaling i.e. when you want to send more traffic than what a single node can handle. Dynomite can distribute the traffic across nodes. For more information: http://techblog.netflix.com/2016/01/dynomite-with-redis-on-aws-benchmarks_14.html

Another note: Redis is a CP (Consistency - Partition Tolerance) system, and Dynomite is an AP (Availability - Partition Tolerance) system.

**Comment by tulun0551** [comment]
every node has dynomite process and redis server, so every vm's performance would be affected?
In a single node scenario when using Dynomite, My performance test results of get and set decrease by 10%-40%(different key/value lengths). it is so big gap.

**Comment by shailesh33** [comment]
@tulun0551 This kind of performance gap might be expected. Remember that Dynomite is a seperate process there is a hop involved even if it means local host, there is parsing of data, copying, etc. You will really start seeing the advantage of Dynomite when you do multi node. By that it doesnt mean that it will be faster, it means that you will have much larger data in the cluster than a single redis node.

**Comment by ipapapa** [comment]
@tulun0551 check also your core affinity in case you are running Redis and Dynomite in the same core. You can take some ideas from the [core affinity script](https://github.com/Netflix/dynomite/blob/dev/bin/core_affinity.sh).

**Comment by tulun0551** [comment]
Thanks. I use 'taskset -c pid' command to set different CPU core binding, but still have no effect. @ipapapa

**Comment by tulun0551** [comment]
Thanks. you may be right. @shailesh33

**Comment by ipapapa** [comment]
@tulun0551 you get a performance benefit if you have high write OPS. In that case you need multiple Dynomite nodes compared to the vanilla Redis cluster which writes to a single master. Otherwise, @shailesh33 is right, there is always an overhead.

**Comment by ipapapa** [comment]
@tulun0551 closing the issue since your question has been answered. If you need more information let us know and we can reopen it.
