### ISSUE TITLE
why does data always set into one server?

### ISSUE THREAD

**Issue by JarvisZhu** [Netflix/dynomite#307]
conf/dynomite.yml：
dyn_o_mite:
  listen: 0.0.0.0:8102
  dyn_listen: 127.0.0.1:8101
  tokens: '101134286'
  servers:
  - 192.168.24.154:6379:2
  - 192.168.24.155:6379:1
  data_store: 0

Java code on other machine：
		Jedis client = new Jedis("192.168.24.154", 8102);
		for(int i = 0; i < 1000; i++) {
			client.set(UUID.randomUUID().toString(), UUID.randomUUID().toString());
		}
		client.disconnect();

the result is all the data are set into redis on 192.168.24.155, and the redis on 192.168.24.154 there is no data.

tks

**Comment by ipapapa** [comment]
Dynomite is not meant to be used with multiple Redis backends i.e. multiple `servers`. 
Dynomite needs to be installed in every node with Redis so that it does the replication. Hence in your conf/dynomite.yml you are missing the `dyn_seeds`. See this as an example: [a_dc1.yml](https://github.com/Netflix/dynomite/blob/dev/conf/a_dc1.yml).

Checkout a list of exemplar configuration files: https://github.com/Netflix/dynomite/tree/dev/conf

**Comment by JarvisZhu** [comment]
Thank you very much, I did more test, well, it's perfect. but I found that when there are multi nodes under one rack, the keys are not balance between these nodes. 
For example two nodes, when I set into 2000 keys, maybe one node has 1996 keys, and the other node just has 4 keys. why? 
How one key be set into which node in one rack ?

**Comment by ipapapa** [comment]
Since you have some keys received by the node with the fewer number of keys, it seems that data are being sent to that node, so no security issue here. The reason, that the nodes are imbalanced is potentially a misconfiguration of the token range. Did you use the above script to generate the .yml? Can you please share your latest .yml file?

**Comment by JarvisZhu** [comment]
**192.168.24.154：**
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  listen: 0.0.0.0:8102
  dyn_listen: 0.0.0.0:8101
  tokens: '101134286'
  dyn_seeds:
  - 192.168.24.155:8101:rack1:dc2:101134286
  - 192.168.24.135:8101:rack2:dc2:101134286
  - 192.168.24.136:8101:rack2:dc2:123456789
  servers:
  - 192.168.24.154:7000:1
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0

**192.168.24.155：**
dyn_o_mite:
  datacenter: dc2
  rack: rack1
  listen: 0.0.0.0:8102
  dyn_listen: 0.0.0.0:8101
  tokens: '101134286'
  dyn_seeds:
  - 192.168.24.154:8101:rack1:dc1:101134286
  - 192.168.24.135:8101:rack2:dc2:101134286
  - 192.168.24.136:8101:rack2:dc2:123456789
  servers:
  - 192.168.24.155:7000:1
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0

**192.168.24.135：**
dyn_o_mite:
  datacenter: dc2
  rack: rack2
  listen: 0.0.0.0:8102
  dyn_listen: 0.0.0.0:8101
  tokens: '101134286'
  dyn_seeds:
  - 192.168.24.154:8101:rack1:dc1:101134286
  - 192.168.24.155:8101:rack1:dc2:101134286
  - 192.168.24.136:8101:rack2:dc2:123456789
  servers:
  - 192.168.24.135:7000:1
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0

**192.168.24.136：**
dyn_o_mite:
  datacenter: dc2
  rack: rack2
  listen: 0.0.0.0:8102
  dyn_listen: 0.0.0.0:8101
  tokens: '123456789'
  dyn_seeds:
  - 192.168.24.154:8101:rack1:dc1:101134286
  - 192.168.24.155:8101:rack1:dc2:101134286
  - 192.168.24.135:8101:rack2:dc2:101134286
  servers:
  - 192.168.24.136:7000:1
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0

each of 155 and 156 has all the data, this is no problem.
each of 135 and 136 has part of data, but it's not balance, maybe 135 has all the data, and 136 has no data.
I installed dynomite on each of the four machine, and "101134286" is the default token value on every mechine, I did not got token "123456789" by the script, I just write it by myself. Is this a problem? 
before my test start, I flushdb of all the four redis.

**Comment by ipapapa** [comment]
I think you have an imbalanced token ring. 

* 192.168.24.154 belongs to dc1/rack1 with token 101134286
* 192.168.24.155 belong to dc2/rack1 with token 101134286
* 192.168.24.136 and 135 belong to dc2/rack2. They have different tokens: 101134286 and 123456789
So you have 1 node in dc1 and 3 nodes in dc2. 

Try using some balanced combination like:
* 1 in rack1/dc1, 1 in rack2/dc1, 1 in rack1/dc2, 1 in rack2/dc2 with a single token in all nodes
* 2 in rack1/dc1 and 2 in rack1/dc2 with two tokens per rack.
* 1 in rack1/dc1, 1 rack1/dc2, 1 rack2/dc2, 1 rack3/dc2 with a single token in all nodes.

**Comment by JarvisZhu** [comment]
thanks you very much, I did all the test of these three.
in fact my aim is this:
before, I have just one redis, there are too many data in this redis, and now, I have two redis, so I want to storage data into this two redis as possible as balance, can dynomite do this ?

**Comment by ipapapa** [comment]
Yes, Dynomite will use a hashing algorithm on the key to evenly distribute the data across nodes.

**Comment by JarvisZhu** [comment]
eh, could you please share me the .yml?

**Comment by ipapapa** [comment]
I am assuming you need the second option:
* 2 in rack1/dc1 and 2 in rack1/dc2 with two tokens per rack.

so based on your above example:
* 192.168.24.154:8101:rack1:dc1:101134286
* 192.168.24.155:8101:rack1:dc1:123456789

* 192.168.24.135:8101:rack1:dc2:101134286
* 192.168.24.136:8101:rack1:dc2:123456789 

You can also use the python script to calculate the tokens properly.

**Comment by JarvisZhu** [comment]
I use this command "python generate_yamls.py 192.168.24.154:rack1 192.168.24.155:rack1 192.168.24.135:rack1 192.168.24.136:rack1" to generate the four .yml file, just use the four token, then use Java code to set 1000 keys to dynomite, then I got the results: 154 has 574, 155 has 426, 135 has 542, 136 has 458.

Thank you very much!

**Comment by ipapapa** [comment]
Great!
