### ISSUE TITLE
using dynomiteDB as PHP session handler

### ISSUE THREAD

**Issue by dev-yohan** [Netflix/dynomite#309]
Hi, we are using dynomite to store php sessions in redis(with phpRedis extension) using two datacenters with 2 racks each one, actually we are using a load balancer as session host:

```
session.save_handler = redis
session.save_path = "tcp://load_balancer_host:6379?timeout=2.5"
```
Currently  we have issues when a rack node goes down because the load balancer seems to lost the connection to the healthy nodes, so I think that maybe is a better idea to remove the load balancer and set some of the nodes in the session.save_path, something like this:

```
session.save_handler = redis
session.save_path = "tcp://rack1_node1_host:6379?timeout=2.5,tcp://rack2_node1_host:6379?timeout=2.5....."
```

What do you think? maybe this is not a good practice in order to maintain the single points of failure at the minimun

regards

**Comment by ipapapa** [comment]
@dev-yohan How many nodes per Rack do you have?

**Comment by dev-yohan** [comment]
Hi, we have 2 racks with 4 nodes per rack, I think that the issues is related to the maxclients handled by redis, as you see in the attached image, when we raised a 100k connections in average the cluster goes down: 

![dynomite-connections](https://cloud.githubusercontent.com/assets/3068138/17295782/426b7e60-57d4-11e6-8dc5-873662381abe.jpg)

So we modify the ulimit and the maxclients in redis.conf to allow more connections, we are worried about if that changes are enough to solve the issue, as you mention maybe the load balancer fails handling a lot of connections and does not jump to a healthy node.

**Comment by ipapapa** [comment]
@dev-yohan if the client is connecting to Dynomite then Dynomite establishes a single connection to Redis.

**Comment by ipapapa** [comment]
In our past performance tests, we found that a single Dynomite node could support 80-100K connections. In that case, we scaled horizontally in order for us to handle a higher number of connections. The load balancing was happening in the client side by [Dyno](https://github.com/Netflix/dyno).

Currently, you may be hitting a single node, which acts as the [coordinator node](https://github.com/Netflix/dynomite/wiki/Replication). Hence, if you want to scale to higher number of connections, you probably need some load balancer.

**Comment by ipapapa** [comment]
We haven't heard back from you regarding this question. At this time, we're marking this case as resolved. If you want to follow up let us know and we can either reopen the issue, or please file a new issue.
