### ISSUE TITLE
Sync/Replay question

### ISSUE THREAD

**Issue by deejanu** [Netflix/dynomite#311]
We have been testing different scenarios with following Dynomite setup:

DC1 - Rack1:Node1; Rack2:Node1;
DC2 - Rack1:Node1;

Replication seems to be working fine across Racks and DCs as long as Nodes are up. Then we take one Node down and publish to nodes that are still up. When we bring Node up that Node is not in sync with other Nodes. It is not aware of data that was published while it was down. This would introduce inconsistent data situation during the maintenance when Nodes go up and down. Is there anything else that needs to be configured to force the sync?

**Comment by ipapapa** [comment]
* When a new node joins the ring, we warm up a node with data from peer servers and hence there is no or very less entropy in the cluster. For more information about cold bootstrapping you can check the following [wiki page of Dynomite-manager](https://github.com/Netflix/dynomite-manager/wiki/Cold-Bootstraping). 
* In a temporary event that a node is not reachable, there is entropy in the cluster. For the latter, we are working on the reconciliation feature (you are welcome to assist).

**Comment by ipapapa** [comment]
We haven't heard back from you regarding this question. At this time, we're marking this case as Resolved. If you want to follow up let us know and we can either reopen the issue, or please file a new issue.
