### ISSUE TITLE
Is there a list of all the redis commands supported by dynomite?

### ISSUE THREAD

**Issue by colmex** [Netflix/dynomite#312]
I was looking through http://www.dynomitedb.com/docs/key-value-api/v0.5.8/introduction/ and under clients it says, `DynomiteDB supports the Redis protocol and the majority of Redis commands.` I was just wondering what are the redis commands that dynomite doesn't support?

**Comment by ipapapa** [comment]
https://github.com/Netflix/dynomite/blob/dev/notes/redis.md

**Comment by ipapapa** [comment]
Let us know if your question has been answered. Thanks!

**Comment by colmex** [comment]
awesome! That's exactly what I needed. Thanks!
