### ISSUE TITLE
Integrating Dynomite with SolrCloud

### ISSUE THREAD

**Issue by nitingithub** [Netflix/dynomite#315]
Hi, 

Will you guys entertain the idea of integration Dynomite with SolrCloud? I have a cross DC replication library for solr (https://github.com/bloomreach/solrcloud-haft) and wondering if adding it to dynomite makes sense/entertained?

Thanks,
Nitin

**Comment by shailesh33** [comment]
Can you please elaborate Nitin?

**Comment by nitingithub** [comment]
Dynomite mentions that the ultimate goal is to be able to implement high availability and cross-datacenter replication on storage engines that do not inherently provide that functionality.

Is this only restricting to k-v storage mechanims or also reverse index platforms like solr/elastic search etc?

**Comment by ipapapa** [comment]
@nitingithub Dynomite already is supposed to offer high availability and cross-datacenter replication. I am missing how the replication library for solr will help here.

**Comment by nitingithub** [comment]
Sorry for the confusion folks. Let me clarify. When i read through dynomite, my understanding was that it supports ha and cross dc replication for redis and memcached. There are other platforms like solr/elastic search which do not come with cross dc replication out of the box. I was wondering if there are any plans to make dynomite work with such platforms as well.

**Comment by ipapapa** [comment]
We do not have the bandwidth to look on all platforms, but we are definitely open for contributions. The best way to integrate the protocol is to look in the [proto folder](https://github.com/Netflix/dynomite/tree/dev/src/proto). Are you going to use the REST API or a binary API? Is there a spec for the ES or Solr protocol that you can leverage?

**Comment by nitingithub** [comment]
I was planning on the rest api for replication. There are few different replication commands that help move the data around. There are some api specs for replication (from a rest api standpoint). How do you recommend to get started on this?

**Comment by ipapapa** [comment]
I believe you need to develop a REST parser in the proto folder as I mentioned above. On another note, I think ES supports cross-DC replication leveraging the binary protocol (but my understanding is that it is not recommended). I am not sure about Solr.

**Comment by ipapapa** [comment]
We haven't heard back from you regarding this question. At this time, we're marking this question as Resolved. If you want to follow up with further questions on the design of the REST endpoint let us know and we can either reopen the issue, or please create a new issue.
