### ISSUE TITLE
Dynomite with Redis 3

### ISSUE THREAD

**Issue by raffian** [Netflix/dynomite#323]
Apologies if this question was previously asked,

If we use Dynomite with redis 3, is it safe to assume redis cluster and sentinel are not required since Dynomite leverages Twemproxy for routing/partitioning, and given Dynomite's peer-to-peer nature, no need for redis sentinel?

**Comment by ipapapa** [comment]
Correct, you do not need Redis Sentinel.

**Comment by raffian** [comment]
That's great news, last question before you can close, if we use a single DNS name to round-robin across all Dynomite instances in a single DC, the Dyno client needs only the DNS name for initial connection, not a list of all hosts, correct? I'm assuming Dyno client, once connected, regularly queries the cluster for active peers to achieve fast fail-over should its connection fail.

**Comment by ipapapa** [comment]
Dyno opens multiple connections with all nodes in the same DC. This is done in order to avoid creating a connection during the fail-over. Dyno gets information about alive nodes from a  Discovery service (including public ip, private ip and hostname). Dyno queries [dynomite-manager](https://github.com/Netflix/dynomite-manager) or other sidecar for [cluster_describe](https://github.com/Netflix/dynomite-manager/wiki/REST-API) every 30 seconds to find out if there are changes in the topology.

**Comment by raffian** [comment]
Thanks again for the info,

**Comment by ipapapa** [comment]
No problem, feel free to ask more questions if you have any more.

**Comment by abhinav0101** [comment]
hi @ipapapa

we are not using any discovery service as yet. this is how I set up dyno.

public void setUpDyno() {

        try {
            final List<Host> hosts = new ArrayList<Host>();
            hosts.add(new HostBuilder().setHostname("box2")
                    .setIpAddress("127.0.0.1")
                    .setPort(8104)
                    .setRack("rack2")
                    .setDatacenter("dc").setStatus(Host.Status.Up).createHost());
            hosts.add(new HostBuilder().setHostname("box")
                    .setIpAddress("127.0.0.1")
                    .setPort(8102)
                    .setRack("rack")
                    .setDatacenter("dc").setStatus(Host.Status.Up).createHost());
            hosts.add(new HostBuilder().setHostname("box3")
                    .setIpAddress("127.0.0.1")
                    .setPort(8106)
                    .setRack("rack3")
                    .setDatacenter("dc").setStatus(Host.Status.Up).createHost());
            hosts.add(new HostBuilder().setHostname("box4")
                    .setIpAddress("127.0.0.1")
                    .setPort(8108)
                    .setRack("rack4")
                    .setDatacenter("dc").setStatus(Host.Status.Up).createHost());

            final HostSupplier customHostSupplier = new HostSupplier() {

                @Override
                public List<Host> getHosts() {
                    return hosts;
                }
            };

            this.hostSuperSupplier = customHostSupplier;

            log.info("roxxx {}", new ObjectMapper().writeValueAsString(hostSuperSupplier));

            this.dynoClient = new DynoJedisClient.Builder()
                    .withApplicationName("BEATLE_ON_MY_KNEE")
                    .withDynomiteClusterName("DYNOMITE_CLUSTER_NAME")
                    .withHostSupplier(customHostSupplier)
                    .withCPConfig(getDynoConfig())
                    .withTokenMapSupplier(testTokenMapSupplier)
                    .build();

            dynoClient.set("kuku", "bandar");

        } catch (Exception e ) {
            log.error("Error while initialising dyno client", e);
        }
    }


    final String json = "[\n" +
            "{\n" +
            "  \"token\": \"0\",\n" +
            "  \"hostname\": \"box2\",\n" +
            "  \"zone\": \"rack2\",\n" +
            "  \"port\": \"8104\",\n" +
            "  \"dc\": \"dc\",\n" +
            "  \"ip\": \"127.0.0.1\"\n" +
            "},\n" +
            "{\n" +
            "  \"token\": \"0\",\n" +
            "  \"hostname\": \"box\",\n" +
            "  \"zone\": \"rack\",\n" +
            "  \"port\": \"8102\",\n" +
            "  \"dc\": \"dc\",\n" +
            "  \"ip\": \"127.0.0.1\"\n" +
            "},\n" +
            "{\n" +
            "  \"token\": \"0\",\n" +
            "  \"hostname\": \"box3\",\n" +
            "  \"zone\": \"rack3\",\n" +
            "  \"port\": \"8106\",\n" +
            "  \"dc\": \"dc\",\n" +
            "  \"ip\": \"127.0.0.1\"\n" +
            "},\n" +
            "{\n" +
            "  \"token\": \"0\",\n" +
            "  \"hostname\": \"box4\",\n" +
            "  \"zone\": \"rack4\",\n" +
            "  \"port\": \"8108\",\n" +
            "  \"dc\": \"dc\",\n" +
            "  \"ip\": \"127.0.0.1\"\n" +
            "}]" ;

    private TokenMapSupplier testTokenMapSupplier = new AbstractTokenMapSupplier() {

        @Override
        public String getTopologyJsonPayload(Set<Host> set) {
            return json;
        }

        @Override
        public String getTopologyJsonPayload(String hostname) {
            return json;
        }
    };


    @Override
    public void contextDestroyed(ServletContextEvent servletContextEvent) {
        DynoJedisClient dynoClient = (DynoJedisClient) servletContext.getAttribute(DYNO_CLIENT);
        if (dynoClient != null) dynoClient.stopClient();
        servletContext.removeAttribute(DYNO_CLIENT);
    }

    private ConnectionPoolConfigurationImpl getDynoConfig() {
        ConnectionPoolConfigurationImpl config = new ConnectionPoolConfigurationImpl("config")
                .setMaxConnsPerHost(150)
                .setMaxFailoverCount(3)
                .withHostSupplier(hostSuperSupplier)
                .setLoadBalancingStrategy(ConnectionPoolConfiguration.LoadBalancingStrategy.TokenAware)
                .setMaxTimeoutWhenExhausted((int) Duration.ofSeconds(10).toMillis())
                .setSocketTimeout(12000);
        return config;
    }
    
This configuration does not work in case of failover. Please help!

**Comment by ipapapa** [comment]
What happens if there is a failover? How is the topology being updated? There has to be some ERROR or log information. It has been a few years since I touched this code. @smukil may remember something or someone else.

**Comment by abhinav0101** [comment]
@ipapapa, @smukil I resolved the issue. Basically I wasnt updating Host Status in the client side when a host was going down.

What I understood from the netflix dyno code is the getHosts() function is called before every read and write. So, everytime getHosts is called, it has to update the Status of hosts as UP or Down. Currently, I am pinging the redis instances with Jedis  every 500 ms and updating their status, Since, I dodnt wanna use Dynomite Manager for Health Discovery. I have got 2 ques. for you:-

1.) Does Dyno client have a feature similar to Ping in Jedis ? if it has we could use it instead for updating host healths.

2.) Can you give me a little info about .setLocalRack() and .setLocalDataCenter() configs in ConnectionPool. What does "Local Rack" and "Local DataCenter" mean when there can be many datacenters and racks ?
