### ISSUE TITLE
Clarify the difference between DC_QUORUM and DC_SAFE_QUORUM

### ISSUE THREAD

**Issue by danielcompton** [Netflix/dynomite#329]
In the docs for [consistency](https://github.com/Netflix/dynomite/wiki/Consistency), I don't quite understand the difference between DC_QUORUM and DC_SAFE_QUORUM.

> DC_QUORUM: Reads and writes are propagated synchronously to quorum number of nodes in the local data center and asynchronously to the rest. The DC_QUORUM configuration writes to the number of nodes that make up a quorum. A quorum is calculated, and then rounded down to a whole number. If all responses are different the local on is returned.
> 
> DC_SAFE_QUORUM: Similarly to DC_QUORUM, but the operation succeeds only if the read/write succeeded on a quorum number of nodes. If the quorum has not been achieved then an error response is generated by Dynamite.

A few notes on my confusion:

> If all responses are different the local on is returned.

Should this be "the local one is returned"? It would be good to specify what "one" is referring to. I'm guessing it's the response to the read/write request?

> DC_SAFE_QUORUM: Similarly to DC_QUORUM, but the operation succeeds only if the read/write succeeded on a quorum number of nodes.

When I read this, it implies that under `DC_QUORUM`, writes/reads are attempted against a quorum, but all but one could fail and that would count as a successful quorum write/read? Is that correct?

Would you be able to clarify what the differences are between these two settings, and their failure scenarios? My apologies if I've misunderstood this.

**Comment by shailesh33** [comment]
@danielcompton Your question is very valid. The difference between the two really comes in picture when the query succeeded on quorum nodes but the responses were not the same. If you are very sensitive to reads and writes getting propagated well, use SAFE_QUORUM option. DC_QUORUM gives looser guarantees on quorum in case data mismatch. SAFE_QUORUM will give you error on which you can retry or attempt to repair the data yourself. (straight forward for basic key value). But they both are sensitive to errors. 

We might actually merge them both into one eventually.

**Comment by danielcompton** [comment]
Thanks for the reply. This is my current understanding:

### Reads under `DC_QUORUM`

* Reads are sent to a quorum of nodes
* All of the nodes must respond with a value for a read to be successful. If less than a quorum responds, then the read fails.
* If the values differ between nodes then the local read is returned as authoritative (what happens if there is no local read? Is it possible for the client request routing to pick the wrong node to query on, and therefore have no local query?)

### Reads under `DC_SAFE_QUORUM`

* Same conditions as `DC_QUORUM`, but if the values differ between nodes then an error is returned.

I'm not clear on how writes would differ between the two quorum consistency types, could you clarify this?

**Comment by shailesh33** [comment]
If the writes are done with DC_ONE and reads are done with any of the two quorum types, the values that are read may differ. This is typically done in situations where the application is very write heavy but sensitive to data inconsistency during reads.
Does that answer your question?

**Comment by danielcompton** [comment]
Not quite, what I'm wondering is whether there is any possible difference in behaviour for writes under `DC_SAFE_QUORUM` and `DC_QUORUM`?

**Comment by shailesh33** [comment]
It has the same difference for writes as for reads. In redis writes do return different values for example Expire. I think for most cases DC_SAFE_QUORUM is correct. Like I said before, we might combine them both into just one option. Please feel free to reach out if this still doesnt answer your questions. 
We also use gitter for real time chats if you want further conversation

**Comment by shailesh33** [comment]
Has this been solved? Closing the issue. Please reopen if you still have questions.
