### ISSUE TITLE
Using Dynomite with Redigo (Redis Golang Client)

### ISSUE THREAD

**Issue by prakashsh** [Netflix/dynomite#331]
Hi,
    I am trying to use dynomite with redis golang client [Redigo] (https://github.com/garyburd/redigo) .

I use a single node cluster. I used the conf/redis_single.yml file.
Dynomite/Redis server is running on Ubuntu 14.04 
Client  code is on Mac OS X 10.11.5.

I am able to connect to dynomite, but i get an error (details given below) while trying to write to Redis with SET command. Here's the code I am using . (I use Vitess Go [Pool](https://github.com/youtube/vitess/tree/master/go/pools)  for creating a Redis Connection Pool)

```
func PlayWithDynomite(strIPAddr string) {

	pRedisPool, err := GetPool("dynomite_redis", strIPAddr, "22222")
	if err != nil {
		panic(err)
	}

	pConn, err := pRedisPool.GetConnection()
	if err != nil {
		panic(err)
	}
	defer pRedisPool.PutConnection(pConn)

	fmt.Println("Connected To dynomite/redis") // This print happens. Successfully connected.

	R.SET(pConn, "a", "b") //This command fails.

}
```

I get the following error.

> panic: redigo: bad response line terminator (possible server error or unsupported concurrent read by application)

 **But,When I try to connect to Redis instance directly (instead of connecting to dynomite), the client connects successfully and the write succeeds**.

I tried to dig a bit in to the redigo client and The call stack of the point where the error was thrown is :

> github.com/garyburd/redigo/redis.(*conn).readLine(0xc820086e60, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/Users/test/try/src/github.com/garyburd/redigo/redis/conn.go:350 +0x645
> github.com/garyburd/redigo/redis.(*conn).readReply(0xc820086e60, 0x0, 0x0, 0x0, 0x0)
> 	/Users/test/try/src/github.com/garyburd/redigo/redis/conn.go:422 +0x57
> github.com/garyburd/redigo/redis.(*conn).Do(0xc820086e60, 0x44bc88, 0x3, 0xc820109200, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
> 	/Users/test/try/src/github.com/garyburd/redigo/redis/conn.go:570 +0x6b2

I just added a panic before line 350 in redigo/redis/conn.go to produce the call stack.

Has anyone here tried using dynomite with Redigo ?
Can you please help me fix this problem ?

Thank you,
Prakash

**Comment by ipapapa** [comment]
Are you running Redis or Dynomite in port `22222`? It seems you are establishing the connection pool to that port:
`    pRedisPool, err := GetPool("dynomite_redis", strIPAddr, "22222")`

Based on the YAML you are running 22122 is your Redis port, and 8102 is your Dynomite port. 22222 is the REST port for Dynomite. So your client may be connecting but no Redis operations will succeed.

**Comment by prakashsh** [comment]
Thanks a lot for your help @ipapapa .

I am now able to write to redis via dynomite.

I also had to change the redis_single.yml file

dyn_listen has to be changed from 127.0.0.1:8102 to 0.0.0.0:8102.


Here's my current config file.

`dyn_o_mite:
  dyn_listen: 0.0.0.0:8101
  data_store: 0
  listen: 0.0.0.0:8102
  dyn_seed_provider: simple_provider
  servers:
  - 127.0.0.1:22122:1
  tokens: 437425602`


Thank you,
Prakash
