### ISSUE TITLE
Compile error under OS X Yosemite 

### ISSUE THREAD

**Issue by KowalczykBartek** [Netflix/dynomite#332]
I tried to build dynomite from the master branch and : 

Running `gcc-4.6 (Homebrew gcc46 4.6.4) 4.6.4`   
Your Travis use `4.6.3`

Build output:
```
Making all in event
gcc -DHAVE_CONFIG_H -I. -I../..  -I ../../src  -Wall -Wshadow -Wpointer-arith -Winline -Wunused-function -Wunused-variable -Wunused-value -Wno-unused-parameter -Wno-unused-value -Wconversion -Wsign-compare -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wmissing-declarations -Werror=implicit-function-declaration -g -O2 -MT dyn_epoll.o -MD -MP -MF .deps/dyn_epoll.Tpo -c -o dyn_epoll.o dyn_epoll.c
mv -f .deps/dyn_epoll.Tpo .deps/dyn_epoll.Po
gcc -DHAVE_CONFIG_H -I. -I../..  -I ../../src  -Wall -Wshadow -Wpointer-arith -Winline -Wunused-function -Wunused-variable -Wunused-value -Wno-unused-parameter -Wno-unused-value -Wconversion -Wsign-compare -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wmissing-declarations -Werror=implicit-function-declaration -g -O2 -MT dyn_kqueue.o -MD -MP -MF .deps/dyn_kqueue.Tpo -c -o dyn_kqueue.o dyn_kqueue.c
dyn_kqueue.c:401:40: warning: implicit conversion loses integer precision: 'intptr_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
                          strerror(ev->data));
                          ~~~~~~~~ ~~~~^~~~
../../src/dyn_log.h:103:41: note: expanded from macro 'log_error'
        _log(__FUNCTION__, __LINE__, 0, __VA_ARGS__);                           \
                                        ^
dyn_kqueue.c:472:12: error: use of undeclared identifier 'st'
        cb(st, &nreturned);
           ^
dyn_kqueue.c:467:40: warning: implicit conversion loses integer precision: 'intptr_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
                          strerror(ev->data));
                          ~~~~~~~~ ~~~~^~~~
../../src/dyn_log.h:103:41: note: expanded from macro 'log_error'
        _log(__FUNCTION__, __LINE__, 0, __VA_ARGS__);                           \
                                        ^
2 warnings and 1 error generated.
make[3]: *** [dyn_kqueue.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1

```

Thanks in advance :)

**Comment by KowalczykBartek** [comment]
Hi, 

after merge I am struggling with 

```
gcc -DHAVE_CONFIG_H -I. -I../..  -I ../../src  -Wall -Wshadow -Wpointer-arith -Winline -Wunused-function -Wunused-variable -Wunused-value -Wno-unused-parameter -Wno-unused-value -Wconversion -Wsign-compare -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wmissing-declarations -Wimplicit-function-declaration -g -O2 -MT dyn_entropy_rcv.o -MD -MP -MF .deps/dyn_entropy_rcv.Tpo -c -o dyn_entropy_rcv.o dyn_entropy_rcv.c
dyn_entropy_rcv.c:32:10: fatal error: 'sys/sendfile.h' file not found
#include <sys/sendfile.h>
```

`<sys/sendfile.h>` seems to be linux specific, isn't it ??

http://stackoverflow.com/questions/8252698/sys-sendfile-h-not-found-gcc

thank you for your effort ! 
Cheers.

**Comment by KowalczykBartek** [comment]
Hi, 

after merge I am struggling with 
```

dyn_crypto.c:214:14: error: implicit declaration of function 'fmemopen' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    stream = fmemopen(buffer, encodedSize+1, "w");

```

seems that it is more common https://github.com/btrask/stronglink/issues/102

thank you for your effort ! 
Cheers.

**Comment by shailesh33** [comment]
Hi Can you give me the set of commands to set up the environment to compile on mac? homebrew and stuff? One of us will try to compile it locally instead of doing back and forth

**Comment by KowalczykBartek** [comment]
hmm, honestly I setup only gcc 4.9

`brew install gcc49`

then

`alias gcc='/usr/local/bin/gcc-4.9'`
`export CC=/usr/local/bin/gcc-4.9`

It is everything that I changed to be up-to date with Travis setup.

If you want to know more just ask, willingly answer.

**Comment by ipapapa** [comment]
@KowalczykBartek  doesn't your issue get solved by https://github.com/btrask/stronglink/commit/b8577d614d3b7673e95c3a69b78ddfa9929dbd3d

@shailesh33 the packages needed are `brew install cmake autoconf libtool gcc automake openssl'

**Comment by KowalczykBartek** [comment]
Ok, so, as far I made successful `make` , but I had to do : 

- according to @ipapapa hint I added stronglink were required (under **src**/ directory ) and I added required include `#import "fmemopen.h"`
- I had to remove `#include<sys/sendfile.h>` from `dyn_entropy_rcv.c` `dyn_entropy_snd.c` and `dyn_entropy_util.c` (reference : http://stackoverflow.com/questions/8252698/sys-sendfile-h-not-found-gcc)

- I had to remove -`rdynamic` option  (reference : http://stackoverflow.com/questions/29534519/why-gcc-doesnt-recognize-rdynamic-option)

Thanks for your amazing work and hints !

**Comment by KowalczykBartek** [comment]
Thanks guy for your amazing work and blazing fast support ! 

Cheers !
