### ISSUE TITLE
How to handle data isolation for different apps that access Dynomite

### ISSUE THREAD

**Issue by mantrala** [Netflix/dynomite#340]
Hello!

I'm trying out dynomite with redis currently and it's performing pretty well to what we expect.

- How does Netflix currently handle data isolation for different apps accessing dynomite and redis? Do they all write to the same redis server? If yes, is the isolation done through namespacing keys?

We have multiple apps that need to access this cache, so I was thinking of standing a separate redis instance (different ports) for every app. Is this the right way to do this? Also, I wanted to use the AUTH command but it's not yet supported by Dynomite (https://github.com/Netflix/dynomite/issues/46) so different apps cannot step in to each other.

Any pointers @ipapapa ?

Thanks!

**Comment by ipapapa** [comment]
@mantrala There are a number of use cases. 
* If the apps want to use the same data, then a single Dynomite cluster (in one or more datacenters) would suffice;
* if the data are not correlated, then each app can use its own cluster (limits the responsibility, makes it easier to debug ); 
* or if the traffic is low and the data are experimental they can use a multi-tenant cluster. In that case, you can use namespacing.

As you can see there are different options based on what fits your needs. In fact we are not putting multiple Redis underneath Dynomite, we rather give a separate cluster. This provides isolation for debugging etc.

`AUTH` command is not supported yet. It can be implemented in Dynomite if you are interested. Actually, the code is already there in Redis to port it in Dynomite.

**Comment by ipapapa** [comment]
Closing this as there is no further follow up. Please feel free to open a new issue if you have any additional questions, or follow up on this one and we can reopen it.
