### ISSUE TITLE
Can't connect to dynomite client port externally

### ISSUE THREAD

**Issue by caramcc** [Netflix/dynomite#341]
I have an instance of dynomite running inside a VM on my local machine with the following options: `src/dynomite -c conf/redis_single.yml -d -v 6 -m 512 -M 1000000 -o debug.log` and using an unmodified version of the provided single-node redis configuration. I'm using the latest version of the master branch.

I'm able to connect to Dynomite through the client port on the VM:
```
vm:~$ redis-cli -p 8102
127.0.0.1:8102> ping
PONG
```

but when I try to access it externally (i.e. from my local machine) I get connection refused:
```
local:~$ redis-cli -h vm -p 8102
Could not connect to Redis at vm:8102: Connection refused
Could not connect to Redis at vm:8102: Connection refused
not connected> 
```

However I am able to connect to redis on the vm externally:
```
local:~$ redis-cli -h vm -p 22122
vm:22122> ping
PONG
```

And am also able to access the dynomite admin port externally (`curl vm:22222` returns "OK", as expected).

If it helps, I'm using the latest version of redis as well (3.2.3) with protected-mode disabled (allowing redis to be accessed externally) and running with --port=22122.

Am I missing something? I should be able to connect to redis through dynomite's client port from the client side, right?

**Comment by ipapapa** [comment]
Try to `telnet vm 8102` and see if the port is open or not.

**Comment by caramcc** [comment]
It isn't:

```
local:~$ telnet vm 8102
Trying 172.16.8.4...
telnet: connect to address 172.16.8.4: Connection refused
telnet: Unable to connect to remote host
```

**Comment by ipapapa** [comment]
Well, if `telnet localhost 8102` works fine from inside the VM, if I am not mistaken, it sounds an access issue on port 8102 from outside the VM.

**Comment by caramcc** [comment]
It does work from within the VM. Do you know why the admin port would be accessible while the dynomite client port 8102 (and the dynomite peer port, 8101) wouldn't be? 

I've tried connecting redis-cli to every open port on the VM to see if the dynomite client port was remapped, but the only one I am able to connect to is the redis port (22122). The five open ports that I'm able to discover on the vm by running `nmap -p- vm` are just ssh, rpcbind, rpc.statd, then the redis port 22122 and the dynomite admin port 22222. 8101 and 8102 are missing.

**Comment by caramcc** [comment]
I figured it out: the default conf/redis_single.yml (which I was using) designated 127.0.0.1 for listen/dyn_listen so those two ports weren't being exposed to the network. The admin/stats port was exposed because it defaults to 0.0.0.0, and changing listen/dyn_listen to 0.0.0.0 in my configuration file resolved my issue.
