### ISSUE TITLE
Token Management and Horizontal Scaling

### ISSUE THREAD

**Issue by balajivenki** [Netflix/dynomite#342]
Hi Dynomite Team,

I have been evaluating dynomite + redis for our caching needs and we are seriously considering using this in prod. However the token management is still not completely clear or documented. Is this similar to cassandra token range? If so the generate_yamls.py gives a random 10 digit number as token for each node. Its not clear how token value should we use for any node. 

Right now my setup is like two racks in the same datacenter and 3 modes per rack.

When I use the script the token range e.g comes as 

node1: 3001831894
node2: 1890818316
node3: 1931033720

And its clear that the token is not equally distributed. Is that fine? Whats the requirement here? Whats the max token range? Is it 4294967295?

So when we manually setup for 3 modes should we equally split the range? 

Also a very important feature and it is missing documentation too is, how can we scale later? How can we add a new node in a rack and what will be that token range and how does dynomite handle it?

Please share more details or documentations if any. This is one of the thing blocking us moving forward with the PROD plan.

One another thing is that is it mandatory to dynomite-manager? What if we go only with dynomite + redis. The reason is we do not use Eureka for host supplier or discovery and looks like dynomite-manager is tightly coupled with it plus it has cassandra dependency too.

Any help is greatly appreciated.

**Comment by ipapapa** [comment]
@balajivenki Please find the documentation for token management in the following [wiki page](https://github.com/Netflix/dynomite-manager/wiki/Token-Management).

- The token management is the exactly same as in the Cassandra case. We use the same methodology. The only minor difference is that each Dynomite node per AZ has each own token range. 
- You need to equally split the range.
- Scale up and scale down by adding nodes is not automatically supported. This has been by far the most requested feature :) but internally we have delayed it by (a) adding the [dual write functionality](https://github.com/Netflix/dyno/wiki/Dual-Write-Functionality) on the client to a bigger shadow cluster; (b) vertically scaling in case of more data (r3.2xlarge --> r3.4xlarge --> r3.8xlarge).
- Dynomite-manager is an orchestration system. You do not need to use. The only missing feature is the [warm up](https://github.com/Netflix/dynomite-manager/wiki/Cold-Bootstraping) but you can implement that easily.

**Comment by balajivenki** [comment]
Thanks for your reply @ipapapa . Just to reiterate, 4294967295 is the max of the token and the distribution is similar to cassandra where the token of the node defines the max of token a node can have. In which case generate_yamls.py needs to be modified(I will see if I can change and contribute back) right now it gives a random number between 0-4294967295.

For the horizontal scaling I think we can read the keys from the nodes and rewrite them again using dynomite. Thats one way.

**Comment by ipapapa** [comment]
Correct, but for the token differences between Dynomite and Cassandra please take a look in the Wiki that I mentioned above.

Yes, we can send the keys to Dynomite in the new node and read them, and Dynomite would re-route properly, if necessary. We also need to delete those keys in the older node.

**Comment by balajivenki** [comment]
Thanks @ipapapa  for the clarification.
