### ISSUE TITLE
Question on Token Split in Dynomite

### ISSUE THREAD

**Issue by balajivenki** [Netflix/dynomite#349]
In my setup using generate_yamls.py when I setup 3 nodes of dynomite the tokens generated are a random number from 0-4294967295. 

That should be wrong right? My understanding is that for Dynomite the complete token range for the ring is 4294967295. So when we setup 3 nodes the token for the nodes are

node1: 1431655765
node2: 2863311530
node3: 4294967295

Is that a fair assumption and understanding? Please confirm. This will help us write our own config generator instead of using the py file provided.

**Comment by shailesh33** [comment]
I do not think it should be random. It should be equidistant from each other. But I will let @timiblossom confirm this since he is the original author of the script.

**Comment by balajivenki** [comment]
Thanks @shailesh33 .

The python script is getting random value(even overlapping one too). So I have changed it manually after generated by the script. Is my example correct and a fair assumption? Please suggest.

**Comment by balajivenki** [comment]
@shailesh33  I fixed the py script and created a PR .
