### ISSUE TITLE
Please tag the latest master release under tags

### ISSUE THREAD

**Issue by balajivenki** [Netflix/dynomite#352]
Can you Please tag the latest master release under tags? The latest tag we have is pretty old and when we package master which is stable the version comes as dirty.

**Comment by ipapapa** [comment]
What do you mean the tag is pretty old? The latest tag is 28 days old and seems to be working fine: https://github.com/Netflix/dynomite/releases/tag/v0.5.7-13_RectifyConsistency Do you face any issues?

**Comment by balajivenki** [comment]
There are constant commits to master, it happened yesterday also. This is more a tracking bug. I will take the new tag when there is one available. We are packaging it as rpm so it needs to fetch it from tag and unfortunately the latest master changes are not tagged yet, hence I created a tracking issue. Thanks for the quick response @ipapapa

**Comment by ipapapa** [comment]
Yeah, we tag when we do a fix or patch in master. We missed the one the last few days as it come from OSS contributors, but this should not stop you from picking the latest tag which is 28 days old.

**Comment by ipapapa** [comment]
Added the tag for you for the latest changes: https://github.com/Netflix/dynomite/releases/tag/v0.5.7-14_whiteSpaceStats

**Comment by balajivenki** [comment]
Thanks @ipapapa much appreciated
