### ISSUE TITLE
Question on pem_key_file conf

### ISSUE THREAD

**Issue by balajivenki** [Netflix/dynomite#355]
We have installed our dynomite and redis nodes and for the pem file we have given the path of the private key file and everything seems to be working fine. Question is who holds the public key, can you please share more info on the use of this pem key?

**Comment by ipapapa** [comment]
@balajivenki Dynomite uses AES for encrypting the data. AES is a symmetric algorithm (private-key cryptography). This involves a single key which is a shared secret between the sender and recipient. 

More info: https://en.wikipedia.org/wiki/Symmetric-key_algorithm

This is were Dynomite initializes the crypto implementation: https://github.com/Netflix/dynomite/blob/dev/src/dyn_crypto.c#L159-L167

**Comment by balajivenki** [comment]
Thanks @ipapapa 

So when we use our own pem file, dynomite is the recipient and dyno is the sender? Please confirm.

**Comment by ipapapa** [comment]
This encryption is not related to client to server communication. Dyno client and and Dynomite must run in the same secure environment (aka in the same datacenter), so encryption is not required. 

However, Dynomite perform cross-datacenter replication and this is over the public network in some cloud providers such as AWS. So we have added a secure_server_option which can be configured to 'none', 'rack', 'datacenter', or 'all'. This is where the encryption is used.

**Comment by balajivenki** [comment]
That makes it much clear. Thanks a lot @ipapapa
