### ISSUE TITLE
Building failed v0.5.8

### ISSUE THREAD

**Issue by balajivenki** [Netflix/dynomite#363]
Hi,

The latest version v0.5.8 building failed for us with the following error.

Making all in hashkit
make[3]: Entering directory `/home/build/rpmbuild/BUILD/dynomite-0.5.8/src/hashkit'
gcc -DHAVE_CONFIG_H -I. -I../..  -I ../../src -I ../../contrib/murmur3  -Wall -Wshadow -Wpointer-arith -Winline -Wunused-function -Wunused-variable -Wunused-value -Wno-unused-parameter -Wno-unused-value -Wconversion -Wsign-compare -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wmissing-declarations -Werror=implicit-function-declaration -g -O2 -MT dyn_crc16.o -MD -MP -MF .deps/dyn_crc16.Tpo -c -o dyn_crc16.o dyn_crc16.c
In file included from ../../src/dyn_core.h:131,
                 from ../../src/dyn_token.h:7,
                 from dyn_crc16.c:23:
../../src/dyn_util.h:353: error: redefinition of typedef 'msec_t'
../../src/dyn_types.h:4: note: previous declaration of 'msec_t' was here
../../src/dyn_util.h:354: error: redefinition of typedef 'usec_t'
../../src/dyn_types.h:5: note: previous declaration of 'usec_t' was here
dyn_crc16.c:62: warning: no previous prototype for 'hash_crc16'
dyn_crc16.c: In function 'hash_crc16':
dyn_crc16.c:68: warning: conversion to 'uint32_t' from 'char' may change the sign of the result
make[3]: *** [dyn_crc16.o] Error 1
make[3]: Leaving directory `/home/build/rpmbuild/BUILD/dynomite-0.5.8/src/hashkit'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/build/rpmbuild/BUILD/dynomite-0.5.8/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/build/rpmbuild/BUILD/dynomite-0.5.8'
make: *** [all] Error 2
error: Bad exit status from /home/build/rpmbuild/BUILDROOT/rpm-tmp.f7c7Be (%build)

RPM build errors:
    Bad exit status from /home/build/rpmbuild/BUILDROOT/rpm-tmp.f7c7Be (%build)

Is there any dependency added recently? v0.5.7-14 was successful though. Can you please share some pointers?

**Comment by shailesh33** [comment]
I am travelling right now. I will try to fix it as soon as I can.

**Comment by ipapapa** [comment]
@balajivenki The error should is shown above. However, I have build Dynomite master in both CentOS and Ubuntu and it built fine for me.

**Comment by balajivenki** [comment]
@ipapapa I used CentOS 7.2 with v0.5.8. Let me try building master branch instead of tag and let you know if I see the same issue.

**Comment by ipapapa** [comment]
I am using a fresh downloaded CentOS 7-2.1511.

**Comment by balajivenki** [comment]
@ipapapa  Apologies, it is CentOS 6.8

We ran the build again with master code and we get the same error. FYI running v0.5.7 again works fine though.

I have attached the build log as file here as you said the earlier logs are not so clear and readable.

Is there any new dependency added for 0.5.8?

Any help is greatly appreciated. 

[dynomite-0.5.8.log.txt](https://github.com/Netflix/dynomite/files/540647/dynomite-0.5.8.log.txt)

**Comment by ipapapa** [comment]
There is some redefinition error that appears. I have cleaned it here for the dev branch: https://github.com/Netflix/dynomite/pull/365

**Comment by balajivenki** [comment]
Thats good news @ipapapa 

Please let me know once it is fixed then I shall try with a new build.

I will keep this issue open till then.

**Comment by ipapapa** [comment]
Yes please, I directed the PR to dev. I will wait for the peer review process and unless there are any issues we can do it in master as well. Btw what is the `gcc` version you are running?

**Comment by balajivenki** [comment]
@ipapapa  Here is the gcc version we have

gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)

**Comment by ipapapa** [comment]
Yeah you have kind of an old version. Ubuntu comes with 5.4.0

**Comment by balajivenki** [comment]
Thanks @ipapapa I will check on that while we wait for the fix. Once the fix is ready then we shall try building it on both versions and see if it works.

**Comment by balajivenki** [comment]
@ipapapa  We run the build on CentOS 7.2 with gcc version 4.8.5 and it worked for us this time. Thanks a lot for all your help.

**Comment by ipapapa** [comment]
@balajivenki #365 has been merged to dev.
