### ISSUE TITLE
Descriptors leak in dyno stats at bunch of places

### ISSUE THREAD

**Issue by mikramulhaq** [Netflix/dynomite#366]
In stats_make_rsp a lot of case's we return without closing sd
https://github.com/Netflix/dynomite/blob/dev/src/dyn_stats.c#L1196

**Comment by ipapapa** [comment]
Aren't we closing `sd` inside the `stats_snd_rsp`? https://github.com/Netflix/dynomite/blob/dev/src/dyn_stats.c#L1170

**Comment by mikramulhaq** [comment]
@ipapapa yes sounds good. Thanks for looking. Will close issue.

**Comment by ipapapa** [comment]
no problem, thanks for taking a look. The more eyes the better :)
