### ISSUE TITLE
Compile error on CentOS 7

### ISSUE THREAD

**Issue by jonakoudijs** [Netflix/dynomite#369]
When following the build instructions from the README on a fresh CentOS 7 machine:

    $ git clone git@github.com:Netflix/dynomite.git
    $ cd dynomite
    $ autoreconf -fvi
    $ ./configure --enable-debug=yes
    $ make
    $ src/dynomite -h

The following build error appears:

    In file included from dyn_core.h:131:0,
                     from dyn_server.c:26:
    dyn_server.c: In function ‘server_deinit’:
    dyn_server.c:123:25: error: ‘s’ undeclared (first use in this function)
         ASSERT(TAILQ_EMPTY(&s->s_conn_q) && s->ns_conn_q == 0);
                             ^
    dyn_util.h:203:11: note: in definition of macro ‘ASSERT’
         if (!(_x)) {                                \
               ^
    dyn_server.c:123:12: note: in expansion of macro ‘TAILQ_EMPTY’
         ASSERT(TAILQ_EMPTY(&s->s_conn_q) && s->ns_conn_q == 0);
                ^
    dyn_server.c:123:25: note: each undeclared identifier is reported only once for each function it appears in
         ASSERT(TAILQ_EMPTY(&s->s_conn_q) && s->ns_conn_q == 0);
                             ^
    dyn_util.h:203:11: note: in definition of macro ‘ASSERT’
         if (!(_x)) {                                \
               ^
    dyn_server.c:123:12: note: in expansion of macro ‘TAILQ_EMPTY’
         ASSERT(TAILQ_EMPTY(&s->s_conn_q) && s->ns_conn_q == 0);
                ^
    dyn_server.c: In function ‘server_rsp_forward’:
    dyn_server.c:908:45: warning: conversion to ‘long unsigned int’ from ‘int64_t’ may change the sign of the result [-Wsign-conversion]
             uint64_t delay = dn_usec_now() - req->request_send_time;
                                                 ^
    dyn_server.c: In function ‘req_send_done’:
    dyn_server.c:1011:41: warning: conversion to ‘int64_t’ from ‘usec_t’ may change the sign of the result [-Wsign-conversion]
         msg->request_send_time = dn_usec_now();
                                             ^
    dyn_server.c: In function ‘req_server_enqueue_imsgq’:
    dyn_server.c:1029:55: warning: conversion to ‘int64_t’ from ‘usec_t’ may change the sign of the result [-Wsign-conversion]
         msg->request_inqueue_enqueue_time_us = dn_usec_now();
                                                           ^
    dyn_server.c: In function ‘req_server_dequeue_imsgq’:
    dyn_server.c:1060:40: warning: conversion to ‘long unsigned int’ from ‘int64_t’ may change the sign of the result [-Wsign-conversion]
         int64_t delay = dn_usec_now() - msg->request_inqueue_enqueue_time_us;
                                            ^
    dyn_server.c:1060:35: warning: conversion to ‘int64_t’ from ‘long unsigned int’ may change the sign of the result [-Wsign-conversion]
         int64_t delay = dn_usec_now() - msg->request_inqueue_enqueue_time_us;
                                       ^
    dyn_server.c:1061:5: warning: conversion to ‘uint64_t’ from ‘int64_t’ may change the sign of the result [-Wsign-conversion]
         histo_add(&ctx->stats->server_queue_wait_time_histo, delay);
         ^
    make[3]: *** [dyn_server.o] Error 1
    make[3]: Leaving directory `/root/dynomite/src'
    make[2]: *** [all-recursive] Error 1
    make[2]: Leaving directory `/root/dynomite/src'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/root/dynomite'
    make: *** [all] Error 2

I have the following prerequisites installed:

* autoconf-2.69-11.el7.noarch
* libtool-2.4.2-21.el7_2.x86_64
* libevent-2.0.21-4.el7.x86_64
* openssl-devel-1.0.1e-51.el7_2.7.x86_64

System information:

    Linux dynomite-01 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ipapapa** [comment]
It seems I recently broke it: https://github.com/Netflix/dynomite/commit/e285e2ffd88348529857011d3783fa4415e626b0

**Comment by ipapapa** [comment]
BTW, please try without the debug flag as well.

**Comment by jonakoudijs** [comment]
Compile is now successful. Thanks!
