### ISSUE TITLE
Is transactions in Redis supported in Dynomite ?

### ISSUE THREAD

**Issue by europelee** [Netflix/dynomite#372]
Hi, I know Dynomite supported pipeline in redis.
Did Dynomite support transactions in Redis?

**Comment by shailesh33** [comment]
Hi,
Dynomite does not support transactions in Redis. Let us know if you have
any further questions and I can elaborate.

**Comment by ipapapa** [comment]
Closing this under the assumption that your question has been answered. If you have any further questions please follow up we can reopen the issue.
