### ISSUE TITLE
Building master fails on CentOS 6.6

### ISSUE THREAD

**Issue by MrAlias** [Netflix/dynomite#379]
Trying to build the `master` branch I received the following error:

```
Making all in src
make[2]: Entering directory `/home/vagrant/dynomite/src'
Making all in hashkit
make[3]: Entering directory `/home/vagrant/dynomite/src/hashkit'
gcc -DHAVE_CONFIG_H -I. -I../..  -I ../../src -I ../../contrib/murmur3  -Wall -Wshadow -Wpointer-arith -Winline -Wunused-function -Wunused-variable -Wunused-value -Wno-unused-parameter -Wno-unused-value -Wconversion -Wsign-compare -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wmissing-declarations -Werror=implicit-function-declaration -g -O2 -MT dyn_crc16.o -MD -MP -MF .deps/dyn_crc16.Tpo -c -o dyn_crc16.o dyn_crc16.c
In file included from ../../src/dyn_core.h:131,
                 from ../../src/dyn_token.h:7,
                 from dyn_crc16.c:23:
../../src/dyn_util.h:353: error: redefinition of typedef ‘msec_t’
../../src/dyn_types.h:4: note: previous declaration of ‘msec_t’ was here
../../src/dyn_util.h:354: error: redefinition of typedef ‘usec_t’
../../src/dyn_types.h:5: note: previous declaration of ‘usec_t’ was here
dyn_crc16.c:62: warning: no previous prototype for ‘hash_crc16’
dyn_crc16.c: In function ‘hash_crc16’:
dyn_crc16.c:68: warning: conversion to ‘uint32_t’ from ‘char’ may change the sign of the result
make[3]: *** [dyn_crc16.o] Error 1
make[3]: Leaving directory `/home/vagrant/dynomite/src/hashkit'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/vagrant/dynomite/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/vagrant/dynomite'
make: *** [all] Error 2
```

This error appears to be related to a recent commit, as this process was building successful yesterday.  The steps taken to reproduce the above error:

1. `git clone -b master https://github.com/Netflix/dynomite.git` (commit hash built from `f1ef86ecbb02e249f76888253faa8ffaf38de88e`)
1. `cd dynomite`
1. `autoreconf -fvi`
1. `./configure --enable-debug=yes`
1. `make`

I received the same error on both a bare metal system and a Virtualbox VM both running identical versions of CentOS 6.6:

```
$ uname -a
Linux vm 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)

$ autoreconf --version
autoreconf (GNU Autoconf) 2.63

**Comment by shailesh33** [comment]
Can you check if dev works for you?

**Comment by MrAlias** [comment]
@shailesh33 it looks like the `dev` branch does build and does not have this problem and successfully builds.

**Comment by MrAlias** [comment]
@shailesh33 it looks like it must have been a late night for me as I seemed to have missed #363, which appears to be the same behavior.  My apologies for the duplicate.

Is there any plans to integrate building the project on RHEL distros in the travis-ci setup in order to catch this in the future?

**Comment by ipapapa** [comment]
@MrAlias I am not following how this issue appeared yesterday although it had been fixed back in October #365

**Comment by shailesh33** [comment]
@MrAlias I did port the fix from dev to master to fix the rebuild but I do not have the setup to test out the build for RHEL. Can you please checkout the latest and see if its fixed? Please reopen the issue if you still have problems.

**Comment by MrAlias** [comment]
@shailesh33 thanks for the hotfix!  Things are building from `master` now with the setup described above.

@ipapapa thanks for the info on how to proceed with the RHEL distros support.

**Comment by ipapapa** [comment]
thank you @MrAlias.
