### ISSUE TITLE
entropy init

### ISSUE THREAD

**Issue by upcloud** [Netflix/dynomite#390]
i have read through the source code of  dynomite ,but i am a little confused about the entroy_init ,it seems hard code and listen on port 8105 ,but there is no logic to be connected by peer or client .is it for the next release to help replicate or has it already in use  for clustering .if so ,who you give some advice to replicate the data through different rack

**Comment by shailesh33** [comment]
8105 port was opened for a external reconciliation process that we were developing using spark. The spark portion is developed and the rest is a work in progress.

**Comment by ipapapa** [comment]
@shailesh33 shall I move the hard coded port and IP value of the entropy code to the YAML?

**Comment by shailesh33** [comment]
May be not yet, till we are ready with the rest of the system?
