### ISSUE TITLE
Data retrieval issue on 3 rack dynomite

### ISSUE THREAD

**Issue by maryoush** [Netflix/dynomite#392]
Hi 
we have 3 node setup of dynomite (similar to https://github.com/Netflix/dynomite/blob/dev/conf/redis_rack1_node.yml / https://github.com/Netflix/dynomite/blob/dev/conf/redis_rack2_node.yml /
https://github.com/Netflix/dynomite/blob/dev/conf/redis_rack3_node.yml)

We have created simple client https://github.com/maryoush/dynomite-client
For many reasons we  couldn't use the Eureka (and we have  fixed host discovery as in project above)

The issue is that we can store messages (token wise across the cluster), but we retrieve only those in my local rack(rack1).

Do I have to create separate clients for each rack in DC ?

**Comment by maryoush** [comment]
Looking down to Redis each rack (each has a single node per rack)
sees 3 queues/sets
testdynoqueues.QUEUE.queue1.k1 zset
testdynoqueues.QUEUE.queue1.k2 zset
testdynoqueues.QUEUE.queue1.k3 zset

And my client for local rack (rack1) just is able to get the elements from first set

**Comment by maryoush** [comment]
The issue was on our site we had sharding while writing but only while reading we get data for current/local shard

**Comment by maryoush** [comment]
I think the take-away is that com.netflix.dyno.queues.ShardSupplier description is not intuitive
If you don't provide consistent shard supplier you can not get your data back.

**Comment by ipapapa** [comment]
@v1r3n ^^

**Comment by v1r3n** [comment]
dyno-queues uses the sharding strategy to put data into each rack.  The client reads data only from the current shard.  When deploying you want to have at-least one broker for dyno-queues in each rack.
