### ISSUE TITLE
dynomite  data sync problem

### ISSUE THREAD

**Issue by europelee** [Netflix/dynomite#399]
hi,
I test dynomite:
1.  set up two data center of dynomite: dy1, dy2, they are in one cluster.
2.  stop dy2, then write some new data to dy1
3.  start dy2, and can not read new data.

did dynomite support the availability？

**Comment by ipapapa** [comment]
There is a difference between the notions of availability and data consistency (see [CAP theorem](https://en.wikipedia.org/wiki/CAP_theorem)). Dynomite is designed to be an AP system. 

In your deployment, it seems you took down a whole datacenter. In each datacenter, I am assuming you have at least 3 replica nodes. If you take a whole data center down, i.e. all three nodes, then the data will be lost on that datacenter. However, if at least one replica in the datacenter is alive you can trigger the [warm up/cold bootstrap](https://github.com/Netflix/dynomite-manager/wiki/Cold-Bootstraping) and Dynomite-manager will automatically bring the new Dynomite node with all the missing data. There are also some other options for a datacenter disaster. One is to [backup/restore](https://github.com/Netflix/dynomite-manager/wiki/Backups-and-Restores) the data, or to manually take a dump of Redis from a remote data center and transfer the data to the other data center.

If you took down a single node, then there will be entropy in the system which can be mitigated in the client by leveraging [higher consistency guarantees](https://github.com/Netflix/dynomite/wiki/Consistency).
