### ISSUE TITLE
support mysql?

### ISSUE THREAD

**Issue by oz-cdu** [Netflix/dynomite#400]
I saw the news in http://techblog.netflix.com/2014/11/introducing-dynomite.html

A datastore can be either a volatile datastore such as Memcached or Redis, or persistent datastore such as Mysql, BerkeleyDb or LevelDb.  **Our current open sourced Dynomite offering supports Redis and Memcached**.

Now support mysql?

**Comment by shailesh33** [comment]
Hi @oz-cdu , we do not have support for MySQL. And that doesnt seem to be on our roadmap of development internally. But depending on your requirement and use case, you can help implement and contribute or look at other redis bases persistent stores like ARDB. Please let us know if you have further questions.

**Comment by oz-cdu** [comment]
@shailesh33 Thanks!
