### ISSUE TITLE
Build broken on Alpine 3.4 with musl libc.

### ISSUE THREAD

**Issue by blinohod** [Netflix/dynomite#408]
When building Dynomite on Alpine Linux (and musl libc) from `master` branch I get the following error:

* Base image: `alpine:3.4`
* GCC: 5.3.0

Commands (from Dockerfile):
```
apk update --no-cache && apk add --no-cache build-base git autoconf automake libtool gettext openssl-dev
git clone -b master https://github.com/Netflix/dynomite.git
cd dynomite
autoreconf -fvi
./configure
make
```

Compilation failed with the following error message:
```
gcc -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE -I ../src/hashkit -I ../src/proto -I ../src/event -I ../src/entropy -I ../src/seedsprovider -I ../contrib/yaml-0.1.4/include  -Wall -Wshadow -Wpointer-arith -Winline -Wunused-function -Wunused-variable -Wunused-value -Wno-unused-parameter -Wno-unused-value -Wconversion -Wsign-compare -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wmissing-declarations -Wimplicit-function-declaration -g -O2 -MT dyn_dict_msg_id.o -MD -MP -MF .deps/dyn_dict_msg_id.Tpo -c -o dyn_dict_msg_id.o dyn_dict_msg_id.c
dyn_dict_msg_id.c:1:31: fatal error: libio.h: No such file or directory
compilation terminated.
```

Seems like the following commit brought this issue by using `libio.h` that does not present in musl libc.
https://github.com/Netflix/dynomite/commit/d38eaa428d71de52e83f8c9f910cdae7f207f41b

Exact line:
https://github.com/Netflix/dynomite/blob/d38eaa428d71de52e83f8c9f910cdae7f207f41b/src/dyn_dict_msg_id.c#L1

Is it possible to define `NULL` differently if building against musl and not glibc?

Thanks :-)

**Comment by shailesh33** [comment]
@blinohod I do not have the setup to test this out: what would be your recommendation to fix it? You can create a PR if you have a local fix. 

Meanwhile I tried to remove that libio include and it compiled just fine for my setup

**Comment by ipapapa** [comment]
@blinohod any update on this issue, or shall we close it because you lost interest in it?

**Comment by blinohod** [comment]
@ipapapa sorry, completely distracted :(

Actually just succeed with the following patch against recent master:
https://github.com/blinohod/dynomite/commit/b80e9f95a5a8ad259c59011cdd7c57fe05042229

Built on Alpine Linux 3.4 and Ubuntu 16.04 successfully.

**Comment by blinohod** [comment]
I also tried to remove `#include libio.h` but this breaking build on Alpine due to `NULL` macro becomes undefined.

**Comment by shailesh33** [comment]
Did you pull the latest?

**Comment by blinohod** [comment]
Yes, my update was based on recent `master` branch .

I've also tried to apply my patch against `dev` branch and seems other changes were added incompatible with musl.

**Comment by shailesh33** [comment]
Do you have the setup of steps to build with musl, what OS to install,
packages etc ?

**Comment by blinohod** [comment]
Sure, I use Docker to build and here is example process:
https://gist.github.com/blinohod/feb71cfbcc1ae342b4682e3d7e937fa1

OS: Alpine Linux 3.4 ( x86_64 )

**Comment by kaniini** [comment]
NULL should be brought in via stdlib.h, not libio.h.  libio.h is a GNU libc extension.

**Comment by shailesh33** [comment]
ah ok. I will take care of it.

**Comment by shailesh33** [comment]
@blinohod I have fixed the libio thing. Can you try compiling now?
It works for me in mac & linux

**Comment by shailesh33** [comment]
I will close this issue but please reopen it if you still have any problems.
Thanks @kaniini
