### ISSUE TITLE
Requests are not getting forwarded to other rack

### ISSUE THREAD

**Issue by sairam546** [Netflix/dynomite#411]
Hey,

We are using Ruby gem to 'Redis' to connect to dynomite from our ruby application. If the redis in that node is not available or getting killed, the requests are not getting forwarded to nodes or replicas in other racks. 

Is there any configuration we have to set to forward requests to other nodes when redis in that machine is not available ?

Is it is the feature not available in dynomite ?

Do I have to use some way or some other gem instead of redis to connect to dynomite ?

Please help

**Comment by shailesh33** [comment]
Some questions: 
1) Which requests are not getting forwarded, reads or writes or both?
2) Ideally you want to take that node out of your client configuration in such cases and failover to other rack. We do that in dyno java client (https://github.com/Netflix/dyno)
3) Also depends on your quorum settings wether it is DC_ONE or DC_QUORUM or DC_SAFE_QUORUM

**Comment by sairam546** [comment]
I am not using dyno client. I am using redis gem to connect to dynomite since I am connecting from a  ruby application. 

Both read and write requests are not getting forwarded. It is stating storage not available when we try to perform operation in the node whose redis is offline.

Kindly help me out

**Comment by shailesh33** [comment]
Can you check why redis is offline or failing in the first place? Did you check if the key is there in the cluster? The local node must have failed but I am sure it replicated to other nodes. I agree the error is misleading in such case

**Comment by sairam546** [comment]
I am failing redis to test the fail over. Yes the keys are replicating.

**Comment by shailesh33** [comment]
You should treat, in such cases, the node as unhealthy and failover to another rack in the cluster. This is a client side failover rather than a server side. But the idea is that the client is talking to a node that is, sort of, unavailable. 
We have a side car (https://github.com/Netflix/dynomite-manager) that you can run on every dynomite node which keeps track of the status of redis and dynomite. OSS community has been using other clients with such discovery mechanism.

**Comment by shailesh33** [comment]
I will close this issue. Please feel free to reopen or open a new one if you have further questions
