### ISSUE TITLE
How about support pika in dynomite

### ISSUE THREAD

**Issue by baotiao** [Netflix/dynomite#413]
https://github.com/Qihoo360/pika
Pika is a nosql compatible with redis, pika support about 90% redis commands, and it's widely used in many company, you can get it from README.

So, can you support pika in dynomite

**Comment by shailesh33** [comment]
If it understands redis protocol, things should work just fine with Pika.  You can try replacing underlying redis with a pika server running on the same port and see. Feel free to reach out if you need further info.

**Comment by shailesh33** [comment]
@baotiao Have you tried this? Please let me know if you see any issues while using it. I am closing this for now.
