### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by vwyuheng** [Netflix/dynomite#414]
CentOS release 6.4
yum install -y git autoconf automake libtool openssl-devel net-tools

but when i execute make command, errors as follow:
dyn_crypto.c: In function ‘aes_init’:
dyn_crypto.c:130: error: invalid application of ‘sizeof’ to incomplete type ‘EVP_CIPHER_CTX’ 
dyn_crypto.c:131: error: invalid application of ‘sizeof’ to incomplete type ‘EVP_CIPHER_CTX’ 

make[3]: *** [dyn_crypto.o] Error 1
make[3]: Leaving directory `/app/tools/git/dynomite/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/app/tools/git/dynomite/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/app/tools/git/dynomite'
make: *** [all] Error 2

**Comment by ipapapa** [comment]
@vwyuheng have you resolved the issue? Are you still facing the issue and are interested for a response? or can we close it since there is no further interest...

**Comment by vwyuheng** [comment]
its all right now,thanks

**Comment by daflip** [comment]
FWIW this seems to occur when you use openssl libs v1.1.0 rather than 1.0.1.
