### ISSUE TITLE
make failing

### ISSUE THREAD

**Issue by ajayaks** [Netflix/dynomite#418]
Hi, 

I am trying to run dynomite on my mac but getting below exception during make.

Undefined symbols for architecture x86_64:
  "_register_printf_function", referenced from:
      _core_register_printf_function in dyn_core.o
     (maybe you meant: _core_register_printf_function)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [dynomite] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Please suggest.
Regards
Ajay

**Comment by shailesh33** [comment]
Any reason you are building dev?

**Comment by ajayaks** [comment]
Thanks.
I have switched to master and noticed its failing. I found fixed as i am using mac so i have fixed its locally.

2 warnings generated.
mv -f .deps/dyn_client.Tpo .deps/dyn_client.Po
gcc -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE -I ../src/hashkit -I ../src/proto -I ../src/event -I ../src/entropy -I ../src/seedsprovider -I ../contrib/yaml-0.1.4/include  -Wall -Wshadow -Wpointer-arith -Winline -Wunused-function -Wunused-variable -Wunused-value -Wno-unused-parameter -Wno-unused-value -Wconversion -Wsign-compare -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wmissing-declarations -Wimplicit-function-declaration -g -O2 -MT dyn_dict_msg_id.o -MD -MP -MF .deps/dyn_dict_msg_id.Tpo -c -o dyn_dict_msg_id.o dyn_dict_msg_id.c
dyn_dict_msg_id.c:1:10: fatal error: 'libio.h' file not found
#include <libio.h> // For NULL




After that i have started dynomite via "./src/dynomite" so its up now http://localhost:22222/<arg>.

I have below doubts so please put some light.

1. I have not started redis on my machine
2. Not passed any configuration also.

I want to know whats happening inside, whats is the default setup and what are changes i need to do make it work with reddis?


https://github.com/Netflix/dynomite/blob/master/conf/dyn_redis_single.yml is not available.


If i push some key-value pair via redis-cli can i see/get that somehow via apis?

Please suggest.

Regards
Ajay

**Comment by ajayaks** [comment]
Its working now.
I have started local instance of redis at 6379 port and update the default.xml.
Now i can access redis via port 8102.

Do you have package for ubuntu 16 also ?
Regards
Ajay

**Comment by ipapapa** [comment]
@ajayaks We have not worked on building a package for Ubuntu, but we are always welcoming contributions. There was some effort for Debian https://github.com/Netflix/dynomite/issues/367 but I am not sure how far it has progressed.

**Comment by shailesh33** [comment]
@ajayaks I have tried fixing Dynomite both master and dev. You may want to pull the latest.

**Comment by shailesh33** [comment]
@ajayaks I think the latest of master builds fine on mac. Please reopen the issue, if you still have a problem.
