### ISSUE TITLE
Support for LEX and HLL commands in Redis

### ISSUE THREAD

**Issue by mattrobenolt** [Netflix/dynomite#42]
I contributed these a while back to twemproxy and can easily be merged in here:

HLL: https://github.com/twitter/twemproxy/commit/0d3084be2c4d3d8cb64cb6199db3413d2cbcda42
LEX: https://github.com/twitter/twemproxy/commit/f0f6e6b08ca8c356f653b1998f0585aeb85779cb

Let me know if you'd like a specific Pull Request for these or if you can just yank these commits. Looks like they'd just apply cleanly.

**Comment by ipapapa** [comment]
Did the work due to inactivity: https://github.com/Netflix/dynomite/pull/294/commits/4072346c90e4a1a6823bcbe40ffc0dc95d5d0748
