### ISSUE TITLE
Dynomite log file grows indefinitely when idle for a while

### ISSUE THREAD

**Issue by balajivenki** [Netflix/dynomite#421]
Hi,

We are facing issues with the log file rotation with dynomite and it is causing the application to stop and the service go down.

Here are the details:
1) The Dynomite + Redis cluster has been idle when the errors show up in the Dynomite log file.
2) If the service is idle for a while then Dynomite starts writing the error "Too many open files" at the rate of hundreds per millisecond.
3) Logrotate is not able to rotate the Dynomite log file when written so rapidly, causing a single log file to grow to GBs in size until all disk space is depleted.

Changing the log level might not help us here as the log is logged as error

`
stats_send_rsp(struct stats *st)
{
    int sd;

    sd = accept(st->sd, NULL, NULL);
    if (sd < 0) {
        log_error("accept on m %d failed: %s", st->sd, strerror(errno));
        return DN_ERROR;
    }`

can you please fix it for us as it is causing service interruption and dynomite stops after a while due to disk not available.

**Comment by shailesh33** [comment]
any idea what is causing this?

**Comment by balajivenki** [comment]
not sure but what my guess is that the cluster is been idle for few days. When thats the case we see the log files grows infinitely and causes this error.

**Comment by shailesh33** [comment]
can you check your netstat output ?

On Fri, Feb 17, 2017 at 2:49 PM, Balaji Venkatesan <notifications@github.com

**Comment by AlexBoyd** [comment]
I've seen a similar issue pop up on a small evaluation cluster I've gotten. 

I have a single node that has itself listed in the dyn_seeds section. It appears to be opening connections to itself that get stuck in this state: 
<hostname>.:8102 hostname>:57074 CLOSE_WAIT
<hostname>54112 <hostname>:6379 TIME_WAIT
<hostname>:57596<hostname>:8102 FIN_WAIT2

I see all three of the above states, The vast majority being the ones hanging in the close wait. Is it possible that this is a bug in the case of a node not handling having itself in the dyn_seeds list. 

Once it opens too many of these hanging sockets it runs out of file descriptors and starts to log "Too many open files"

**Comment by balajivenki** [comment]
I have a question along the same lines, whats the ideal conf value for **dyn_seeds**? Can it have one node per rack? Or does it have to have all the other nodes in all the other racks.

In my setup I have 3 local and 3 replication as two racks. Rack1 has 1, 2, 3 and Rack2 has 4, 5, 6 which is replication. On Node 1 I provide 2, 3, 4, 5, 6 as seeds. Is that correct? Please suggest.

**Comment by shailesh33** [comment]
Hello
The dyn_seeds should have all the nodes in the cluster except self. It
might be a bug that it is connecting to itself. But since its a config
issue, you should avoid it in the first place.

On Tue, Feb 28, 2017 at 5:31 PM, Balaji Venkatesan <notifications@github.com

**Comment by balajivenki** [comment]
Thanks @shailesh33 I have kept it that way. One thing strange we see is that when we roll the logs sometimes the dyn_listen port goes down. E.g we have centOS log rotation policy of per hour or 100MB. The log rotation happens right, however sometimes when the log rotation happens I think due to file lock or something the port mentioned on dyn_listen(means the listening) goes down and hence dynomite goes down or unusable. Any idea how to handle it? Can you share more details on how Netflix rotates the log in its dynomite PROD env?

**Comment by shailesh33** [comment]
I haven't seen that before. We have a general company wide system log
rotation of every 2 hours and may be some file size.
Are you hitting the 1 hour limit or file size?

On Wed, Mar 1, 2017 at 10:59 AM, Balaji Venkatesan <notifications@github.com

**Comment by balajivenki** [comment]
@shailesh33 We are hitting the hour limit most of the time. This is in our QA env and most of the time the servers are idle, means redis/dynomite is not actively used. Does it cause any of the issues? Unfortunately there is no core here or something for us to debug.

**Comment by shailesh33** [comment]
Do you know if the issue exists before you log rotate? Try connecting to
dynomite a few seconds before the log rotation?

On Wed, Mar 1, 2017 at 11:15 AM, Balaji Venkatesan <notifications@github.com

**Comment by balajivenki** [comment]
We haven't checked that @shailesh33  we will get notified when dynomite is not running or the port is not listening. When we get the alert we go to the node and see the new log is 0bytes and so we know that the log has rotated and nothing happened after that, and this happens 2/10 times.

**Comment by shailesh33** [comment]
1) change the frequency to be more often, so we can debug
2) Is it possible to attach gdb and see if the threads are stuck
3) do a netstat for dynomite ports
4) Do you have a dynomite-manager running, it should do a PING every 30
secs. Can you increase the log level may be just before the log rotation:
curl -s http://localhost:22222/loglevelup


On Wed, Mar 1, 2017 at 11:36 AM, Balaji Venkatesan <notifications@github.com

**Comment by balajivenki** [comment]
Thanks @shailesh33  I will follow the debugging steps and update here. FYI we do not use dynomite-manager.

**Comment by ipapapa** [comment]
Is this a duplicate of #424? Can we close this then?

**Comment by balajivenki** [comment]
Yes @ipapapa this can be closed.
