### ISSUE TITLE
Dynomite closes listening socket

### ISSUE THREAD

**Issue by balajivenki** [Netflix/dynomite#424]
Dynomite log file grows infinitely with the following error

`stats_send_rsp:1183 accept on m 5 failed: Too many open files`

We have also noticed that the service is down on its listening port configured with listen configuration. Can you please suggest and help us?

**Comment by shailesh33** [comment]
You are not using dynomite-manager from what I know, can you see if the
socket is being closed properly?
what does lsof, netstat shows/

On Fri, Mar 3, 2017 at 11:26 AM, Balaji Venkatesan <notifications@github.com

**Comment by balajivenki** [comment]
@shailesh33  Here is what I see for netstat when the service is down. Please note that 50172 is down.

```
[eng_sjc01_p08 root@qredis01 bvenkatesan]# netstat 50171
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 redis01.p08.eng.s:50171 isn01.p08.eng.sjc:45149 CLOSE_WAIT
tcp        0      0 redis01.p08.eng.s:50171 isn01.p08.eng.sjc:50037 CLOSE_WAIT
^C
[eng_sjc01_p08 root@qredis01 bvenkatesan]# netstat 50172
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 redis01.p08.eng.s:50171 isn01.p08.eng.sjc:45149 CLOSE_WAIT
tcp        0      0 redis01.p08.eng.s:50171 isn01.p08.eng.sjc:50037 CLOSE_WAIT
^C
[eng_sjc01_p08 root@qredis01 bvenkatesan]#
```
Since we are not using dynomite manager, should I need to tweak my config?

I have attached the config file with this ticket for your review. 


[dyn_o_mite.txt](https://github.com/Netflix/dynomite/files/817747/dyn_o_mite.txt)

**Comment by balajivenki** [comment]
Here is netstat for 50172 port(listen port) from another server that has the same issue

```
[eng_sjc01_p08 root@qredis05 bvenkatesan]# netstat 50172
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:49535 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 redis04.p08.eng.s:40898 ESTABLISHED
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:51598 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:46376 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:51703 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:52200 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:36795 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:53357 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:46052 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:47542 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:37578 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:53085 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 redis04.p08.eng.s:57150 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:41557 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:36065 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:44330 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:41372 log01.p08.eng.:palace-6 ESTABLISHED
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:51894 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:60866 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:46815 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:57620 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:41714 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:48065 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:58873 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:55334 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:45323 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:36492 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:44434 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:53901 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:37079 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:36497 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:44960 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:46074 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:44972 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:56613 CLOSE_WAIT
tcp        0      0 localhost:38692         localhost:50180         TIME_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:57474 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:40649 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:53464 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:60831 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:44427 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:42801 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:48727 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:47085 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:38560 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:33489 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:46986 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:35153 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:36094 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:34602 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:58235 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:33396 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:44970 CLOSE_WAIT
tcp        0      0 redis05.p08.eng.s:50171 isn01.p08.eng.sjc:50736 CLOSE_WAIT
^C
```

**Comment by balajivenki** [comment]
Here is the output for lsof(attached) and this is taken from node1 in the config mentioned above. Please note that I have pasted last few lines.
[lsof.txt](https://github.com/Netflix/dynomite/files/817772/lsof.txt)

**Comment by balajivenki** [comment]
@shailesh33 Any update on this please? I have restarted the servers on friday and now I see the same issue, dynomite is not listening on port 50172. The netstat is similar to what I have posted earlier and unfortunately no core. Can you please review my dynomite conf and see if I do anything obvious in the conf?

**Comment by shailesh33** [comment]
Is this your test cluster?

**Comment by balajivenki** [comment]
Yes @shailesh33  This is our QA server and this also happens in dev as well. We are not in PROD yet as this issue is blocking us to go so.

**Comment by shailesh33** [comment]
It looks like most of your close wait connections are to your dynomite port 50171 (which by default is 8101). Can you see if those close wait connections are legit?

Can you also try the branch v0.5.9 and tell me if you have the same issues?

**Comment by balajivenki** [comment]
Thanks @shailesh33  I will check with v0.5.9, however with the latest experiment of not rotating logs I am still able to repro the issue and I think at this point its nothing to do with the log rotation script. Not sure if you remember, we had core due to our in house vulnerability management scans running on all these machines. It does a port scan and used to cause core with invalid entry. The scan runs everyday and that might even contribute to this. I have a pattern I see here, however it does not happen all the time. Here are the sample logs collected from a failure node. And I have attached the detailed log as well.

```
[2017-03-07 14:25:11.344] dnode_accept:172 Accepting client connection from 10.44.93.254/53863 on sd 619
[2017-03-07 14:25:11.344] dnode_accept:217 dyn: accepted LOCAL_PEER_CLIENT 619 on PEER_PROXY 9 from '10.44.93.254:53863'
[2017-03-07 14:25:11.446] dnode_accept:172 Accepting client connection from 10.44.93.254/53864 on sd 620
[2017-03-07 14:25:11.446] dnode_accept:217 dyn: accepted LOCAL_PEER_CLIENT 620 on PEER_PROXY 9 from '10.44.93.254:53864'
[2017-03-07 14:25:11.548] dnode_accept:172 Accepting client connection from 10.44.93.254/53865 on sd 621
[2017-03-07 14:25:11.548] dnode_accept:217 dyn: accepted LOCAL_PEER_CLIENT 621 on PEER_PROXY 9 from '10.44.93.254:53865'
[2017-03-07 14:25:20.066] conn_recv_data:632 recv on sd 614 eof rb 24 sb 0
[2017-03-07 14:25:20.066] req_recv_next:332 eof c 614 discarding incomplete req 12403059 len 24
[2017-03-07 14:25:20.066] dnode_accept:172 Accepting client connection from 10.44.93.254/53964 on sd 622
```

[dynomite-log.txt](https://github.com/Netflix/dynomite/files/825611/dynomite-log.txt)

Do you think the 

> Accepting client connection from 10.44.93.254/53968

 and then posting incomplete req can cause this over a period of attempts?

Now I am going to increase the log level to 9 or something and let the scan run to see if I can gather more logs on this case.

**Comment by shailesh33** [comment]
I am guessing that dynomite is probably not calling close on its side. I
fixed it v0.5.9. Let me know what you see.

On Tue, Mar 7, 2017 at 11:53 AM, Balaji Venkatesan <notifications@github.com

**Comment by balajivenki** [comment]
Sure, thanks @shailesh33  I will try it on v0.5.9 and update here, I will keep the issue open till then.

**Comment by balajivenki** [comment]
@shailesh33 I have installed v0.5.9 on all my machines and so far the issue not happening consistently as it used to happen, thats a good sign. However I see few nodes go down randomly and those are especially the nodes in replication rack(not sure if that has to do anything with it). I have attached the log for the hour we think the node went down.Please have a look at it and see if you can infer something. However the good news is that the issue is not happening consistently like before so v0.5.9 is much better than 0.5.8

[dynomite.log-20170311-1489244461.txt](https://github.com/Netflix/dynomite/files/836059/dynomite.log-20170311-1489244461.txt)

**Comment by shailesh33** [comment]
There is a lot of noise in the logs. Why are there all weird requests on
the stats port and the peer port. Some security scan It seems. you will
have to either black list these ports from scanning, or add better handing
of these requests on the ports. Can you confirm?

-Shailesh

**Comment by balajivenki** [comment]
@shailesh33  Yes you are right, we do our VM and WAS scans on all our hosts and the scan used to even produce core on dynomite and you have fixed it earlier. On and off this happens, the scan runs everyday on all machines and not all nodes go down and not all the time. Is exclusion the only option here for us?

**Comment by shailesh33** [comment]
Hi Balaji
You can either Exclude the ports or check if the scanners are keep the
ports open and not closing the sockets. You can also try to debug the stats
port and see if we are closing the socket when there is some error (wrong
GET path). I would have helped, but my hands are full at the moment. I can
check the code later or you can try debugging the code.

Regards
Shailesh

**Comment by balajivenki** [comment]
Thanks a lot @shailesh33 I will work with my network team to see if we can exclude the hosts or least exclude the ports. That will help us eliminating the issue. Appreciate your help on it.

**Comment by balajivenki** [comment]
@shailesh33  I am actively looking for possibilities to exclude the port from the scan. However when you get time if you could fix the issue for us then that would be great. Sorry for pressing more on this issue as the entire dynomite stack is in question and all the efforts too if the servers goes down due to scan. Entire 3 months of evaluation, dev effort will go in vain due to this issue.

**Comment by shailesh33** [comment]
I will see what can be done.
@ipapapa FYI.

**Comment by ipapapa** [comment]
@balajivenki I am sorry to interfere here, I am still missing the reason why there are so many irrelevant HTTP requests to Dynomite stats port. For example:

> [2017-03-11 14:15:33.700] parse_request:997 GET /includes/hotnews-engine.inc.php3 HTTP/1.1
> [2017-03-11 14:15:33.700] parse_request:1003 1: /includes/hotnews-engine.inc.php3
> [2017-03-11 14:15:33.701] parse_request:1003 1: //n0tAChaNc3.printer
> [2017-03-11 14:15:33.702] parse_request:1003 1: /?mode=view&album=%60cat%20/etc/passwd%60

**Comment by balajivenki** [comment]
@ipapapa  The requests are caused by the VM and WAS scans on the hosts. Unfortunately for security purpose we cannot turn them off, I am trying my best to exclude the ports used here. The requests are made by the WAS scanner to check if all is good. When the scan runs not all the time the port goes down on and off it goes down with version 0.5.9. With earlier version 0.5.8 it used to go down consistently and @shailesh33 fixed few connection closing issues in 0.5.9 and that made the build stable than before, yet we see this issue on few random nodes. I have 3 clusters, 6 each and I can constantly repro the issue.

**Comment by ipapapa** [comment]
@balajivenki are you also running with Gossip enabled:
> [2017-03-11 14:51:28.484] gossip_loop:792 Gossip is running ...

**Comment by balajivenki** [comment]
I thought it is disabled by default. Here is what the conf I have on pretty much all nodes(with different servers and tokens)

```
dyn_o_mite:
  auto_eject_hosts: 'true'
  data_store: 0
  datacenter: ENG_SFO01_P08
  dyn_listen: 0.0.0.0:50171
  dyn_port: 50171
  dyn_seed_provider: simple_provider
  dyn_seeds:
  - qredis02.p08.eng.qualys.com:50171:rack02:ENG_SFO01_P08:1431655765
  - qredis04.p08.eng.qualys.com:50171:rack02:ENG_SFO01_P08:2863311530
  - qredis06.p08.eng.qualys.com:50171:rack02:ENG_SFO01_P08:4294967295
  - qredis03.p08.eng.qualys.com:50171:rack01:ENG_SFO01_P08:2863311530
  - qredis05.p08.eng.qualys.com:50171:rack01:ENG_SFO01_P08:4294967295
  env: network
  listen: 0.0.0.0:50172
  pem_key_file: /opt/qualys/dynomite/certs/dynomite.pem
  rack: rack01
  read_consistency: dc_one
  secure_server_option: datacenter
  server_failure_limit: 3
  server_retry_timeout: 30000
  servers:
  - 127.0.0.1:50180:1
  timeout: 150000
  tokens: 1431655765
  write_consistency: dc_one
```

Should I explicitly set enable_gossip to false and try? Do you think that will solve the issue?

**Comment by balajivenki** [comment]
@ipapapa  and @shailesh33  When I start the server it says in conf dump as gossip is set to false but yet it runs. Here is the log

```
[2017-03-14 20:41:17.826] conf_dump:530 pool in configuration file '/etc/dynomite.yml'
[2017-03-14 20:41:17.826] conf_dump:534 dyn_o_mite
[2017-03-14 20:41:17.826] conf_dump:536   listen: 0.0.0.0:50172
[2017-03-14 20:41:17.826] conf_dump:537   timeout: 150000
[2017-03-14 20:41:17.826] conf_dump:538   backlog: 512
[2017-03-14 20:41:17.826] conf_dump:539   hash: 10
[2017-03-14 20:41:17.826] conf_dump:541   hash_tag: ""
[2017-03-14 20:41:17.826] conf_dump:543   client_connections: 0
[2017-03-14 20:41:17.826] conf_dump:551   data_store: 0 (redis)
[2017-03-14 20:41:17.826] conf_dump:552   preconnect: 1
[2017-03-14 20:41:17.826] conf_dump:553   auto_eject_hosts: 1
[2017-03-14 20:41:17.826] conf_dump:555   server_retry_timeout: 30000 (msec)
[2017-03-14 20:41:17.826] conf_dump:557   server_failure_limit: 3
[2017-03-14 20:41:17.826] conf_dump:559   datastore:
[2017-03-14 20:41:17.826] conf_dump:561     127.0.0.1:50180
[2017-03-14 20:41:17.826] conf_dump:563   dyn_seed_provider: "simple_provider"
[2017-03-14 20:41:17.826] conf_dump:566   dyn_seeds: 5
[2017-03-14 20:41:17.826] conf_dump:569     qredis02.p08.eng.qualys.com:50171:rack02:ENG_SFO01_P08:1431655765
[2017-03-14 20:41:17.826] conf_dump:569     qredis04.p08.eng.qualys.com:50171:rack02:ENG_SFO01_P08:2863311530
[2017-03-14 20:41:17.826] conf_dump:569     qredis06.p08.eng.qualys.com:50171:rack02:ENG_SFO01_P08:4294967295
[2017-03-14 20:41:17.826] conf_dump:569     qredis03.p08.eng.qualys.com:50171:rack01:ENG_SFO01_P08:2863311530
[2017-03-14 20:41:17.826] conf_dump:569     qredis05.p08.eng.qualys.com:50171:rack01:ENG_SFO01_P08:4294967295
[2017-03-14 20:41:17.826] conf_dump:572   env: network
[2017-03-14 20:41:17.826] conf_dump:573   rack: rack01
[2017-03-14 20:41:17.826] conf_dump:574   dc: ENG_SFO01_P08
[2017-03-14 20:41:17.826] conf_dump:577   dyn_listen: 0.0.0.0:50171
[2017-03-14 20:41:17.826] conf_dump:578   dyn_read_timeout: 10000
[2017-03-14 20:41:17.826] conf_dump:579   dyn_write_timeout: 10000
[2017-03-14 20:41:17.826] conf_dump:580   dyn_connections: 100
[2017-03-14 20:41:17.826] conf_dump:582   gos_interval: 30000
[2017-03-14 20:41:17.826] conf_dump:583   conn_msg_rate: 50000
[2017-03-14 20:41:17.826] conf_dump:587   secure_server_option: "datacenter"
[2017-03-14 20:41:17.826] conf_dump:591   read_consistency: "dc_one"
[2017-03-14 20:41:17.826] conf_dump:595   write_consistency: "dc_one"
[2017-03-14 20:41:17.826] conf_dump:597   stats_interval: 30000
[2017-03-14 20:41:17.826] conf_dump:599   stats_listen: 0.0.0.0:22222
[2017-03-14 20:41:17.826] conf_dump:601   enable_gossip: false
[2017-03-14 20:41:17.826] conf_dump:603   mbuf_size: 0
[2017-03-14 20:41:17.826] conf_dump:604   max_msgs: 0
[2017-03-14 20:41:17.826] conf_dump:606   dc: "ENG_SFO01_P08"


[2017-03-14 20:41:47.831] gossip_loop:792 Gossip is running ...
[2017-03-14 20:41:47.852] core_print_peer_status:63 0)0x188dbe0 ENG_SFO01_P08 rack01 0.0.0.0:50171 NORMAL
[2017-03-14 20:41:47.852] core_print_peer_status:63 4)0x188dea0 ENG_SFO01_P08 rack01 qredis03.p08.eng.qualys.com:50171:rack01:ENG_SFO01_P08:2863311530 NORMAL
[2017-03-14 20:41:47.852] core_print_peer_status:63 5)0x188df50 ENG_SFO01_P08 rack01 qredis05.p08.eng.qualys.com:50171:rack01:ENG_SFO01_P08:4294967295 NORMAL
[2017-03-14 20:41:47.852] core_print_peer_status:63 1)0x188dc90 ENG_SFO01_P08 rack02 qredis02.p08.eng.qualys.com:50171:rack02:ENG_SFO01_P08:1431655765 NORMAL
[2017-03-14 20:41:47.852] core_print_peer_status:63 2)0x188dd40 ENG_SFO01_P08 rack02 qredis04.p08.eng.qualys.com:50171:rack02:ENG_SFO01_P08:2863311530 NORMAL
[2017-03-14 20:41:47.852] core_print_peer_status:63 3)0x188ddf0 ENG_SFO01_P08 rack02 qredis06.p08.eng.qualys.com:50171:rack02:ENG_SFO01_P08:4294967295 NORMAL
[2017-03-14 20:41:47.852] _dn_free:305 free(0x1888de0) @ dyn_task.c:106
[2017-03-14 20:42:17.831] gossip_loop:792 Gossip is running ...
```

**Comment by ipapapa** [comment]
It should be disabled by default and this is probably not related. I just read in yours logs and brought it up to play it safe. @shailesh33 made some recent changes on the gossip status if I am not mistaken.

**Comment by balajivenki** [comment]
Hmm, I even manually added enable_gossip: false in the conf but I still see Gossip is running... in the logs, so no way for me to disable it. May be a regression there.

**Comment by shailesh33** [comment]
It could be misleading. the loop is actually talking to Florida.

Balaji,
are you seeing a lot of conenctions on the stats port or peer port?


On Tue, Mar 14, 2017 at 1:57 PM, Balaji Venkatesan <notifications@github.com

**Comment by balajivenki** [comment]
I see constantly 11 connections on the dyn_port(50171) and 1 normally and 4 in one of the instance on the listen port(50172) and 1 or more on the stats port(22222). However this is taken now not while the scan is running.

**Comment by shailesh33** [comment]
@balajivenki  now that its been a day that your nodes are running, can you tell me the situation of the connections again to these ports that you mentioned above?

**Comment by balajivenki** [comment]
@shailesh33  There are nodes down today also(I restarted them yesterday). I have taken the connection count from the node which is down and here is what it is

```
[eng_sfo01_p05 root@qredis03 bvenkatesan]# netstat -tulpn | grep LISTEN
tcp        0      0 0.0.0.0:22222           0.0.0.0:*               LISTEN      19680/dynomite
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      15747/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      6806/master
tcp        0      0 0.0.0.0:50171           0.0.0.0:*               LISTEN      19680/dynomite
tcp        0      0 0.0.0.0:161             0.0.0.0:*               LISTEN      8824/snmpd
tcp        0      0 127.0.0.1:50180         0.0.0.0:*               LISTEN      10659/redis-server
tcp        0      0 127.0.0.1:199           0.0.0.0:*               LISTEN      8824/snmpd
[eng_sfo01_p05 root@qredis03 bvenkatesan]# netstat -anp | grep 50171 | wc -l
11
[eng_sfo01_p05 root@qredis03 bvenkatesan]# netstat -anp | grep 50172 | wc -l
15
[eng_sfo01_p05 root@qredis03 bvenkatesan]# netstat -anp | grep 22222 | wc -l
1
[eng_sfo01_p05 root@qredis03 bvenkatesan]#
[eng_sfo01_p05 root@qredis03 bvenkatesan]# netstat -anp | grep 50171 | grep ESTABLISHED | wc -l
10
[eng_sfo01_p05 root@qredis03 bvenkatesan]# netstat -anp | grep 50172 | grep ESTABLISHED | wc -l
15
[eng_sfo01_p05 root@qredis03 bvenkatesan]# netstat -anp | grep 22222 | grep ESTABLISHED | wc -l
0
```

**Comment by shailesh33** [comment]
Lets chat on gitter.

**Comment by balajivenki** [comment]
Per conversation with @shailesh33 here is the latest failed log

[dynomite.log-20170315-1489600861.txt](https://github.com/Netflix/dynomite/files/845785/dynomite.log-20170315-1489600861.txt)

**Comment by shailesh33** [comment]
I identified the issue with the extra logging in the latest build. Fixing the bug

**Comment by balajivenki** [comment]
@shailesh33 and @ipapapa Unfortunately the issue still exist with the proxy_close_fix branch build. 3 of my nodes went down and here is the log for one node when it went down.

[dynomite.log-20170316-1489676476.txt](https://github.com/Netflix/dynomite/files/848660/dynomite.log-20170316-1489676476.txt)

**Comment by shailesh33** [comment]
checking

**Comment by shailesh33** [comment]
I do not think you have the right code. We have merged it to v0.5.9. You
may want to pull the latest code and rebuild it.

**Comment by balajivenki** [comment]
@shailesh33 we built the code from proxy_close_fix branch yesterday. I can try building the new tag v0.5.9-2_ProxyCloseFix again. Is there anything I can search and confirm after I start to make sure I have the right code? I am guessing you are looking for new log lines you have added earlier.

**Comment by shailesh33** [comment]
yes you should see newer logs around the bad file descriptor. Check the PR

**Comment by balajivenki** [comment]
Thanks @shailesh33  Yes there was a mistake in the build process and we took the wrong code. I have installed the right code on the nodes today. We will know tomorrow if the issue is fixed.

**Comment by ipapapa** [comment]
@balajivenki has this been resolved? Do you still see the issue? Can we close it?

**Comment by balajivenki** [comment]
@ipapapa  and @shailesh33  So far the build seems to be pretty solid. I am running few more scans to make sure everything is right. I will close it on Monday morning if the service runs stable even after few more scans.

**Comment by balajivenki** [comment]
@ipapapa  and @shailesh33  The fix is pretty stable and I have been running it for last few days along with our WAS scans running. I really appreciate you taking time and fixing this for us. Special thanks to @shailesh33 . Closing the issue.
