### ISSUE TITLE
Send Event to client when key in datastore has been written? (similar to redis keyspace events) ?

### ISSUE THREAD

**Issue by jomeier** [Netflix/dynomite#426]
Hi Folks, 

ok: Regarding the docs subscribe/publish from redis is currently not supported. 

Is there some similar notification mechanism like keyspace events a client could subscribe for?

If we would like to implement it: are there any showstoppers for publish/subscribe or keyspace events in dynomite?

Would it be a solution to not subscribe to redis keys through the dynomite proxy but to subscribe directly to the redis datastore behind it?

Greetz,

Josef

**Comment by shailesh33** [comment]
There are folks here at Netflix who needed that, but they went ahead and subscribe to the underlying redis directly. That should also be fairly simple compared to the effort and correctness request to get this done in Dynomite.

**Comment by shailesh33** [comment]
Closing this unless you have more questions.
