### ISSUE TITLE
Getting this error while installing

### ISSUE THREAD

**Issue by sairam546** [Netflix/dynomite#428]
root@redis:/home/sairam/dynomite# autoreconf -fvi
autoreconf2.50: Entering directory `.'
autoreconf2.50: configure.ac: not using Gettext
autoreconf2.50: running: aclocal --force -I m4
autoreconf2.50: configure.ac: tracing
autoreconf2.50: configure.ac: adding subdirectory contrib/yaml-0.1.4 to autoreconf
autoreconf2.50: Entering directory `contrib/yaml-0.1.4'
autoreconf2.50: configure.ac: not using Autoconf
autoreconf2.50: Leaving directory `contrib/yaml-0.1.4'
autoreconf2.50: configure.ac: not using Libtool
autoreconf2.50: running: /usr/bin/autoconf --force
configure.ac:32: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf2.50: /usr/bin/autoconf failed with exit status: 1

**Comment by ipapapa** [comment]
What OS? What version of automake? Check if `gettext-base` and `gettext` packages are installed in your system. Make sure the following packages are there in your system

````
RUN apt-get update && apt-get install -y \
	autoconf \
	build-essential \
	dh-autoreconf \
	git \
	libssl-dev \
	libtool \
	python-software-properties \
	redis-server \
	tcl8.5
````

**Comment by ipapapa** [comment]
@sairam546 I am assuming your question was addressed as there has not been any further activity on this issue. If there is anything else we can assist please reopen the issue or create a new one.
