### ISSUE TITLE
Question: Master branch, tags and configuration management 

### ISSUE THREAD

**Issue by blueelephants** [Netflix/dynomite#429]
Hello,

I have a question conc. your git repository handling.

The readme says "the master branch contains the latest stable version".
...and the master branch works very well  :)

However, I wanted to dockerize Dynomite and because of "software configuration management" purposes I  wanted to configure a "specific version of Dynomite" to be installed in the Docker image
=> simply for better handling of Dynomite upgrades in the future (I want to know which version of Dynomite is running in my container).

I tried to checkout e.g. tag v0.5.8 in my Dockerfile, but I noticed that this version doesn't seem to be "as stable as the master branch" (I ran into some strange replication problems, which only disappeard after I again built the software out of the master branch).

After building from the master branch,  dynomite -V shows me
<pre>
dynomite -V
This is dynomite-v0.5.8-5_HgetallLocalRack-130-g366999a
</pre>

Is there a way you also tag "stable releases" within the git repo which I could use for my use case?
Or do I have to rely on the master branch without any further version information?

Thanks a lot for your help.

**Comment by ipapapa** [comment]
That is a good advice. We recently changed the way we describe stable branches and we have not updated the `Readme.md`. The latest release is marked in the release link: https://github.com/Netflix/dynomite/releases

Hence master branch may not contain the latest that we use in production. Unfortunately, Github does not allow to check out the latest release, so one programmatic way is

````
# Get new tags from the remote
$ git fetch --tags
 
# Get the latest tag name
$ latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
 
# Checkout the latest tag
$ git checkout $latestTag
````

**Comment by ipapapa** [comment]
@shailesh33 It seems the new way (tagging based on versions) creates some confusion on what is the definition of the master branch. Any proposal on how to improve it?

**Comment by blueelephants** [comment]
Thanks for your answer.

So currently, the latest realease is "v0.5.9-2_ProxyCloseFix".

Can I "rely" on your release tags? What I mean is, you are not going to change/delete it in the future - i.e. in case you apply some bugfixes/features you don't modify this tag but always create a new tag?

This would be important for me so to be always able to create the Docker image in a fully reproducable way. So when I configure release "v0.5.9-2_ProxyCloseFix" in the Dockerfile it should always build the very same code. 

I personally have used Driessen's branching/release management model for a while, which served me quite well (although I adjusted/streamlined it a bit). It also uses release tags from which you can e.g. create a branch for hotfixes. As far as I have understood your current git model, is not that far away from his model.

Here is the link to it with a good description: http://nvie.com/posts/a-successful-git-branching-model/
Maybe there are some good additionaln ideas in it for you as well.

**Comment by shailesh33** [comment]
Hi @blueelephants You can rely on the tags that we create. Traditionally I was creating AMIs from master branch dev was unstable. And we were merging dev to master when we wanted to create a new release. But lately we have been changing dynomite code significantly and so we decided to keep master around and start creating release branches. Hot fixes go to release branch as well as dev branch. Every hotfix creates a new tag on the release branch ( previously this was done on master branch). 

We have studied that git flow approach and you are right, the model we have is closer to git flow now than it was before.
