### ISSUE TITLE
Logs are not rotating for dynomite

### ISSUE THREAD

**Issue by amitduapec** [Netflix/dynomite#433]
For us dynomite logs are not rotating. If we delete logs manually or by job, running dynomite does not write logs. Any pointers on what could be issue ?

**Comment by shailesh33** [comment]
I am not sure why that is the case. Does your dynomite process hangs ? can you check if the inode still exists? does dynomite still have open handle to the file?

**Comment by amitduapec** [comment]
Process does not hang. We are deleting files via cron jobs as dynomite is not rotating files.

**Comment by amitduapec** [comment]
Once file is deleted. dynomite is not creating new  file

**Comment by maksimlikharev** [comment]
Yes, we see the same issue, when dynamite runs under somewhat verbose log level, eventually it runs out of disk space, it is fine to disable logs on prod, but on dev, better to have it and in some cases to have even very verbose. This is quite serious problem.

**Comment by shailesh33** [comment]
@maksimlikharev there are various log levels, to debug issues, I go to log level 6 which is good enough for all practical purposes; It shows how the message is received in dynomite, how the copies are made and sent to various nodes.
Each message has a id:parent_id, if a message is received from a client it has a parent_id of 0, then internally we create copies of the message to propagate it in the system and then the copies have parent_id of the original message. That way, I trace the messages in the system.

What is your purpose of verbose log and what level do you keep?

We usually archive the logs every 2 hours but its part of the base system and dynomite itself doesnt have to do anything. let me try quickly deleting the logs on my system.

**Comment by maksimlikharev** [comment]
I didn't mv or del, file is open, this won't work. log needs to be properly rotated by date or size

**Comment by shailesh33** [comment]
I assume the underlying operation would be mv or del or truncate right?

**Comment by maksimlikharev** [comment]
My desire that dynomite will properly rotate logs for me and I will zip/backup/delete as I feel it, this is trivial operation. 
I don't won't to reserve to "black magic" here to rotate opened file by another process.
Good example would be *RollingFileAppender*, at the very minimum rotate log file every day.

Why I need verbose, sometimes I need to investigate errors and it helps to see where the problems is, is it dynomite, is it redis, is it client library, is it network. That's why we run on dev in somewhat verbose  log level, sometimes we run at v11.

**Comment by shailesh33** [comment]
ok. got it. I looked at our script here, and the way it does a rotation is copy the file to archive directory and truncate the source file. So essentially I think dynomite keeps wrting to the same file, just that it gets truncated every 2 hours. Does that make sense?

**Comment by ipapapa** [comment]
This is how we rotate logs (as @shailesh33 described above): https://github.com/Netflix/dynomite/blob/dev/bin/launch_dynomite.sh#L24-L27

**Comment by claudineimatos** [comment]
As far as I can see, if you do move the original file with logorate for example, you may use a kill with signal HUP to start to write the new file:
sudo killall -HUP dynomite
