### ISSUE TITLE
Firewall ports

### ISSUE THREAD

**Issue by slopokeit** [Netflix/dynomite#446]
Great work with the project.  We're in the process of testing this out in a 3 DC environment.

We've been leveraging the Dockerfile in the conf with some tweaks to make it more dynamic in loading in various configs.

That being said we're struggling with getting Dynomite running within Docker's bridge (default) network.  If we run it in the host network all seams file.  It appears as if we need to open up more then ports 8101-8102 for cross dc/rack communication.

If we simply run the container with "-p 8101:8101 -p 8102:8102", the nodes can't communicate with each other.

Can you confirm which ports need to be enabled?  It would be great if there was a new item published in the wiki.

Thanks!

**Comment by shailesh33** [comment]
Hi
8101 is a peer to peer communication port
8102 is the default client port
22122 is the default port on which dynomite talks to underlying redis (not
outside the node)
22222 is the default stats control port

What is the issue that you see?

**Comment by slopokeit** [comment]
My issue appears to be the same as described in #441.  I can only get a multi node cluster running if the container is running as --network=host

The only thing I could could come up with is that the inter-cluster communication relied on some other port other then 8101-8102
