### ISSUE TITLE
Unable to install dynomitedb from apt

### ISSUE THREAD

**Issue by sairam546** [Netflix/dynomite#450]
# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys FB3291D9

sudo add-apt-repository "deb https://apt.dynomitedb.com/ trusty main"

sudo apt-get update
it is stopping at this point as it is unable to talk with dynamite apt.

Please resolve this issue fastly.

**Comment by shailesh33** [comment]
@akbarahmed can you comment please? 

@sairam546 we usually do not use this process in production, we build our own debians and install them.

**Comment by akbarahmed** [comment]
@sairam546 The .deb build and the packages on the apt repo were very out of date. As a result, we took the apt repo down.

We're now pointing everyone to the Netflix repo: https://github.com/Netflix/dynomite

I have updated the README on https://github.com/DynomiteDB/DynomiteDB.github.io and will update it on the other repos, website etc.

**Comment by sairam546** [comment]
It is easy for beginners to install using apt. Can you enable that back with some versioning or with some different URL.

**Comment by ipapapa** [comment]
Right now we do not have in our timeline as an OSS project to publish a debian. We may consider it later based on the need. There was an effort in the past https://github.com/Netflix/dynomite/issues/367 and as an OSS project, it would be great to get more people involved.

**Comment by ipapapa** [comment]
@sairam546 Currently, we do not plan to address it as project maintainers given the fact that at Netflix we build our own Debians. We would love though to support you or anybody else who plans to help with publishing Debian package.
