### ISSUE TITLE
easy scenario to run DynomiteDB on Kubernetes .

### ISSUE THREAD

**Issue by omilun** [Netflix/dynomite#455]
hello . 
I have 3 servers in a data center, and I want to set up DynomiteDB and ARDB on Kubernetes.
I have a problem in setting dynomite.yaml file for all of them.
I want to divide my problem and run DynomiteDB step by step.
First: I need to run DynomiteDB and Redis by docker. I think I can make it easy by using felorida config to same setup on kubernetes.
how can I run it with Docker? I cannot find any example or scenario that can help me get it to work.
can anyone give me a solution or scenario to run DynomiteDB this way?

**Comment by ipapapa** [comment]
Let me start by clarifying. DynomiteDB is the commercial product, for which @akbarahmed can provide more insights. 

If you want to use Dynomite in Docker here is a Dockerfile here are some instructions: https://github.com/Netflix/dynomite/tree/dev/docker
and you can also use the Docker image from Docker hub:
 https://hub.docker.com/r/ipapapa/dynomitedocker/

**Comment by ipapapa** [comment]
@omilun was your question answered? Would you like any further assistance from our side?
