### ISSUE TITLE
Documentation of deploying dynomite cluster on AWS

### ISSUE THREAD

**Issue by sk523** [Netflix/dynomite#458]
We are trying to use Netflix conductor in our project but did n't find any documentation on  deploying  dynomite cluster on aws with production HA settings. Can you please provide steps to deploy?

**Comment by ipapapa** [comment]
Here it is: https://github.com/Netflix/dynomite-manager/wiki/Step-by-step-installation

**Comment by shailesh33** [comment]
I hope this is answered. Please reopen the issue if you have further follow up questions
