### ISSUE TITLE
Dynomite is taking very high memory

### ISSUE THREAD

**Issue by sairambs3** [Netflix/dynomite#461]
Seems like mbuf is taking the memory and not freeing it. If i reload dynomite that memory is getting released and it is becoming normal.

Can i know how mbuf works and how to free memory ?

**Comment by shailesh33** [comment]
Hi 
That is by design to have memory allocated and not freed to avoid fragmentation and also to avoid frequent allocation and deallocation. Currently we do not free that memory.

**Comment by sairambs3** [comment]
Can we limit the memory ?

**Comment by shailesh33** [comment]
there is a command line option for logs.
There is also a command line or yaml option for max messages. This will limit the memory indirectly. It limits the messages not the buffers in it. But you can imply from it.
Also dynomite has a stats port that you specify on the command line or yaml file (based on the version) where you can send query like http://localhost:<stats port>/info and get a lot of statistics.

**Comment by shailesh33** [comment]
@sairambs3 please reopen the issue if you have further questions.
