### ISSUE TITLE
Question: consistency guarantee during the cluster partitioning

### ISSUE THREAD

**Issue by yazovsky** [Netflix/dynomite#463]
Hello here!

Let's assume I have "Record A" saved in DynomiteDB cluster. Now, I got network partitioning, which splits my cluster into two parts: part A (with "Record A" and all replicas) and part B (no replicas of "Record A").

During partitioning, my client application has an access to only part B, thus, the "Record B" is unavailable.

Now, I'm trying to check if "Record A" exists and create if it doesn't exists yet. Aerospike (in AP mode) in this case would perform a master selection and allow me to write a new record. And when the cluster re-join again - it would merge duplicate records. Which is not optimal is my case. See details in this nice article - https://aphyr.com/posts/324-jepsen-aerospike

How would Dynomite behave in this scenario? Is it possible to fail read/write request if there is no quorum of replicas available due to network partitioning? That would be ideal for me.

Thank you in advance!

**Comment by shailesh33** [comment]
Yes, in that case part of the data is not available and Dynomite will complain and read/write will fail.

**Comment by yazovsky** [comment]
thanks, @shailesh33 

Just to double check we are talking about the same thing here. I found the following description of Dyno's behavior in another thread:

_>> When a node leaves the cluster (ex. when it fails), the Dyno client will be notified of the failure due to failed health checks and will direct traffic away from the failed node...until it is brought back online._

Does **"will direct traffic away from the failed node"** means that:
a) Dyno would start using less nodes that configured as replication factor (for instance, I had RF=3, after 1 node went down, Dyno sends requests to 2 nodes only, thus, QUORUM requests would still succeed, but ALL requests would fail)

or 

b) Dyno would select different node from available to replace failed node and would keep writing/reading data from 2 old nodes + 1 new node. (by the way, in this case, I wonder if data will be rebalances to newly selected node for keys that were stored on failed node).

Thanks in advance.

**Comment by shailesh33** [comment]
option a is correct. However its not dyno which replicates the data, its dynomite server which does it for you. Client do not have to write to multiple nodes, that why you can use any client, even a basic redis-cli to talk to dynomite.

**Comment by yazovsky** [comment]
thanks a lot!
