### ISSUE TITLE
Error Install dynomite in Ubuntu

### ISSUE THREAD

**Issue by marciogoulart** [Netflix/dynomite#466]
When executed sudo apt-get update occured error below.

sudo apt-get update
Err:26 https://apt.dynomitedb.com trusty InRelease
  Connection timed out after 120003 milliseconds

**Comment by shailesh33** [comment]
DynomiteDB was a commercial product by @akbarahmed that is no longer supported. Please use the open source version in this git repo to build and install.

Closing this issue for now. Let us know if you have issues with the git repo
