### ISSUE TITLE
Latency increases by message size

### ISSUE THREAD

**Issue by balajivenki** [Netflix/dynomite#468]
Hi,

We have been seeing latency issues when writing or doing GET/DEL calls to dynomite/redis. The interesting thing we observed was that the latency increases proportionate to the size of the message. Can you please tell me other than network check is there any config we are using wrong? There are not much doc about mbuf_size config for dynomite. does increasing mbuf_size helps here?

**Comment by shailesh33** [comment]
what is teh message size that you are sending? Typically in this case, we increase the mbuf size but that wont help significantly. We also try to use dyno compression feature if the payload is compressable.

**Comment by shailesh33** [comment]
@balajivenki let me know if you tried dyno compression or app side compression, what is your typical payload size?

**Comment by shailesh33** [comment]
@balajivenki is there anything on our side that needs to be done, if not can you please close the issue?

**Comment by balajivenki** [comment]
@shailesh33  This issue was due to that RetryNTime infinite loop issue. Marking it as closed as commenting out the retry policy worked for us. Thanks for your help
