### ISSUE TITLE
Dynomite installtion failed on Linux Suse 12

### ISSUE THREAD

**Issue by noubough** [Netflix/dynomite#469]
Hi,
I tried to install dynomite from source as described here 

[](tps://github.com/Netflix/dynomite/blob/master/README.md) but failed due to Connection issue, I cloned the git repo with eclipse , zipped it and copies via winscp to my Linux suse  VM.

Finally  i executed following:

```
$ cd dynomite
$ autoreconf -fvi
$ ./configure --enable-debug=yes$ make
But make give me following error:

```
 

>  from dyn_hashkit.c:1:
> ../../src/dyn_crypto.h:14:25: fatal error: openssl/bio.h: No such file or directory
>  #include <openssl/bio.h>
>                          ^
> compilation terminated.
> Makefile:380: recipe for target 'dyn_hashkit.o' failed
> make[3]: *** [dyn_hashkit.o] Error 1
> make[3]: Leaving directory '/tmp/dynomite/src/hashkit'
> Makefile:677: recipe for target 'all-recursive' failed
> make[2]: *** [all-recursive] Error 1
> make[2]: Leaving directory '/tmp/dynomite/src'
> Makefile:471: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/tmp/dynomite'
> Makefile:359: recipe for target 'all' failed
> make: *** [all] Error 2
> 

Note: the same error occured  when i tried to install using the release  dynomite-0.5.9-2_ProxyCloseFix.tar.gz
Please help me building th dynomite Framework. I am newbie.

Thanks in Advance

**Comment by shailesh33** [comment]
I think you need to install libtool and libssl-dev

sudo apt-get install libssl-dev

**Comment by noubough** [comment]
Hi shailesh33,

thank you. Exactly I'v installed openssl-devel and this has solved my issue.
