### ISSUE TITLE
Support ring describe cmd

### ISSUE THREAD

**Issue by timiblossom** [Netflix/dynomite#47]
This is one of the admin commands that must be available as soon as possible.  This cmd is similar to cassandra's nodetool ring cmd.

**Comment by mfouilleul** [comment]
Is there an update on the stats commands? Only the /info works:

root@redis1:~# curl http://192.168.33.20:22222/ping
curl: (52) Empty reply from server
root@redis1:~# curl http://192.168.33.20:22222/describe
curl: (52) Empty reply from server

Max.

**Comment by timiblossom** [comment]
For ping, you can just call PING directly on the Dynomite's client port, not that port.

For cluster describe, we will have it soon.

**Comment by mfouilleul** [comment]
Do you have some fresh news on this issue?

**Comment by timiblossom** [comment]
We are working on two urgent issues so we have to finish those before doing
this.  We will have more man powers very soon too.  In the mean time, if
your cluster is small, you can use a script to ping each node in the ring
for health check.

**Comment by ipapapa** [comment]
@mfouilleul cluster_describe was added last year on Dynomite and is returning a JSON object. For more information about check out the admin port commands: https://github.com/Netflix/dynomite/wiki/REST
