### ISSUE TITLE
Dynomite CPU usage is increased and it stopped responding

### ISSUE THREAD

**Issue by sairambs3** [Netflix/dynomite#475]
Hi

Suddenly Dynomite CPU increased and it stopped responding to requests.
When i reload it is again working normally.

What might be the issue ?

Also when i tried to enable logs with command line. I am getting following error

??:0
/tmp/dynomite/src/dyn_stats.c:1401
/tmp/dynomite/src/dyn_stats.c:1556
/tmp/dynomite/src/dyn_core.c:232
/tmp/dynomite/src/dyn_core.c:244
/tmp/dynomite/src/dyn_core.c:287
/tmp/dynomite/src/dyn_core.c:320
/tmp/dynomite/src/dynomite.c:578
/tmp/dynomite/src/dynomite.c:652
??:0
??:?
Segmentation fault (core dumped)

I built the dynomite from v0.5.9 branch

Please help me to resolve issue.

**Comment by shailesh33** [comment]
can you send me some more details of the load, anything in the logs etc?

**Comment by mkumar87** [comment]
I have seen similar issue too.. We see a increase in CPU ~90% and CPU usage to 5000MHz and the VM crashes.

I dont see any suspicious logs, but below are the server logs i saw just before the VM crash :

Sep  6 22:16:15  nm-dispatcher: Dispatching action 'dhcp4-change' for ens192

Sep  6 22:16:15  systemd: Started Network Manager Script Dispatcher Service.

Sep  6 22:16:15  dbus-daemon: dbus[6062]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'

Sep  6 22:16:15  dbus[6062]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'

Sep  6 22:16:15  systemd: Starting Network Manager Script Dispatcher Service...

Sep  6 22:16:15  dbus-daemon: dbus[6062]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'

Sep  6 22:16:15  dbus[6062]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'

Sep  6 22:16:15  dhclient[32246]: bound to 96.115.36.76 -- renewal in 299 seconds.

Sep  6 22:16:15  NetworkManager[6072]: <info>  (ens192): DHCPv4 state changed bound -> bound
