### ISSUE TITLE
Dynomite with docker causing huge decrease in read-write speed

### ISSUE THREAD

**Issue by codophobia** [Netflix/dynomite#477]
I am thinking of using dynomite for geo replication of redis data. I was just benchmarking the dynomite with redis on a single node and I found it to be too slow. I have seen very good benchmarking results of dynomite with redis . I don't understand why my dynomite is too slow.

Node hardware details:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 6
Model name:            QEMU Virtual CPU version 2.0.0
Stepping:              3
CPU MHz:               2666.760
BogoMIPS:              5333.52
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0-7
Flags:                 fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 ht syscall nx lm rep_good nopl eagerfpu pni vmx cx16 x2apic popcnt hypervisor lahf_lm tpr_shadow vnmi flexpriority ept vpid
```
I am using the the [redis_single.yml](https://github.com/Netflix/dynomite/blob/master/conf/redis_single.yml) conf file which is used with docker. 
```
dyn_o_mite:
  dyn_listen: 127.0.0.1:8101
  data_store: 0
  listen: 127.0.0.1:8102
  dyn_seed_provider: simple_provider 
  servers:
  - 127.0.0.1:22122:1
  tokens: 437425602
```
I first ran benchmarking directly on the redis server at port 22122.
`redis-benchmark -h 172.20.22.100 -q -t set,get -c 100 -p 22122`
Result:
```
SET: 32071.84 requests per second
GET: 25859.84 requests per second
```
Then, i ran benchmarking on dynomite layer on port 8102 and got very bad results.
`redis-benchmark -h 172.20.22.100 -q -t set,get, -c 100 -p 8102`
```
SET: 1024.68 requests per second
GET: 978.14 requests per second
```
What could be the possible reason for my dynomite being too slow?

**Comment by shailesh33** [comment]
This is what I get with my virtual machine:
sbirari@ubuntu:~/Work/dynomite (dev)*$ redis-benchmark -q -t set,get -c 100 -p 8102
SET: 60532.69 requests per second
GET: 62421.97 requests per second

sbirari@ubuntu:~/Work/dynomite (dev)*$ redis-benchmark -q -t set,get -c 100 -p 22122
SET: 129701.68 requests per second
GET: 119617.22 requests per second

**Comment by codophobia** [comment]
@shailesh33 Are you using docker to run dynomite? What could be possible reasons for so slow performance?

**Comment by shailesh33** [comment]
No we dont use docker. But I just ran in inside a VM.  Try it without a docker and see if that helps?

**Comment by codophobia** [comment]
@shailesh33 ya, it helped. So, the problem was with the docker. 
```
redis-benchmark -q -t set,get -c 100 -h 127.0.0.1 -p 22122
SET: 89206.06 requests per second
GET: 88967.98 requests per second
```

```
redis-benchmark -q -t set,get -c 100 -h 127.0.0.1 -p 8102
SET: 42716.79 requests per second
GET: 43066.32 requests per second
```
The performance drop is almost 50% with just one node. Is this much drop normal by using dynomite?

**Comment by shailesh33** [comment]
that's what I see it on my machine too. I would guess Dynomite does the same parsing etc that Redis does. Other than that, Redis does a little extra work of setting data in memory which is not significantly costly. You could get a better performance with Unix sockets. If Redis supported binary protocol too, it would perform much better.

**Comment by shailesh33** [comment]
Please feel free to reopen the issue if you have any more questions,

**Comment by codophobia** [comment]
@shailesh33 When I compiled the  dynomite code on ubuntu, it worked fine. But I am facing problem when I am trying to run make command  on debian stretch. I followed the Dockerfile in the master repo for installing the dependencies. 
```
apt-get install -y \
	autoconf \
	build-essential \
	dh-autoreconf \
	git \
	libssl-dev \
	libtool \
	python-software-properties \
	redis-server \
	tcl8.5
```
The first three commands for compiling worked fine but I got error when I ran the make command.
```
$ git clone git@github.com:Netflix/dynomite.git -b master
$ cd dynomite
$ autoreconf -fvi
$ CFLAGS="-ggdb3 -O0" ./configure --enable-debug=full
$ make
$ sudo make install
```
```
Makefile:621: recipe for target 'dyn_crypto.o' failed
make[3]: *** [dyn_crypto.o] Error 1
make[3]: Leaving directory '/home/admin/dynomite/src'
Makefile:668: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/admin/dynomite/src'
Makefile:483: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/admin/dynomite'
Makefile:372: recipe for target 'all' failed
make: *** [all] Error 2
```

I tried to look at line number 621 in the Makefile but could not make any sense of it.
```
@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
615           if test "$$subdir" = .; then :; else \
616             $(am__make_dryrun) \
617               || test -d "$(distdir)/$$subdir" \
618               || $(MKDIR_P) "$(distdir)/$$subdir" \
619               || exit 1; \
620             dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
621             $(am__relativize); \
622             new_distdir=$$reldir; \
623             dir1=$$subdir; dir2="$(top_distdir)"; \
624             $(am__relativize); \
625             new_top_distdir=$$reldir; \
626             echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
627             echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
628             ($(am__cd) $$subdir && \
629               $(MAKE) $(AM_MAKEFLAGS) \
630                 top_distdir="$$new_top_distdir" \
631                 distdir="$$new_distdir" \
632                 am__remove_distdir=: \
633                 am__skip_length_check=: \
634                 am__skip_mode_fix=: \
635                 distdir) \
636               || exit 1; \
637           fi; \
                                                                                                                                     637,1-8       69%
636               || exit 1; \
637           fi; \
638         done
```

**Comment by wkruse** [comment]
The compile error is related to #414, change `libssl-dev` (OpenSSL **1.1.x**) to `libssl1.0-dev` (OpenSSL **1.0.x**).

**Comment by nikitinvasily** [comment]
@codophobia to speedup dynomite in docker you need decrease log level in startup.sh to 5 or below (-v11 => -v5)
