### ISSUE TITLE
Usage of memory by dynomite increases - ENOTRECOVERABLE

### ISSUE THREAD

**Issue by sairambs3** [Netflix/dynomite#478]
[2017-09-19 00:32:42.892] msg_send:1266 <LOCAL_PEER_SERVER 0x28dd250 163 to '10.2.19.35:8101:rack1:dc1:0'> Setting ENOTRECOVERABLE happens here!

Like this i am getting logs continuously and memory usage of dynomite is increasing. What is this ?

What is MAX_CONN_QUEUE_SIZE in dyn_connection.h

Thank you

**Comment by shailesh33** [comment]
It tries to put a limit on the outstanding messages to be sent to a peer. If you are getting this, mostly the storage is slow or you are pumping too much queries to the cluster. In such case we recommend scaling the cluster appropriately.
