### ISSUE TITLE
dynomite instance crash when using binary data ?

### ISSUE THREAD

**Issue by daflip** [Netflix/dynomite#480]
Hi 

I've been investigating several issues I've been having with dynomite whilst running some tests to see if this is going to work in production. One thing I've noticed is I made a simple PHP script which reads random binary data and attempts to set value via dynomite and if successful then reads it back and compares what it got back equals what it set. Running the script causes a 'read error on connection' usually before it gets to writing 200,000 chars. Once this read error occurs ALL subsequent connections to dynomite hang.

```
<?php
$r = new Redis;
$i = 0;
$s = '';
$r->connect("localhost", 8101, 2, null,500);
while ($i < 400000) {
  $i+=1024;
  $s .= openssl_random_pseudo_bytes(1024);
  echo "$i\n";
  if ($r->set("test", $s)) {
    $ss = $r->get("test");                                                                                                                                                        
    if (md5($ss) != md5($s)) {
      throw new exception("mismatch error");
    }   
  } else {
    throw new exception("failed to set");
  }
}
```

Running this same script against an actual redis instance yields zero problems.

Can you help?

**Comment by shailesh33** [comment]
Will look into it.

**Comment by daflip** [comment]
Let me know if I can be of any assistance. For the record I'm using v0.5.9 .. issue happens on redis 3.0.7 and also 3.2.6. My test uses php-redis 3.1.1-1 on debian stretch (stable)

**Comment by daflip** [comment]
FWIW the disable flush branch actually fixes this issue too.. that flushing code which was added to core_loop inside dyn_core.c is buggy **for sure**! 

The disable flush branch also fixes issues for me whereby I experienced connection hangs when requesting keys which contained larger amounts of data (>16KB) - the server would simply stop sending the full contents of the key and so the client would hang since it remains waiting for the full packet --
 which never gets sent because that flushing code just removes the client without actually flushing the data.  I've only just started digging in to this code and I'm not a c programmer but from what I can make out currently the core issue is that the flushing code is either triggering on connections which it should not be triggering on it (i.e. it needs to check more than just status == DN_OK) or the flushing code is not actually triggering a flush of the remaining buffer at all and instead it just deletes the connection.  It seems you won't experience this bug if you're communicating from localhost to localhost presumably because the packets send so fast the bug is masked -- it only happens if you're going across a network and with larger packets (>16kb) .

It seems like the connection flushing which was added to core_loop is safe to use in production since the connection still gets hit with event_del_out in my tests.. and comparing to v0.5.8 that previous version didn't use that connection flushing code at all.

If you can shed any further light on all of this I'd gladly help with trying to resolve it and move forward !

**Comment by shailesh33** [comment]
Let me grab your php script. Why are you connecting to 8101? is that the port you listen to?

**Comment by daflip** [comment]
haha yes that's the port I'm using -  sorry, that's a little confusing!  I started off using a config I found somewhere and which had the ports swapped around so my listen port is 8101 rather than 8102 :D

**Comment by shailesh33** [comment]
I am trying to get that PHP script running, for me, it starts with installing PHP. Traditionally new installations are never a breeze for me, so struggling with this "class Redis not found"

**Comment by daflip** [comment]
what OS are you using ? if you're using ubuntu or debian then install the php-redis package -- it's a php redis extension which is required for redis comms.

**Comment by daflip** [comment]
https://github.com/phpredis/phpredis#installingconfiguring

**Comment by shailesh33** [comment]
tried that. Still, it fails with class Redis not found. I might rewrite the script in python

**Comment by shailesh33** [comment]
ok. I have it all set. So you are seeing the script hang? for me, it goes all the way down to 400384 and then finishes. You mentioned about Redis and Dynomite being on the same node or not. what is the case with you?

**Comment by daflip** [comment]
I experienced two issues. One was for larger values stored in keys the connection would hang when trying to read it remotely. The other issue was my script above which wrote random data to a key and then verified it was retrieved & written correctly would throw a read connection error and then the dynomite instance would hang. 

Both of these issues are solved by using the disable flush branch !

**Comment by shailesh33** [comment]
hmm. ok. Can you grab the latest from v0.5.9, I have merged the disable_flush branch.

**Comment by daflip** [comment]
the latest v0.5.9 fixes it
