### ISSUE TITLE
Dev branch build broken on Alpine 3.6

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [Netflix/dynomite#500]
Musl does not support glibc’s custom format specifier registration system:
```log_register_custom_specifier('M', print_obj, print_obj_arginfo);```
Not so clear why has been made decision to use glibc specific feature for dev branch that breaks compatibility with musl. There are no rocket science to implement log functions without using custom specifier %M - BTW master branch has no %M and works fine.

**Comment by shailesh33** [comment]
I am open to ideas to not use %M. Please educate me.

**Comment by UladzimirTrehubenka** [comment]
Approach #1 - revert back log_info(), log_debug() etc from master branch (and remove printf.h dependency).
For example:
```log_error("%M Failed to add %M to event loop: %s", p, c, strerror(errno));```
transformed into:
```log_error("%s %d Failed to add %s %d to event loop: %s", conn_get_type_string(p), p->sd, conn_get_type_string(c), c->sd, strerror(errno));```

Approach #2 - implement function toString() for each object that uses %M specifier.
For example:
```log_error("%M Failed to add %M to event loop: %s", p, c, strerror(errno));```
transformed into:
```log_error("%s Failed to add %s to event loop: %s", toString(p), toString(c), strerror(errno));```
```
char* toString(struct pool *p) {
static char buffer[255];
snprintf(buffer, sizeof(buffer), "%s %d", conn_get_type_string(p), p->sd);
return buffer;
}

char* toString(struct conn *c) {
static char buffer[255];
snprintf(buffer, sizeof(buffer), "%s %d", conn_get_type_string(c), c->sd);
return buffer;
}
```

**Comment by shailesh33** [comment]
I am curious how will this work. This is overloading/polymorphism. How does this work in C

**Comment by UladzimirTrehubenka** [comment]
My bad (this is C not C++) - so another one approach (actually you have separate print function for each object - so just need rewrite it to return string instead write to stream)

**dyn_types.c**
```
struct object;
typedef int (*func_print_t)(FILE *stream, const struct object *obj);
typedef struct object {
    uint16_t    magic;
    object_type_t type;
    func_print_t func_print;
}object_t;
```
replaced with
```
#define PRINT_BUF_SIZE 255

struct object;
typedef char* (*func_print_t)(const struct object *obj);
typedef struct object {
    uint16_t    magic;
    object_type_t type;
    func_print_t func_print;
    char print_buff[PRINT_BUF_SIZE];
}object_t;
```
**dyn_message.c**
```
static int
print_req(FILE *stream, const struct object *obj)
{
    ASSERT(obj->type == OBJ_REQ);
    struct msg *req = (struct msg *)obj;
    struct string *req_type = msg_type_string(req->type);
    return fprintf(stream, "<REQ %p %lu:%lu::%lu %.*s, len:%u>", req, req->id, req->parent_id,
                   req->frag_id, req_type->len, req_type->data, req->mlen);
}
```
replaced with

```
static char*
print_req(const struct object *obj)
{
    ASSERT(obj->type == OBJ_REQ);
    struct msg *req = (struct msg *)obj;
    struct string *req_type = msg_type_string(req->type);
    snprintf(obj->print_buff, PRINT_BUF_SIZE, "<REQ %p %lu:%lu::%lu %.*s, len:%u>", req, req->id, req->parent_id,
                   req->frag_id, req_type->len, req_type->data, req->mlen);
    return obj->print_buff;
}
```
**dyn_client.c**
```
log_info("%M FORWARD %M to storage conn %M", c_conn, req, s_conn);
```
replaced with
```
log_info("%s FORWARD %s to storage conn %s", (struct object *)c_conn->func_print(), (struct object *)req->func_print(), (struct object *)s_conn->func_print());
```

**Comment by shailesh33** [comment]
I am worried about the bloating of structure size this will cause. Is there any other way you can suggest? The current approach is very code-friendly and would hate to see it go.

**Comment by UladzimirTrehubenka** [comment]
You could use pointer (and malloc) instead array to avoid growing structure size.

**Comment by UladzimirTrehubenka** [comment]
Created https://github.com/Netflix/dynomite/pull/514

**Comment by UladzimirTrehubenka** [comment]
Created https://github.com/Netflix/dynomite/pull/515 - Back port logging from dev to v0.5.9

**Comment by shailesh33** [comment]
Good to close?

**Comment by UladzimirTrehubenka** [comment]
I am Ok, you can close the issue.
