### ISSUE TITLE
Documentation YML conf files not found (404)

### ISSUE THREAD

**Issue by syberkitten** [Netflix/dynomite#502]
The YAML configuration files described here as (examples) are missing:
https://github.com/Netflix/dynomite/wiki/Getting+Started#a-one-node-cluster

https://github.com/Netflix/dynomite/wiki/Getting+Started#b-two-nodes-cluster-in-one-datacenter-with-2-racks

https://github.com/Netflix/dynomite/wiki/Getting+Started#d-6-node-cluster-in-one-datacenter-with-3-racks-each-having-2-nodes

**Comment by syberkitten** [comment]
How can i see proper examples of connecting between two data centers?

**Comment by ipapapa** [comment]
This one shows two DCs: https://github.com/Netflix/dynomite/blob/dev/conf/redis_dc1.yml All conf files can be found: https://github.com/Netflix/dynomite/tree/dev/conf

**Comment by ipapapa** [comment]
I also fixed the links in the wiki. If you have any more questions please do not hesitate to reach out.
