### ISSUE TITLE
What is the best practice to add nodes and rebalance data without dyno?

### ISSUE THREAD

**Issue by tinoji** [Netflix/dynomite#507]
I want to scale out/in the rack and read issues: #69, #173, #116, #357 etc.
#357 says the "dual write" is available by client side (dyno), but I don't use dyno. Are there any other ways to perform dual write?

Or need to redis dump and restore manually? In that case, data may needs to be rebalanced in the new rack. Can gossip mode and dynomite manager(#69) reallocate tokens and rebalance data dynamically?

Thanks

**Comment by ipapapa** [comment]
Yes, you can take a Redis dump and restore it manually. You can even create a new cluster with twice the capacity and set the new nodes in Redis master-slave (2 slave nodes to 1 master node). Once the data are in sync, you can switch the traffic and start deleting the non-usable data with a background script (script checks the tokens and if the key does not belong to the node it deletes it). Alternatively, you can implement a reconciliation process. Alternatively, you can use Dyno dual-writer. There are so many options.

In regards to Dynomite-manager: You can have any topology you like and with Dynomite-Manager you can even change it alive. Dynomite-manager will provide the seeds to Dynomite that you want.

**Comment by tinoji** [comment]
You mean I can realize it by only 2 steps?:
1. create a new cluster and start it with enabling gossip.
1. make the new nodes slaves by redis-cli.

**Comment by ipapapa** [comment]
This should be probably contain some information: https://github.com/Netflix/dynomite-manager/wiki/Cold-Bootstraping

**Comment by tinoji** [comment]
Thanks. You can close this issue.
