### ISSUE TITLE
Configure Unix socket for Dynomite

### ISSUE THREAD

**Issue by mitsus** [Netflix/dynomite#508]
Hi,
before using Dynomite i configured Redis for listen incoming connections using Unix Sockets in this mode:
`
unixsocket "/var/run/redis_6380.sock"
unixsocketperm 755`

Is it possible to do this with Dynomite? So is possible to listed dynomite using also Unix Sockets?
Thanks and Best regards

**Comment by shailesh33** [comment]
yes you can. Please use the appropriate path in the servers list. 
Also use v0.6 branch or tag v0.6.0.
Please let me know if you see issues with Unix usage

**Comment by shailesh33** [comment]
@mitsus any update?

**Comment by mitsus** [comment]
Hi @shailesh33 ,
I tried to found the appropriate path in the server list but I did not succeed. In redis I configure it into conf file...with dynomite?
Thanks

**Comment by shailesh33** [comment]
with Dynomite also you need to tell that exact path in the servers's
configuration section in the conf for Dynomite.

**Comment by sobkovych** [comment]
Hi @shailesh33 ,
I suppose the question was if Dynomite able to use Unix socket as "listen" parameter for client connections (instead of TCP connection on port 8102). As result, if Redis also configured to use Unix Domain socket, the connection chain will look like:
  `client <--(Unix socket)--> Dynomite <--(Unix socket)--> Redis`
Regards

**Comment by shailesh33** [comment]
I believe it should work. have you given it a try? What is the use case that you will have dynomite on unix port? I believe the gossip portion will need to change.

**Comment by sobkovych** [comment]
@shailesh33 
You're right, unix sockets work in both cases I mentioned in my previous comment! Thanks!
