### ISSUE TITLE
What would happen when DataCenter1 crash and reover?

### ISSUE THREAD

**Issue by springside** [Netflix/dynomite#51]
step 1. Do i need to sync-up the data from Data Center 2 use the "SLAVEOF" command to full sync-up the data for each shard? 

steop2. and then i need to stop the "SLAVEOF" and swith to master at some time? 

step3. and then the Dynomite will start to replicate data to it?

How to ensure no data lost between step2 and step3.

**Comment by mfouilleul** [comment]
Just come back on that subject.

Ok for "the server does not return any byte", but does it do something? 

My node is accepting queries
```
root@redis1:~# redis-cli -p 8102
127.0.0.1:8102> ping
PONG
127.0.0.1:8102> set 1 OK
OK
127.0.0.1:8102> get 1
"OK"
```

I call standy to "force the dynomite node to not process any read/write from clients or peers"
```
root@redis1:~# curl 'http://localhost:22222/standby'
curl: (52) Empty reply from server
```

My node is still accepting queries
```
root@redis1:~# redis-cli -p 8102
127.0.0.1:8102> ping
PONG
127.0.0.1:8102> set 1 OK
OK
127.0.0.1:8102> get 1
"OK"
```

Is it normal?

Best Regards, 

Max.

**Comment by ipapapa** [comment]
We have open sourced Dynomite-manager with the warm up process. It is well documented now in the [wiki](https://github.com/Netflix/dynomite-manager/wiki/Cold-Bootstraping)
