### ISSUE TITLE
Support for ZRANGEBYLEX command in SortedSet.

### ISSUE THREAD

**Issue by srikanthm-1** [Netflix/dynomite#511]
Hi
Is there a plan to support ZRANGEBYLEX and ZREVRANGEBYLEX command in SortedSet? I am not able to find any specific concerns regarding this command (like the operation spanning across multiple server etc.) which would cause Dynomite to fail here.

**Comment by shailesh33** [comment]
Seriously, no reason for not adding. Do you want to create a PR?

**Comment by srikanthm-1** [comment]
Cool! Yeah, I can create a PR.
Thanks!

**Comment by srikanthm-1** [comment]
Hey! Thanks for merging the [PR](https://github.com/Netflix/dynomite/pull/513). Any idea when this would be merged in to master branch? 
Also, I am submitting another PR to support these operations in the DynoJedisClient. Hope thats okay.

**Comment by shailesh33** [comment]
yes completely ok. Really appreciate all Open source contributions.
For Dynomite we have taken the approach of branch per version. The latest we are running in prod is the v0.5.9 branch. The next we are targetting to upgrade to is v0.6.

**Comment by srikanthm-1** [comment]
Thanks! I am currently using the v0.6 branch actually. Will these changes be available in the next version or be merged in to v0.6?

**Comment by shailesh33** [comment]
I have created a new pre-release on v0.6 with tag v0.6.2. Please use that
branch and let me know if you see any issues.
