### ISSUE TITLE
redic-cli monitor doesn't work

### ISSUE THREAD

**Issue by mitsus** [Netflix/dynomite#512]
Hi all,
if I try to launch in redis-cli (on dynomite port) "monitor" command it doesn't work and it exit from redis-cli.
Why? How can i do for start "monitor" command?
`
#redis-cli -p 9379
127.0.0.1:9379> monitor
#
`

**Comment by shailesh33** [comment]
You cannot. Monitor command is not supported by Dynomite

**Comment by shailesh33** [comment]
Please reopen if you have further questions
