### ISSUE TITLE
Quorum Reads not working for Redis Hash

### ISSUE THREAD

**Issue by srikanthm-1** [Netflix/dynomite#518]
Hi,
I am using v0.6.2 and in that version I am not seeing quorum reads working for redis Hash. My setup is a single DC, 3 racks with consistency set to dc_quorum for both reads and writes to all the nodes. 

Assuming the Dynomite instances are D1, D2, D3 backed by redis instance R1, R2 and R3 respectively, rhis is how I am reproducing the issue..
I am adding a Hash directly to redis instance R2 and R3.
_HMSET myhash field1 "Hello" field2 "Hi"_

After this, the hash exist only in R2 and R3 but not in R1. So a quorum read should return that hash, but interestingly the hash is returned only from D2 and D3 and not from D1. DC_SAFE_QUORUM has the same behavior as well.

I am using the following command to perform read on the hash
_hgetall myhash_

P.S. I tried the same experiment above for a basic KV set and get and that seems to be working fine.

**Comment by shailesh33** [comment]
hmm. Heres the reason: 
https://github.com/Netflix/dynomite/blob/0c87f1411ecfdba03c387ae85476ee45ac572538/src/proto/dyn_redis.c#L1025

It seems we are forcing to get the request from local rack only. From what I remember, we did this change because the order of elements in the Hash could be different on different nodes. Or better, they could have some elements missing because of delayed replication or simultaneous access. 
There is a chance that quorum will not work in this case most of the times.

**Comment by srikanthm-1** [comment]
> we did this change because the order of elements in the Hash could be different on different nodes

Yes, thats true, can Dynomite be smarter in these scenarios by performing individual KV comparison? I understand there will be a performance dent, but I think the benefits outweigh it.

> Or better, they could have some elements missing because of delayed replication or simultaneous access.

If its due to delayed replication, then the quorum read failing should be the right behavior right? Also, AFAIK simultaneous access shouldn't cause partial response since redis is single threaded and a put on a Map is completed before get is performed and partial keys are not returned. 

On a different note, this behavior should be documented somewhere. I discovered this by accident in our development environment and would have gone unnoticed to prod. But I do have a workaround in the meanwhile by using HMGET with all the keys specified instead of HGETALL.

Thanks,
Srikanth

**Comment by ipapapa** [comment]
The Wiki documentation has been updated to include the non-quorum responses: https://github.com/Netflix/dynomite/wiki/Consistency#operations-not-checked-for-a-quorum
