### ISSUE TITLE
Keyspace notifications support

### ISSUE THREAD

**Issue by voron** [Netflix/dynomite#520]
Does Dynomite support Redis Keyspace Notifications https://redis.io/topics/notifications ? I tried to use Spring Session +Jedis with Dynomite, but it disconnects with `JedisConnectionException: Unexpected end of stream.`.  Here is Dynomite tcpflow https://pastebin.com/raw/eXHhYdTa , and Redis tcpflow https://pastebin.com/raw/QLxwVhVu , 192.168.1.113 is client IP

**Comment by voron** [comment]
Found per notes/redis.md that PSUBSCRIBE isn't supported

**Comment by shailesh33** [comment]
thats right. Spring uses subscribe and Dynomite doesnt support that for obvious reasons.
