### ISSUE TITLE
Return of DEL operation in redis

### ISSUE THREAD

**Issue by hiagohubert** [Netflix/dynomite#523]
Hello guys, I don't know if this is a problem with dynomite implementation or with the redis python package. 

When I delete a key from redis it returns 1 and when I delete a key in dynomite it returns Null. So when using redis python package with the dynomite it throws a TypeError exception because it is expecting the return to be 1 instead of Null.

**Comment by mcouillard** [comment]
Odd. I'm unable to duplicate using redis-cli and the local redis port (6379) vs dynamite port (8102). Both return 1 on del key.

I'm using the dev branch as of the Dec 18 commit. How about you?

**Comment by zcalusic** [comment]
FWIW, I'm seeing these lines in log output:
```
[2018-02-28 10:39:42.538] redis_parse_req:1263 parsed unsupported command 'delete'
```

v0.6.5

**Comment by shailesh33** [comment]
The command should be `DEL` not `delete`

**Comment by zcalusic** [comment]
Oops, so this might be operator error, after all. :smile: 

I managed to find red:delete Lua calls, where it probably should have been red:del then.

Thanks for the answer, @shailesh33 I'll investigate further what's really goin' on there.

**Comment by zcalusic** [comment]
Yeah, it was an error on our part. Thanks once again @shailesh33 and sorry for the noise!

**Comment by ipapapa** [comment]
This issue has been answered.
