### ISSUE TITLE
INFO command is working partially

### ISSUE THREAD

**Issue by shunanya** [Netflix/dynomite#526]
Hi,

I use the latest version of Dynomite (v0.6.0-1-gfdf19a5) with local Redis (v4.0.2) engine. 
The 'info' command (without any section) is working properly. 
```
/GitHub_projects/dynomite$ redis-cli -p 6380
127.0.0.1:6380> info
# Server
redis_version:4.0.2
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:26ad0ed339f64220
.....
```

But when any section is specified the connection is crushed.
```
/GitHub_projects/dynomite$ redis-cli -p 6380
127.0.0.1:6380> info server
Error: Server closed the connection
127.0.0.1:6380>
```

**Comment by shailesh33** [comment]
It might be an issue with the parser in Dynomite. Let me try a few things.

**Comment by shailesh33** [comment]
Fixed it: https://github.com/Netflix/dynomite/pull/527
