### ISSUE TITLE
How to do Management in the absence of dynomite manager

### ISSUE THREAD

**Issue by nginxsantos** [Netflix/dynomite#529]
I am using dynomite and Redis in the openstack environment. But, I am having problem of using the dynomiteManager (to me it works in AWS only). Is there any other package which I can use for the management of the dynomite node in place of dynomite manager.

I am also interested for the entire life cycle management and scale out/scale in of the dynomite nodes (equivalent to what dynomite manager does).

Ant help?

**Comment by shailesh33** [comment]
@ipapapa there was some OSS effort on this. Can you shed some light on it?

**Comment by ipapapa** [comment]
I do not recall exactly the effort since there are several people contacting us of things they have developed. Probably we need to do a better job to bookkeep them. There have been a few efforts to support ECS (containers but still on AWS), some folks asking for GCP support, and some effort to deploy it in a local datacenter that I recall of. DM v2.x has abstracted several components so that it can be run in different environments. If you want to deploy it in OpenStack you probably need to implement a few interfaces. If there is something blocking you from these implementations, we can help out.

**Comment by nginxsantos** [comment]
@shailesh33 , @ipapapa 
,
Thank you for the reply. I defintely need your help. If you could guide me to what are the changes required to run this in OpenStack or vCenter then it will help.  I am really interested to do this and contribute to this great community but I  if you could help me to understand what are the changes required then it would really help me.
Any pointers would be helpful. I am looking for some basic basic Dynomite-Manager functionality (minus the S3-AWS storage/restore function; plus, the token management function without Cassandra).
Please let me know.

thanks, santos

**Comment by ipapapa** [comment]
The implementations that are AWS specific can be found in the [AWS package](https://github.com/Netflix/dynomite-manager/tree/dev/dynomitemanager-common/src/main/java/com/netflix/nfsidecar/aws). There are also two AWS specific implementations in the [backups](https://github.com/Netflix/dynomite-manager/tree/dev/dynomitemanager-core/src/main/java/com/netflix/dynomitemanager/aws). 
You do not have to implement all the functionality so for example, in the beginning, you can have some empty interfaces for the backups/restores.

In the [Getting started](https://github.com/Netflix/dynomite-manager/wiki/Getting-Started) you can find some information about what each interface does. If there is something that you do not see there and you want more information please let me know and I will be populating the Wiki.

I suggest that you start reading the [README](https://github.com/Netflix/dynomite-manager/blob/dev/README.md) and [Wiki](https://github.com/Netflix/dynomite-manager/wiki) and if you have specific questions then let us work on those. Going over them will also give you an understanding of how we run Dynomite in production.

**Comment by ipapapa** [comment]
Continuing on https://github.com/Netflix/dynomite-manager/issues/95
