### ISSUE TITLE
Dynomite Vs redis-cluster

### ISSUE THREAD

**Issue by thakurajayL** [Netflix/dynomite#532]
Hello,
Is there any comparison about which is better option ? How redis cluster is not so good option compared to dynomite ?

Can someone provide me some pointers ?

Thanks
Ajay

**Comment by ipapapa** [comment]
Redis Cluster is an CP system, Dynomite is an AP system (definitions based on the CAP theorem). Search for the word `Dynomite` in the Redis documentation: https://redis.io/topics/sentinel for more information

**Comment by ipapapa** [comment]
This question has been answered and there have not been any follow-up -> closing it.
