### ISSUE TITLE
List of Redis commands not supported ?

### ISSUE THREAD

**Issue by thakurajayL** [Netflix/dynomite#533]
HI,
I was going through the redis.md. We have list of commands which are supported in this file. But wanted to know if we know which commands are not  supported at this time and which commands can not be supported on dynomite because the way dynomite works ?

Thanks
Ajay

**Comment by mcouillard** [comment]
That list is already here: https://github.com/Netflix/dynomite/blob/dev/notes/redis.md

But I agree that extra visibility to it on a wiki page would help.

**Comment by thakurajayL** [comment]
Well can someone create wiki page ? What we are suppose to do to help in documentation ? I am willing to do that. 
We can add up the commands in that list. I see some of the enhancements issues reported to add the support. 

Thanks
Ajay

**Comment by ipapapa** [comment]
Good point. I have created a Wiki page that re-directs in the Redis.md file. I kept the file instead of copying-pasting in the Wiki as it is easier to keep the Github history outside of the wiki. 

https://github.com/Netflix/dynomite/wiki/Redis-Commands
