### ISSUE TITLE
keys are not equally distributed among all nodes across a rack when multi rack config is used in generate_yamls.py

### ISSUE THREAD

**Issue by shyamnayak6** [Netflix/dynomite#534]
Hi,

Keys are getting equally distributed when using generate_yamls.py for a single rack, but this is not same case when multiple racks are used for generating tokens.

Thanks,
Shyam

**Comment by shailesh33** [comment]
racks are essentially replicas or each other. Are you saying when using multiple nodes in a rack?

**Comment by shyamnayak6** [comment]
Yes using multiple nodes in a rack and replica with a single node. My configuration looks something like this.

python generate_yamls.py <IP>:rack1 <IP>:rack1 <IP>:rack2

**Comment by thakurajayL** [comment]
HI @shyamnayak6 ,
Can you please post your generated yaml files for every node.

Thanks
Ajay

**Comment by smukil** [comment]
This is fixed here:
https://github.com/Netflix/dynomite/commit/0e0db801571b2d42eac405b448717136b6b3191f
