### ISSUE TITLE
[proposed-label: Help Wanted] Workflows stopping in random places with multi-node Conductor/Dynomite on AWS

### ISSUE THREAD

**Issue by kpdude7** [Netflix/dynomite#537]
We currently have 3 Conductor instances backed by an ELB in AWS, one for each of 3 AZ's. We also have 3 Dynomite instances per AZ, for a total of 9. When we test assets through our workflows, sometimes an asset will get "stuck" in a workflow, and when viewing the workflow via the API, steps are just missing at the end. We also see periodic NoAvailableHostsExceptions in the Conductor logs:

Feb 21 16:43:36 ip-10-240-71-124 sh[17714]: %93005 [qtp1041451158-52] ERROR com.netflix.conductor.server.resources.GenericExceptionMapper  - NoAvailableHostsException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down], latency=0(0), attempts=0]Token not found for key hash: 151863863
Feb 21 16:43:36 ip-10-240-71-124 sh[17714]: %com.netflix.dyno.connectionpool.exception.NoAvailableHostsException: NoAvailableHostsException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down], latency=0(0), attempts=0]Token not found for key hash: 151863863
Feb 21 16:43:36 ip-10-240-71-124 sh[17714]: at com.netflix.dyno.connectionpool.impl.hash.BinarySearchTokenMapper.getToken(BinarySearchTokenMapper.java:68)

We are running Conductor 1.8.2, Dynomite dynomite-v0.5.9-5_MuslCompatiblity, and redis 3.2.10. 
Below are representative conductor.yml and dynomite.yml files:

conductor.yml:
`db=dynomite
workflow.dynomite.cluster.hosts=10.240.71.25:8102:us-east-1a;10.240.71.93:8102:us-east-1c;10.240.71.137:8102:us-east-1d
workflow.dynomite.cluster.name=dynomite_cluster_sit
workflow.namespace.prefix=conductor
workflow.namespace.queue.prefix=conductor_queues_sit
queues.dynomite.threads=30
queues.dynomite.nonQuorum.port=22122
workflow.elasticsearch.url=10.240.71.30:9300
workflow.elasticsearch.index.name=conductor
server.connection-timeout=60000
workflow.system.task.worker.poll.count=25
workflow.system.task.worker.thread.count=25
logging.level.com.netflix.conductor=INFO
EC2_AVAILABILITY_ZONE=us-east-1d`

dynomite.yml:
`dyn_o_mite:
datacenter: us-east-1
rack: us-east-1a
listen: 0.0.0.0:8102
dyn_listen: 0.0.0.0:8101
dyn_seed_provider: simple_provider
dyn_seeds:
- 10.240.71.16:8101:us-east-1a:us-east-1:2222222222
- 10.240.71.46:8101:us-east-1a:us-east-1:3333333333
- 10.240.71.70:8101:us-east-1c:us-east-1:3333333333
- 10.240.71.93:8101:us-east-1c:us-east-1:2222222222
- 10.240.71.103:8101:us-east-1c:us-east-1:1111111111
- 10.240.71.173:8101:us-east-1d:us-east-1:2222222222
- 10.240.71.160:8101:us-east-1d:us-east-1:1111111111
- 10.240.71.137:8101:us-east-1d:us-east-1:3333333333
tokens: 1111111111
servers:

127.0.0.1:6379:1
data_store: 0
stats_listen: 0.0.0.0:22122
mbuf_size: 65536
max_msgs: 300000
read_consistency: dc_safe_quorum
write_consistency: dc_safe_quorum
auto_eject_hosts: true
server_retry_timeout: 30000
server_failure_limit: 3
timeout: 10000`

During one of these occurrences, I noticed that of our 9 dynomites, one of them (10.240.71.16) was missing one of the dyn_seeds (10.240.71.70); when I looked at the log for 16, I saw:

`[2018-02-20 19:53:46.622] dnode_accept:168 Accepting client connection from 10.240.71.70:62472 on sd 22
[2018-02-20 19:53:46.622] event_add_conn:207 adding conn <LOCAL_PEER_CLIENT 0x1527ba0 22 from '10.240.71.70:62472'> to active
[2018-02-20 19:53:46.622] dnode_accept:210 <PEER_PROXY 0x14c74d0 12 listening on '0.0.0.0:8101'> accepted <LOCAL_PEER_CLIENT 0x1527ba0 22 from '10.240.71.70:62472'>
[2018-02-20 19:53:46.622] event_del_out:181 removing conn <LOCAL_PEER_CLIENT 0x1527ba0 22 from '10.240.71.70:62472'> from active
[2018-02-20 20:04:32.876] dnode_accept:168 Accepting client connection from 10.240.71.70:63703 on sd 22
[2018-02-20 20:04:32.876] event_add_conn:207 adding conn <LOCAL_PEER_CLIENT 0x888ef0 22 from '10.240.71.70:63703'> to active
[2018-02-20 20:04:32.876] dnode_accept:210 <PEER_PROXY 0x8874d0 12 listening on '0.0.0.0:8101'> accepted <LOCAL_PEER_CLIENT 0x888ef0 22 from '10.240.71.70:63703'>
[2018-02-20 20:04:32.876] event_del_out:181 removing conn <LOCAL_PEER_CLIENT 0x888ef0 22 from '10.240.71.70:63703'> from active`

I'm not sure why these connections keep dropping, but this dynomite instance never re-accepted the connection from 70. 

We have tried everything under the sun to address this issue, from increasing mbuf_size to decreasing our payload from one workflow task step to the next, and still see this issue.

**Comment by kpdude7** [comment]
I also posted this issue in the Conductor forum.

**Comment by ipapapa** [comment]
Seems a good portion of the discussion has been done in https://github.com/Netflix/conductor/issues/432 Hence I am closing this as a duplicate.
