### ISSUE TITLE
Using Dynomite with Laravel

### ISSUE THREAD

**Issue by MeeDNite** [Netflix/dynomite#541]
Hi,

I want to connect my application to Dynomite using phpredis.

In CLI (redis-cli) everything works fine and data is replicated in all redis nodes. but when I use php to write and read from redis, it seems that phpredis is connecting to redis, not Dynomite.

What am I doing wrong?
Regards.

**Comment by sobkovych** [comment]
I think a good point to start is to check if phpredis connects to the right port. I mean redis server listens on 6379 by default and dynomite proxy uses 8102 (it depends from <listen> parameetr in your config).

**Comment by ipapapa** [comment]
That is correct, you need to configure the proper port number.
