### ISSUE TITLE
Tomcat web session replication

### ISSUE THREAD

**Issue by sampleap** [Netflix/dynomite#542]
Hi,

Is Dynomite a good choice for tomcat web session replication?

I need to reliably replicate tomcat sessions across multiple tomcat runtimes and Data Centers.
With strong consistency.
Is it possible with Dynomite?

Regards,
S.

**Comment by mcouillard** [comment]
With sticky sessions that use cookies, I think so. That ensures your clients aren't bouncing between servers rapidly, possibly running into stale data if Dynomite's async replication isn't keeping up. It's fast, but sticky sessions help minimize the chance for edge-case issues.

If you can get tomcat sessions working with redis, you can make it work with Dynomite. I don't think tomcat does anything special with redis; just basic ops. I know PHP session storage backed by Dynomite is fine.
https://dzone.com/articles/setup-redis-session-store

**Comment by sampleap** [comment]
Thanks,

For me edge-case issues are most interesting.
And replication between Data Centers (DCs).

Lets assume we don't use sticky sessions.
Replication between 2 DCs is configured.
Client hits first runtime in DC1, then application create in session some object (O).
Then client rapidly hits second runtime in DC2.
We expect on second runtime in application replicated session from first runtime, and O in its session.

Is it possible with Dynomite in every case?
To be 100% sure we will get this replicated O every time and don't loose information.
This is very important for me.
Synchronization time between DCs and possible lags not important.

**Comment by shailesh33** [comment]
How is this possible in any system? Take any system for that matter, Dynomite, Cassandra etc, if the replication between data centers is lagging, or broken, how do you expect replication to happen, unless you use full quorum i.e every write ensure that the replication went to another DC and then only acknowledge. If that is something that you desire, then we will need some modifications in Dynomite layer where we wait for Remote DC replication to happen before acknowledging. In this case, remember that the writes might fail for a long time if the cross DC replication is broken, which is worse.

**Comment by sampleap** [comment]
Under normal circumstances, no network failures, lags, etc.
Can Dynomite be configured for strong consistency, as described above?
As I understand, no, full quorum should be implemented.

**Comment by shailesh33** [comment]
Cross DC replication is Async. Under normal scenarios, yes the replication will succeed.

Is there a way for the client to wait for cross DC replication to finish? No.

**Comment by ipapapa** [comment]
This question seems to have been answered. I am therefore closing this issue. If you have any further questions, please open a new issue.
