### ISSUE TITLE
Question: max mbuf_size Recommendation

### ISSUE THREAD

**Issue by balajivenki** [Netflix/dynomite#543]
For one of our requirement our key size can be more than the default 16kb and can go upto 100kb. 

We have see the following errors in dynomite.log

`[2018-03-02 23:00:01.545] redis_parse_req:1312 parsed bad req 20185 of type 55 with key length 54214 that greater than or equal to maximum redis key length of 16336`

The prod recommendation doc https://github.com/Netflix/dynomite/blob/master/notes/recommendation.md says 65k is what we can go upto. 

Since Redis supports 500mb size for a key, can we safely set it to 100kb beyond the recommended value which is 65k?

If so what can be the implications.

**Comment by shailesh33** [comment]
@balajivenki To be very honest, we have never tried that big of a key in our system. In fact I do not even know what will be the behavior if the key spans across buffers. But you can give it a try and let me know what you see?

**Comment by balajivenki** [comment]
Thanks @shailesh33  For now we are going with the recommended 65k as mbuf value. If needed we will increase it more than that. I just want to know your take from the code it wont be any issue right? We checked the code and couldn't find any issue, so wanted to double confirm.

**Comment by shailesh33** [comment]
Testing is the right way to be sure. :)

**Comment by balajivenki** [comment]
Thanks @shailesh33  We will verify with our QA and keep this page updated.

**Comment by balajivenki** [comment]
Since mbuf_size increasing has its own performance and memory issues and slowness we have decided to keep it the default 16kb. Closing this issue
