### ISSUE TITLE
Can dynomite by cross-compiled?

### ISSUE THREAD

**Issue by onexay** [Netflix/dynomite#544]
$ ./configure --prefix=/usr --build x86_64-unknown-linux-gnu --host arm-brcm-linux-gnueabi --target arm-brcm-linux-gnueabi --host=arm-brcm-linux-gnueabi --with-sysroot=/data/git/wing7int/wing/out/willow/root --enable-static=no ac_cv_fu
nc_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-gcc accepts -g... yes
checking for /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-gcc option to accept ISO C89... none needed
checking whether /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-gcc... gcc3
checking how to run the C preprocessor... /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-cpp
checking for arm-brcm-linux-gnueabi-g++... arm-brcm-linux-gnueabi-g++
checking whether we are using the GNU C++ compiler... yes
checking whether arm-brcm-linux-gnueabi-g++ accepts -g... yes
checking dependency style of arm-brcm-linux-gnueabi-g++... gcc3
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking the name lister (/tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin//arm-brcm-linux-gnueabi-nm -B) interface... BSD nm
checking the maximum length of command line arguments... 3458764513820540925
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to arm-brcm-linux-gnueabi format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-ld option to reload object files... -r
checking for arm-brcm-linux-gnueabi-objdump... arm-brcm-linux-gnueabi-objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking for arm-brcm-linux-gnueabi-ar... /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-ar
checking for archiver @FILE support... @
checking for arm-brcm-linux-gnueabi-strip... (cached) /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-strip
checking for arm-brcm-linux-gnueabi-ranlib... /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-ranlib
checking command to parse /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin//arm-brcm-linux-gnueabi-nm -B output from /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-gcc object... ok
checking for sysroot... /data/git/wing7int/wing/out/willow/root
checking for arm-brcm-linux-gnueabi-mt... no
checking for mt... mt
configure: WARNING: using cross tools not prefixed with host triplet
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-gcc supports -fno-rtti -fno-exceptions... no
checking for /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-gcc option to produce PIC... -fPIC -DPIC
checking if /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-gcc PIC flag -fPIC -DPIC works... yes
checking if /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-gcc static flag -static works... yes
checking if /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-gcc supports -c -o file.o... yes
checking if /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-gcc supports -c -o file.o... (cached) yes
checking whether the /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-gcc linker (/tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-ld) supports shared librchecking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for ld used by arm-brcm-linux-gnueabi-g++... /tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-ld
checking if the linker (/tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-ld) is GNU ld... yes
checking whether the arm-brcm-linux-gnueabi-g++ linker (/tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-ld) supports shared libraries... yes
checking for arm-brcm-linux-gnueabi-g++ option to produce PIC... -fPIC -DPIC
checking if arm-brcm-linux-gnueabi-g++ PIC flag -fPIC -DPIC works... yes
checking if arm-brcm-linux-gnueabi-g++ static flag -static works... yes
checking if arm-brcm-linux-gnueabi-g++ supports -c -o file.o... yes
checking if arm-brcm-linux-gnueabi-g++ supports -c -o file.o... (cached) yes
checking whether the arm-brcm-linux-gnueabi-g++ linker (/tools//gcc-4.9.4-glibc-2.18-p2-3.14.43/arm-brcm-linux-gnueabi/bin/arm-brcm-linux-gnueabi-ld) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for inline... inline
checking for int8_t... yes
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for unsigned long long int... yes
checking for long long int... yes
checking for intmax_t... yes
checking for intptr_t... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uintmax_t... yes
checking for uintptr_t... yes
checking for off_t... yes
checking for pid_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking whether byte ordering is bigendian... no
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for string.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/uio.h usability... yes
checking sys/uio.h presence... yes
checking for sys/uio.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/un.h presence... yes
checking for sys/un.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking sys/epoll.h usability... yes
checking sys/epoll.h presence... yes
checking for sys/epoll.h... yes
checking sys/event.h usability... no
checking sys/event.h presence... no
checking for sys/event.h... no
checking for pow in -lm... yes
checking for pthread_create in -lpthread... yes
checking for SSL_read in -lssl... yes
checking for OPENSSL_init in -lcrypto... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... cross
configure: WARNING: result yes guessed because of cross compilation
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... (cached) yes
checking for dup2... yes
checking for gethostname... yes
checking for gettimeofday... yes
checking for strerror... yes
checking for socket... yes
checking for memchr... yes
checking for memmove... yes
checking for memset... yes
checking for strchr... yes
checking for strndup... yes
checking for strtoul... yes
checking if epoll works... configure: error: in `/data/git/wing7int/wing/obj/willow/src/sys/3rdparty/dynomite/dynomite-0.6.6':
configure: error: cannot run test program while cross compiling
See `config.log' for more details

**Comment by shailesh33** [comment]
No it cannot be cross compiled as yet

**Comment by onexay** [comment]
I was able to cross-compile it setting following variables during ./configure

ac_cv_func_malloc_0_nonnull=yes
ac_cv_func_realloc_0_nonnull=yes
ac_cv_evports_works=no
ac_cv_kqueue_works=no
ac_cv_epoll_works=yes

Of course, these settings are true for my target.
