### ISSUE TITLE
Question: How atomicity is handled through Dynomite as transnational commands are not supported 

### ISSUE THREAD

**Issue by shyamnayak6** [Netflix/dynomite#547]
Hi,

Would you clarify on atomicity and consistency in terms of Dynomite as transactional commands are not supported. We know Redis is single threaded but still it provides transnational features.

Do we have to use dyno client for transactional guarantees ?

Thanks,
Shyam

**Comment by shailesh33** [comment]
Hi Shyam,
No There are no transactions supported in Dynomite but you can go one step ahead with quorum guarantees.

**Comment by shyamnayak6** [comment]
Thanks!!

**Comment by abdulrahman004** [comment]
Can somebody elaborate how quorums can substitute for transactions
