### ISSUE TITLE
Data Loss

### ISSUE THREAD

**Issue by jossysebastian** [Netflix/dynomite#552]
I trying a test bed with 4 dynomite instance with in a same server. I have 4 redis server running which is attached to each dynomite. first 2 are in rack1 and other two in rack2. All 4 instance are marked as same data center. Sharding and replications are fine when all dynomites and redis server are up. 
But I made redis instance of 4th dynomite down. In stage, I made few write operations on the other dynomite instances. After that made the redis up. Now the changes done while redis 4 was down are still missing in redis 4. What is wrong here ? Am I missing anything?

Dynomite 1 and 3 has the same tokens and Dynomite 2 and 4 the same token

All redis are running with **save** disabled and **appendonly** set as **yes**

[configs.zip](https://github.com/Netflix/dynomite/files/1901530/configs.zip)

Please help

**Comment by mcouillard** [comment]
I believe only the companion product, dynomite-manager, handles a 'cold-bootstrap' process when nodes come back online. Nothing else catches-up out of sync nodes; dynomite is just a proxy that replicates changes as they pass through. If a node isn't there at the time of the change, it won't get the change later.

More info: https://github.com/Netflix/dynomite-manager/wiki/Cold-Bootstraping

**Comment by ipapapa** [comment]
That is correct. Dynomite does not itself repair the data. Dynomite-manager is able to fetch the peer data after a node termination

**Comment by ipapapa** [comment]
I am closing this since there has not been any further question and the initial question was answered.
