### ISSUE TITLE
Help: Too many open files in system

### ISSUE THREAD

**Issue by balajivenki** [Netflix/dynomite#553]
In our cluster in the first primary rack node we see tons of the following errors

`[2018-04-16 04:57:54.038] proxy_recv:228 <CONN_PROXY 0x1da8290 8 listening on '0.0.0.0:xxxx'> Failed to accept a connection. Continuing
[2018-04-16 04:57:54.039] proxy_accept:170 accept on <CONN_PROXY 0x1da8290 8 listening on '0.0.0.0:xxxx'> failed: Too many open files in system`

and it fills up the disk in minutes like GBs in minutes in dynomite.log

FYI the ulimit we have is 500000. Any hint what might be causing this ? We run dynomite v0.6.3

**Comment by shailesh33** [comment]
Can you check from netstat if there are too many connections from the client?
What is the client version you are using?

**Comment by balajivenki** [comment]
netstat shows its all from clients. We run dynomite v0.6.3 and client v1.5.9

On the side, in dynomite is it ok to give seeds as dns names or IP is preferred? We run all of them as DNS names

**Comment by shailesh33** [comment]
It should be fine. We provide hostnames in the conf file.

**Comment by balajivenki** [comment]
We found that the connections are coming abruptly from the client apps running inside docker swarm cluster. The issue was not reproducible when running away from swarm. Connecting through IP from swarm cluster resolved the issue though. Either issue with docker swarm overlay network or dns resolution timeouts. Closing the issue for now.
