### ISSUE TITLE
Is RocksDB still supported ?

### ISSUE THREAD

**Issue by unoexperto** [Netflix/dynomite#555]
Hey guys,

Sorry for perhaps naive question. Is RocksDB still supported ? I couldn't find answer neither in doc nor in github/dockerhub pages.

The things are unclear to me:

1) Is RocksDB still sopprted as backend ?
2) Is Redis one of backends or is it protocol frontend for rocksdb backend ?

**Comment by shailesh33** [comment]
Dynomite is a layer on top of non distributed storage engines. Today it understands Redis well and Memcache (has some bugs to be sorted there). So essentially it can talk to storage engine that understands redis apis. It could be a redis server process itself, or some other process that understands redis protocol and writes to say disk using rocksdb, boltdb etc. There are other open source software for example https://github.com/yinqiwen/ardb which understands redis and writes to disk. 
I hope this answers.
