### ISSUE TITLE
DynoJedisClient does not support blocking calls for queue operations

### ISSUE THREAD

**Issue by bshevade** [Netflix/dynomite#557]
Hello,

We are using dynomite jedis client (dyno-jedis version 1.6.3) with redis but without the dynomite server at the moment. However, we see that the blocking calls like brpoplpush are not yet supported. Any idea when they will be supported? Thanks!

**Comment by ipapapa** [comment]
It feels that this issue should be migrated to the Dyno Github repository. Would you mind opening it there?

FWIW, not all commands are supported by Dyno. We and the OSS folks have implemented the commands that have been useful for Dynomite. However, if you have found other usages of Dyno then please consider adding those commands.

**Comment by bshevade** [comment]
Thanks @ipapapa for your comments. I have opened the issue in Dyno Github repo. I will try to add the blocking commands myself and open a PR for review. Thanks!
