### ISSUE TITLE
Merge values

### ISSUE THREAD

**Issue by tolikr** [Netflix/dynomite#565]
Does dynomite support merge values after network issue occurs?

I have 2 dynomite instaces connected to 2 redis servers. After connection breaks, i add on one dynomite instance "test" -> "test1", on another i add "test" -> "test2". After connection re-established, values swaps between instances. I expected that one should be dropped, and use last updated. Do i mistake?

**Comment by ipapapa** [comment]
The last write should win. During the network disconnectivity, the data will be lost. After the connection is re-established there should be no problem. If the data have the same key it is up to Redis to merge them not Dynomite.

**Comment by tolikr** [comment]
So it seems like Redis merged values incorrect?

**Comment by shailesh33** [comment]
Dynomite will not merge values on a network disconnect. But you can use
quorum settings to get better consistency in the system.

**Comment by tolikr** [comment]
Ok, i understand. Thanks.
