### ISSUE TITLE
dynomite core down 

### ISSUE THREAD

**Issue by binbowang1987** [Netflix/dynomite#570]
dynomite version: v0.6.7 
configuration: 
dyn_o_mite:
  datacenter: dc_cq
  rack: rack1
  dyn_listen: 172.19.3.113:8101
  dyn_seeds:
  - 172.19.3.114:8101:rack1:dc_cq:1073741823
  - 172.19.3.116:8101:rack1:dc_cq:2147483646
  - 172.19.3.117:8101:rack1:dc_cq:3221225469
  - 172.22.128.40:8101:rack1:dc_wx:0
  - 172.22.128.41:8101:rack1:dc_wx:1073741823
  - 172.22.128.42:8101:rack1:dc_wx:2147483646
  - 172.22.128.43:8101:rack1:dc_wx:3221225469
  listen: 0.0.0.0:8102
  servers:
  - 127.0.0.1:6380:1
  tokens: '0'
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
  #1MiB buffer
  mbuf_size: 512000
  #max number of messages to allocate 
  max_msgs: 1000000
  read_consistency : DC_QUORUM
  write_consistency : DC_QUORUM
  stats_listen: 0.0.0.0:22222

![image](https://user-images.githubusercontent.com/8586061/41708594-9b01c8a4-7573-11e8-90d0-db74a6b12b83.png)

**Comment by ipapapa** [comment]
How did you get this issue?

**Comment by binbowang1987** [comment]
I do not how this issue arise, after I change conf file to the dynomit.pem file in dynomite repository, this issue looks like gone away. When the issue arising, I am using a pem file generated by myself, maybe the pem is not valid. 
So, what is the correct way to generate a pem file ?

**Comment by smukil** [comment]
@binbowang1987 It's basically a RSA key. You can generate them using the standard OpenSSL tools.
