### ISSUE TITLE
Dynomite core down when use pipeline

### ISSUE THREAD

**Issue by binbowang1987** [Netflix/dynomite#571]
Dynomite version: 0.5.9-5_MuslCompatiblity

process to reproduce: 
redis-benchmark -p 8102 -q -t set,get -c 100 -P 10

here is the gdb back trace: 
#0  0x0000003518c32625 in raise () from /lib64/libc.so.6
#1  0x0000003518c33e05 in abort () from /lib64/libc.so.6
#2  0x00000000004381a0 in _log (file=0x478b6a "_msg_get", line=300, panic=1, 
    fmt=0x4785c0 "Bad link elm %p next->prev != elm") at ../dyn_log.c:183
#3  0x0000000000425a02 in _msg_get (conn=0x11337f0, request=false, caller=0x478b10 "msg_parsed")
    at dyn_message.c:300
#4  0x000000000042607a in msg_get (conn=0x11337f0, request=false, caller=0x478b10 "msg_parsed")
    at dyn_message.c:415
#5  0x0000000000427205 in msg_parsed (ctx=0x11261a0, conn=0x11337f0, msg=0x10eda290)
    at dyn_message.c:800
#6  0x0000000000427719 in msg_parse (ctx=0x11261a0, conn=0x11337f0, msg=0x10eda290)
    at dyn_message.c:951
#7  0x0000000000427d38 in msg_recv_chain (ctx=0x11261a0, conn=0x11337f0, msg=0x10eda290)
    at dyn_message.c:1119
#8  0x0000000000427e32 in msg_recv (ctx=0x11261a0, conn=0x11337f0) at dyn_message.c:1152
#9  0x0000000000415c19 in core_recv (ctx=0x11261a0, conn=0x11337f0) at dyn_core.c:371
#10 0x00000000004162d3 in core_core (arg=0x11337f0, events=65535) at dyn_core.c:524
#11 0x000000000044f5f2 in event_wait (evb=0x1137970, timeout=20037) at dyn_epoll.c:279
#12 0x0000000000416b50 in core_loop (ctx=0x11261a0) at dyn_core.c:649
#13 0x000000000043f80b in dn_run (nci=0x7fff20aa2e50) at dynomite.c:589
#14 0x000000000043f96f in main (argc=8, argv=0x7fff20aa3098) at dynomite.c:651

**Comment by ipapapa** [comment]
You are using a fairly old version of Dynomite. The latest one is 0.6.7: https://github.com/Netflix/dynomite/releases

Please update and retry.

However, it works in my instance. Hence we need to see what is causing the issue:
```
$ redis-benchmark -p 8102 -q -t set,get -c 100 -P 10
SET: 46707.14 requests per second
GET: 166389.34 requests per second
```

Moreover, please provide some more info on the environment you are using.

**Comment by binbowang1987** [comment]
## my environment
OS: CentOS 6.5
dynomite configuration: 
```dyn_o_mite:
  datacenter: dc_cq
  rack: rack1
  dyn_listen: 172.19.3.113:8101
  dyn_seeds:
  - 172.19.3.114:8101:rack1:dc_cq:1073741823
  - 172.19.3.116:8101:rack1:dc_cq:2147483646
  - 172.19.3.117:8101:rack1:dc_cq:3221225469
  - 172.22.128.40:8101:rack1:dc_wx:0
  - 172.22.128.41:8101:rack1:dc_wx:1073741823
  - 172.22.128.42:8101:rack1:dc_wx:2147483646
  - 172.22.128.43:8101:rack1:dc_wx:3221225469
  listen: 0.0.0.0:8102
  servers:
  - 127.0.0.1:6380:1
  tokens: '0'
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
  #1MiB buffer
  mbuf_size: 1024
  #max number of messages to allocate 
  max_msgs: 1000000
  read_consistency : DC_QUORUM
  write_consistency : DC_QUORUM
  stats_listen: 0.0.0.0:22222
  auto_eject_hosts: true
  server_retry_timeout: 30000    
  server_failure_limit: 3      
  timeout: 400
```

and ,here is the ulimits, I don't know if this will cause this issue
```
[app@Onenet-test-db06 dynomite]$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 30470
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 30470
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by smukil** [comment]
@binbowang1987 This has been fixed since. Please reopen if you're still seeing this issue.
