### ISSUE TITLE
Dynomite Integration with AppDynamics [Question]

### ISSUE THREAD

**Issue by anujwalia** [Netflix/dynomite#579]
Hi All, 

I am planning to use Dynomite for one of my service. However i need to understand if i can integrate it with AppDynamics(https://www.appdynamics.com) for performance monitoring. 
I know Dynomite have Atlas for this, but as per my limited understanding according to this article (https://github.com/Netflix/atlas/wiki/Overview), very few features are open source.

If someone can throw some light on this, it will be helpful. 
#

**Comment by mcouillard** [comment]
Dynomite can output metrics to a page (defaults to port 22222) and that's what I use in conjunction with a custom scraper that takes the data and inserts it into a time series database for Grafana visualization. If AppDynamics supports custom ingestion like that then it could be fine.

Plus the usual Redis stats is still output to a page could also be ingested. I think some like Datadog support this out of the box.
