### ISSUE TITLE
Support for redis streams (XADD / XREADGROUP / XRANGE...)

### ISSUE THREAD

**Issue by axelc** [Netflix/dynomite#580]
Are redis streams in the roadmap for Dynomite at some point?

**Comment by ipapapa** [comment]
We do not have a use case right now so not in our roadmap. Things change though quarter by quarter. If you are up to contributing the commands it should be fairly simple.

**Comment by ipapapa** [comment]
This question has been answered. If you wish to have a discussion please add your response in this issue and we can re-open it.
