### ISSUE TITLE
External PDF link issue in docs

### ISSUE THREAD

**Issue by JeremyHutchings** [Netflix/dynomite#581]
I found on this wiki page : 
 - https://github.com/Netflix/dynomite/wiki/Membership-protocols
A link to a PDF : 
 - https://www.cs.cornell.edu/~asdas/research/dsn02-swim.pdf

Which is a 404.

Is this the document linked to ? 
- http://www.cs.cornell.edu/projects/Quicksilver/public_pdfs/SWIM.pdf

**Comment by ipapapa** [comment]
Thank you for the note. We have taken care of this documentation issue.
