### ISSUE TITLE
How to generate RSA private key (.pem) to use with Dynomite?

### ISSUE THREAD

**Issue by yura415** [Netflix/dynomite#582]
I've tried to use openssl tool from libssl and aes128 algorithm to generate encrypted key and then remove password from it:

```bash
openssl genrsa -aes128 -out key.pem
openssl rsa -in key.pem -out dynomite.pem
```

Dynomite boots normally with this key provided but it disconnects client on first write. I've tried to replace my generated key with default key from conf/dynomite.pem and it worked.

The question is - how the original key from conf dir was generated? Can someone provide correct commands to generate a similar key?

**Comment by thias** [comment]
This seems to have worked for me with 0.5.9 (the latest 0.6 releases seem to start without the file): `ssh-keygen -t rsa -f dynomite.pem`

**Comment by smukil** [comment]
Thanks for answering @thias :)
