### ISSUE TITLE
Question regarding replication

### ISSUE THREAD

**Issue by sheldon-sminq** [Netflix/dynomite#583]
I have single node on 2 different servers, and want the data replicated between the 2 redis instances.

My current config is below, but data is not replicated.

```
dc1
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_listen: 0.0.0.0:8101
  dyn_seeds:
  - 139.59.66.243:8101:rack2:dc2:1234567
  listen: 0.0.0.0:8102
  servers:
  - 127.0.0.1:6379:1
  tokens: '3456789'
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
  stats_listen: 0.0.0.0:22221
  read_consistency : DC_QUORUM
  write_consistency : DC_QUORUM
```
```
dc2

dyn_o_mite:
  datacenter: dc2
  rack: rack2
  dyn_listen: 0.0.0.0:8101
  dyn_seeds:
  - 159.89.168.137:8101:rack1:dc1:3456789
  listen: 0.0.0.0:8102
  servers:
  - 127.0.0.1:6379:1
  tokens: '1234567'
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
  stats_listen: 0.0.0.0:22222
  read_consistency : DC_QUORUM
  write_consistency : DC_QUORUM

```

**Comment by mcouillard** [comment]
I think you'll want each server to handle all tokens - so set both to the max. Right now it looks like each are handling only half the data, so nothing is replicated. When both handle all data it should be replicated.

**Comment by sheldon-sminq** [comment]
Not really clear with the max token setup, is it possible to give and example config?

**Comment by mcouillard** [comment]
I've seen some use a real high value, but I just use zero. So in dyn_seeds after the last colon of each server goes a 0. Then down below, tokens: '0'. That means each node has all data, not a sharded subset.

**Comment by sheldon-sminq** [comment]
I created these new ymls, 2 nodes in same datacenter want to replicate all data between 2 redis nodes running on port 6379 and 6380. Currently no luck with the master master replication.

```
dyn_o_mite:
  datacenter: dc
  rack: rack1
  dyn_listen: 127.0.0.1:8101
  dyn_seeds:
  - 127.0.0.1:8102:rack2:dc:0
  listen: 127.0.0.1:8103
  servers:
  - 127.0.0.1:6379:1
  tokens: '0'
  secure_server_option: datacenter
  pem_key_file: /root/dynomite/conf/dynomite.pem
  data_store: 0
  stats_listen: 127.0.0.1:22221
  read_consistency : DC_QUORUM
  write_consistency : DC_QUORUM
```

```
dyn_o_mite:
  datacenter: dc
  rack: rack2
  dyn_listen: 127.0.0.1:8102
  dyn_seeds:
  - 127.0.0.1:8101:rack1:dc:0
  listen: 127.0.0.1:8104
  servers:
  - 127.0.0.1:6380:1
  tokens: '0'
  secure_server_option: datacenter
  pem_key_file: /root/dynomite/conf/dynomite.pem
  data_store: 0
  stats_listen: 127.0.0.1:22222
  read_consistency : DC_QUORUM
  write_consistency : DC_QUORUM
```

**Comment by mcouillard** [comment]
Configs seem to look OK, though the consistency should probably be DC_ONE. Otherwise, perhaps it's something more basic: are your clients using the dynomite port to interact with redis, 8103/4? If you use the redis backend port, 6379/80, nothing will be replicated.

**Comment by sheldon-sminq** [comment]
@mcouillard thanks for the update, my bad was using the redis client directly with the original ports. Replication seems to work now using the dynomite ports.
