### ISSUE TITLE
How to add new node without restarting dynomite

### ISSUE THREAD

**Issue by rajangamsj** [Netflix/dynomite#584]
To add a new node, I update the dyn_seeds in .yml file and it is required to restart the dynomite to again read the seed node information from the yml file.

Is there a way to do this without the requirement to restart (any APIs which would trigger dynomite to read the yml file again or just to send the new node information without the need to restart?)

**Comment by mcouillard** [comment]
I second this idea! Would love to skip the (quick) disruption of a restart when scaling up/down by adding nodes.

**Comment by ipapapa** [comment]
Yes, Dynomite gets the updated tokens through a REST call. You do not need to restart Dynomite for it to get the tokens updated. Dynomite would to that for you in the background. This is effectively how it gets the tokens updated once a node dies and a new one comes up.

The YAML file is only used to bootstrap Dynomite, and it does not get used later on. Hence, that is why you do not see the topology getting updated. If you are not using Dynomite-manager (which would that for you), a script to update the YAML and Dynomite through

**Comment by 52tt** [comment]
> Yes, Dynomite gets the updated tokens through a REST call. 

What is the REST call to update the tokens?
I can not find that call from https://github.com/Netflix/dynomite/wiki/REST :-(

**Comment by rajangamsj** [comment]
We ran the Florida server (https://github.com/Netflix/dynomite/tree/dev/scripts/Florida) and updated the seeds.list file.  Dynomite is able to get the updated seeds information through the Florida server.

**Comment by ipapapa** [comment]
In addition, if you are using Dynomite-manager see the listed REST endpoints including `get_seeds`: https://github.com/Netflix/dynomite-manager/wiki/REST-API
