### ISSUE TITLE
Does "florida_provider" way of finding seed nodes require gossip to be enabled?

### ISSUE THREAD

**Issue by rajanarayan92** [Netflix/dynomite#585]
When dyn_seed_provider is set to florida_provider in yml file, do we need to enable gossip in dynomite?

The fact is that, when I run the dynomite server, I cannot add "-g" option, it doesn't understand this option. As per the wiki, it says to enable gossip by providing "-g" option

-g, --gossip            : enable gossip (default: disabled)

Also the document states that gossip is in experimental. Does that mean it is still under some kind of development?

> ./src/dynomite -g -c conf/dyno_exp_node1.yml 
> dynomite: invalid option -- 'g'
> Usage: dynomite [-?hVdDt] [-v verbosity level] [-o output file]
>                   [-c conf file] [-p pid file] [-m mbuf size (deprecated)]
>                   [-M max alloc messages (deprecated)]
> 
> Options:
>   -h, --help             : this help
>   -V, --version          : show version and exit
>   -t, --test-conf        : test configuration for syntax errors and exit
>   -d, --daemonize        : run as a daemon
>   -D, --describe-stats   : print stats description and exit
>   -v, --verbosity=N            : set logging level (default: 5, min: 0, max: 11)
>   -o, --output=S               : set logging file (default: stderr)
>   -c, --conf-file=S            : set configuration file (default: conf/dynomite.yml)
>   -p, --pid-file=S             : set pid file (default: off)
>   -m, --mbuf-size=N            : set size of mbuf chunk in bytes (default: 0 bytes)

**Comment by rajanarayan92** [comment]
Can some one also provide the information on what is the role of gossip in dynomite with some examples?

**Comment by shailesh33** [comment]
If you have a seeds provider set, then you do not need gossip. And We
recommend you use a seeds provider. Look at
https://github.com/Netflix/dynomite-manager/ for more details.
It is a sidecar for managing Dynomite.

**Comment by rajanarayan92** [comment]
Thank you Shailesh.
