### ISSUE TITLE
GEOADD, GEORADIUS support Redis 

### ISSUE THREAD

**Issue by sheldon-sminq** [Netflix/dynomite#588]
We are testing replication between 2 redis nodes using dynomite, the replication is working fine but we came across an issue while using geo commands of redis.

Does dynomite support these commands?

**Comment by shailesh33** [comment]
Hi
Dynomite does not support Geo commands yet. But I do not see why it cannot
be done. It is just like other single key commands.
Do you want to give it a stab?
Check proto/dyn_redis.c

**Comment by sheldon-sminq** [comment]
Hi @shailesh33  

Had a look at the code and it was pretty simple to add support for GEOADD and GEORADIUS, how do i go about adding this contribution here?.

**Comment by sheldon-sminq** [comment]
pull request added for the same.

https://github.com/Netflix/dynomite/pull/589

**Comment by sheldon-sminq** [comment]
After adding the support we could use the commands as expected, but now have come across a blocker that prevents us from using dynomite for now. We use Redisson as our java client and make use of the Batch commands there. According to the doc Redisson uses multi/exec for batch operations which is not supported in dynomite.

**Comment by shailesh33** [comment]
Hi
Yes we do not support radisson yet. We just use 'dyno' client and do not
support transactions.
