### ISSUE TITLE
Dynomite and Redis integration driver for FastoNoSQL

### ISSUE THREAD

**Issue by topilski** [Netflix/dynomite#621]
Hi, i found here https://github.com/Netflix/dynomite/blob/dev/notes/redis.md commands which dynomite support in Redis, i think i can implement driver for dynomite to show Redis content. is it a good idea? do you have some use cases when needed GUI for this solution?

**Comment by ipapapa** [comment]
Dynomite supports a subset of the vanilla Redis commands. What type of driver do you have in mind?
We have an internal GUI that we have not yet open sourced (and we are not sure when). You can find some more information at this [video](https://youtu.be/MPrJIFVgy6g?t=1118). However, we would love to help you out if you want to create an OSS GUI.

**Comment by topilski** [comment]
Hi @ipapapa thank you for reply, we have 10 database drivers (FastoNoSQL slang, common interface wrap DB api) here sources https://github.com/fastogt/fastonosql_core/tree/master/src/core/db , in your case i think driver can be inharitance from https://github.com/fastogt/fastonosql_core/tree/master/src/core/db/redis_compatible which based on hiredis with ssh support , but commands count will be less than in common redis driver.

**Comment by ipapapa** [comment]
Correct. Note that Sentinel and Cluster commands are not relevant to us because Dynomite is multi-master and does not require external management systems.

**Comment by topilski** [comment]
Hi @ipapapa , i added DynomiteDB driver into FastoNoSQL here screenshot: 

![dynomitedb](https://user-images.githubusercontent.com/4686379/49362069-c60a1900-f6ee-11e8-9229-1e1af8e4a0a0.png)

It will be very cool if DynomiteDB have AUTH, SELECT, and DBSIZE implementation.

**Comment by ipapapa** [comment]
Awesome looks good. Note that `DynomiteDB` is a private company not currently associated with the project. Our OSS solution is called `Dynomite`. Currently, we only allow single DB that is why the `SELECT` command is not there. At some point, we are thinking of adding AUTH.

**Comment by topilski** [comment]
Hey @ipapapa thank you for reply, i will rename. Can i use this logo or need to change? Also how can i see DBSIZE not implemented?

**Comment by ipapapa** [comment]
I think the logo is not correct. You can find Dynomite's logo under [images](https://github.com/Netflix/dynomite/tree/dev/images). I do not see any issue in adding `DBSIZE`. It should be fairly simple but would return the local copies size.

**Comment by topilski** [comment]
Hi @ipapapa , thank you for feedback, i updated resources and renamed driver. I will release FastoNoSQL on next Monday, also i will add links to Dynomite on our websites. Dynomite is very interesting solution, thank you for you job.
