### ISSUE TITLE
Coldstarting dynomite 

### ISSUE THREAD

**Issue by posix4e** [Netflix/dynomite#622]
As much as I appreciate dynomite-manager, we don't run a production cassandra installation so it's not very useful for us. I'm curious what my other options are for cold starting a dynomite server, without dynomite-manager

- [ ] We only use one set of shards. Our datasizes are relatively small we just want to write them anywhere
- [ ] We are using this as a cache, and all the data gets flushed into s3 eventually anyway
- [ ] We want to be able to add and remove servers, but it doesn't have to happen that way all the time. Our current plan is to bootstrap a new cluster, and switch users over to the new cluster when topology changes.

**Comment by ipapapa** [comment]
You do not need to use Cassandra to leverage Dynomite-manager. We are only using Cassandra for token management. Since DynamoDB now supports global tables and transactions, I think it should be a great option to store the tokens.

The Cold Bootstrapping process is explained [here](https://github.com/Netflix/dynomite-manager/wiki/Cold-Bootstraping). As you can see the only thing that is needed is to identify from which node to bootstrap. We use the tokens for that. All steps could be done in a small script.

**Comment by posix4e** [comment]
let’s discuss this script, as i’d like to make a guide to use it this way... with enough help. just a hostname - token mapping?

**Comment by mcouillard** [comment]
Here's the basic steps of an Ansible script we use to add new nodes to a cluster; may be of use:

systemctl stop dynomite
redis-cli -p {{ redis_port }} SLAVEOF {{ master_node }} {{ redis_port}}
pause seconds: '{{ sleep }}'
redis-cli -p {{ redis_port }} info replication
redis-cli -p {{ redis_port }} SLAVEOF NO ONE
systemctl start dynomite


My situation is a bit more simple in that every node contains all tokens (no sharding).

**Comment by ipapapa** [comment]
There are a few details that you are missing in the script (1) monitor the offset to make sure it is small enough. Sometimes you may not achieve the perfect offset; (2) set Dynomite in write-only, so even if there is an offset then you can flush it then and then enable Dynomite to accepts reads as well. These circumstances are useful in a high write scenario, but if you have low traffic, you can probably leave without them. However, you have to find a way/logic to stop the Redis replication (when to call `SLAVEOF NO ONE`

**Comment by posix4e** [comment]
what happens if you have write only and slave mode activated? double writes? that’s probably fine for a lot of use case.

**Comment by ipapapa** [comment]
If Redis is in Slave mode, it cannot accept writes and therefore Dynomite will return exceptions to the client. There is no reason to be in that mode.

**Comment by posix4e** [comment]
ipapapa, so does that mean when transitioning there's  write hole?

**Comment by ipapapa** [comment]
That is why I mentioned above: `(2) set Dynomite in write-only, so even if there is an offset then you can flush it then and then enable Dynomite to accepts reads as well.`. Then you disable the slave mode (I am sorry I forgot that). Hence, Dynomite will buffer the writes and flush them once you switch.

**Comment by posix4e** [comment]
Ooh nice! We should really make it explicit that this is what is going on
