### ISSUE TITLE
Replication not working ?

### ISSUE THREAD

**Issue by binooetomo** [Netflix/dynomite#634]
dear all

I have 2 centos7 box, each with ip address 192.168.5.81 and 192.168.5.82
Curently there is redis on each box (no clustering, no Sentinel).

Dynomite config yaml of 192.168.5.81 is :

dyn_o_mite:
    datacenter: ncdc-yk
    rack: rack-4
    dyn_listen: 192.168.5.81:6371
    listen: 192.168.5.81:6370
    dyn_seed_provider: simple_provider
    dyn_seeds:
    - 192.168.5.82:6371:rack-4:ncdc-yk:12345678
    servers:
    - 127.0.0.1:6369:1
    tokens: 12354678
    data_store: 0
    stats_listen: 0.0.0.0:22222

Dynomite config yaml of 192.168.5.82 is :

dyn_o_mite:
    datacenter: ncdc-yk
    rack: rack-4
    dyn_listen: 192.168.5.82:6371
    listen: 192.168.5.82:6370
    dyn_seed_provider: simple_provider
    dyn_seeds:
    - 192.168.5.81:6371:rack-4:ncdc-yk:12345678
    servers:
    - 127.0.0.1:6369:2
    tokens: 12354678
    data_store: 0
    stats_listen: 0.0.0.0:22222

At 192.168.5.81 try to set a key , and re-check if the key is stored

[root@ceph-node1 ~]# redis-cli -h 192.168.5.81 -p 6370
192.168.5.81:6370> set srv81:05 81:05
OK
192.168.5.81:6370> get srv81:05
"81:05"

At 192.168.5.82, try to get the key

[root@ceph-node2 dynomite]# redis-cli -h 192.168.5.82 -p 6370
192.168.5.82:6370> get srv81:05
(nil)

looks like the replication no run between the two nodes

Kindly please give me a clue to fix this problem

**Comment by ipapapa** [comment]
This is apparently a misconfiguration or a network problem, not a software issue. See the configuration folder for some examples: https://github.com/Netflix/dynomite/tree/dev/conf
