### ISSUE TITLE
directive "stats_listen" is unknown

### ISSUE THREAD

**Issue by zhjs0523** [Netflix/dynomite#638]
I started 3 nodes(node1.yml.node2.yml,node3.yml).When I configure on 'stats_listen'，it prints directive "stats_listen" is unknown,but when I droped the setting,it said 'Address already in use'.
node1.yml:
`dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_listen: 127.0.0.1:8101
  dyn_seeds:
  - 127.0.0.1:8201:rack1:dc1:1431655765
  - 127.0.0.1:8301:rack1:dc1:2863311530
  data_store: 0
  listen: 127.0.0.1:8102
  dyn_seed_provider: simple_provider
  servers:
  - 127.0.0.1:6379:1
  tokens: 0
  stats_listen: 127.0.0.1:3000
  pem_key_file: /Users/zhjs/Documents/JAVA/dynomite/dynomite/conf/dynomite.pem
  recon_key_file: /Users/zhjs/Documents/JAVA/dynomite/dynomite/conf/recon_key.pem
  recon_iv_file: /Users/zhjs/Documents/JAVA/dynomite/dynomite/conf/recon_iv.pem
  
`
node2.yml:
`dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_listen: 127.0.0.1:8201
  dyn_seeds:
  - 127.0.0.1:8101:rack1:dc1:0
  - 127.0.0.1:8301:rack1:dc1:2863311530
  data_store: 0
  listen: 127.0.0.1:8202
  dyn_seed_provider: simple_provider
  servers:
  - 127.0.0.1:6380:1
  tokens: 1431655765
  stats_listen: 127.0.0.1:30001
  pem_key_file: /Users/zhjs/Documents/JAVA/dynomite/dynomite/conf/dynomite.pem
  recon_key_file: /Users/zhjs/Documents/JAVA/dynomite/dynomite/conf/recon_key.pem
  recon_iv_file: /Users/zhjs/Documents/JAVA/dynomite/dynomite/conf/recon_iv.pem
`
node3.yml:
`
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_listen: 127.0.0.1:8301
  dyn_seeds:
  - 127.0.0.1:8101:rack1:dc1:0
  - 127.0.0.1:8201:rack1:dc1:1431655765
  data_store: 0
  listen: 127.0.0.1:8302
  dyn_seed_provider: simple_provider
  servers:
  - 127.0.0.1:6381:1
  tokens: 2863311530
  stats_listen: 127.0.0.1:30002
  pem_key_file: /Users/zhjs/Documents/JAVA/dynomite/dynomite/conf/dynomite.pem
  recon_key_file: /Users/zhjs/Documents/JAVA/dynomite/dynomite/conf/recon_key.pem
  recon_iv_file: /Users/zhjs/Documents/JAVA/dynomite/dynomite/conf/recon_iv.pem
`

**Comment by ipapapa** [comment]
Did you check if when you do not add it if it defaults to a port that is already in use by another process?

**Comment by zhjs0523** [comment]
> Did you check if when you do not add it if it defaults to a port that is already in use by another process?

No another process is using the port.I changed a few ports,but it always said that.Even if I start one node with the configuration,it also throws the error "stats_listen is unknown".

**Comment by smukil** [comment]
@zhjs0523 Your YAML file _may_ be improperly formatted if you're getting the "stats_listen is unknown" error.

You can check which process is using the default port by running:
`netstat -tulpn | grep 22222`

**Comment by zhjs0523** [comment]
> @zhjs0523 Your YAML file _may_ be improperly formatted if you're getting the "stats_listen is unknown" error.
> 
> You can check which process is using the default port by running:
> `netstat -tulpn | grep 22222`

Thanks for your answer.I have solved this question with the another way to start.I deleted this configuration in my YAML file .Instead of that,I added "-s" to specify the port on startup like './dynomite -c node1.yml -s 22222 -d --output=../logs/node1.log'.
