### ISSUE TITLE
Dynomite only setting values to 1 redis server behind dynomite

### ISSUE THREAD

**Issue by ankur-aggarwal** [Netflix/dynomite#640]
I have the following configuration:

dyn_o_mite:
  listen: 0.0.0.0:8102
  timeout: 150000
  servers:
    - 127.0.0.1:22122:1
    - 127.0.0.1:22123:1
    - 127.0.0.1:22124:1
    - 127.0.0.1:22125:1
  dyn_seed_provider: simple_provider
  dyn_port: 8101
  dyn_listen: 0.0.0.0:8101
  datacenter: default_dc
  rack: rack1
  tokens: 1073741823
  dyn_seeds:
    - 172.19.0.120:8101:rack1:default_dc:2147483646
    - 172.19.0.130:8101:rack1:default_dc:3221225469
    - 172.19.0.140:8101:rack1:default_dc:4294967292
    - 172.19.0.10:8101:rack2:default_dc:1073741823
    - 172.19.0.20:8101:rack2:default_dc:2147483646
    - 172.19.0.30:8101:rack2:default_dc:3221225469
    - 172.19.0.40:8101:rack2:default_dc:4294967292
  hash_tag: "{}"
  env: network

but, the dynomite only seems to be connected to one redis server running at 22125, and setting all values to that node.

**Comment by smukil** [comment]
@ankur-aggarwal: You need to create one YAML file per server. Try running "./test/start_cluster.py" from the top level dynomite directory. It will create a folder called "test_run.<some_string>". Under that, have a look at the "conf/" directory to see how to setup a cluster.

Closing this. Please reopen if you still have issues.
