### ISSUE TITLE
Logging and heath check ?

### ISSUE THREAD

**Issue by tannh** [Netflix/dynomite#642]
With run on production. How to can u view logging and healcheck metrics dynomitedb?

**Comment by mcouillard** [comment]
Metrics are exposed over an HTTP endpoint:
https://github.com/Netflix/dynomite/wiki/FAQ#how-can-we-monitor-a-dynomite-process

Logs can be written to a file:
https://github.com/Netflix/dynomite#help

**Comment by smukil** [comment]
@mcouillard Thanks for helping with this issue!

@tannh In addition to what @mcouillard mentioned above, you may also want to have a look at the Dynomite-manager:
https://github.com/Netflix/dynomite-manager
