### ISSUE TITLE
Dyno client requests are not getting load balanced to all available racks in dc

### ISSUE THREAD

**Issue by kmurthy7** [Netflix/dynomite#646]
We have a dynomite cluster with 2 racks ( 5 nodes in each rack ) in one datacenter. I am using dyno client with token aware strategy. When i try to connect to the dyno client always requests are forwarded to rack2 , rack1 is idle. Am i missing any configuration why dyno is not using rack1 at all.

Below is the code we are using.

DynoJedisClient dynoClusterClient	= new DynoJedisClient.Builder()
					.withApplicationName(clientMetrics)
					.withDynomiteClusterName(clusterMetrics)
					.withCPConfig(new ConnectionPoolConfiguration(clientMetrics)
							.withTokenSupplier(TokenMapSupplierHelper.toTokenMapSupplier(nodes))
							.setMaxConnsPerHost(maxConnectionsMetrics)
							.setConnectTimeout(maxTimeOutMetrics)
							.setRetryPolicyFactory(new RetryNTimes.RetryFactory(retryCountMetrics,true))
							.setMaxTimeoutWhenExhausted(maxTimeOutExhaustedMetrics)
							)
					.withHostSupplier(TokenMapSupplierHelper.toHostSupplier(nodes))
					.build();

**Comment by smukil** [comment]
@kmurthy7 Each rack is an entire token ring, i.e. a full replica. The client always forwards requests to its local rack, which in your case is rack 2. We load balance across racks when there are multiple client instances, by having each client instance talk to servers in its local rack.

A client will talk to a different rack as a fallback mechanism when there is a connection error while talking to a server in its local rack.

**Comment by smukil** [comment]
Closing, please reopen if you have further requests.
