### ISSUE TITLE
not able to build dynomite

### ISSUE THREAD

**Issue by shivambansal2222** [Netflix/dynomite#657]
HI , 
      I am getting following error while running autoreconf -fvi to build dynomite as mentioned :
autoreconf  -fvi:
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: adding subdirectory contrib/yaml-0.1.4 to autoreconf
autoreconf: Entering directory `contrib/yaml-0.1.4'
autoreconf: configure.ac: not using Autoconf
autoreconf: Leaving directory `contrib/yaml-0.1.4'
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
configure.ac:32: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1

**Comment by smukil** [comment]
@shivambansal2222 You're missing dependencies. Such errors can usually be googled easily. Installing these deps should unblock you:

sudo apt-gen install autogen autoconf libtool
