### ISSUE TITLE
Encryption between client and Dynomite

### ISSUE THREAD

**Issue by rajangamsj** [Netflix/dynomite#662]
How to encrypt communication between the client and Dynomite. I see that dynomite supports encryption between nodes in a rack using secure_server_option. But not sure how to secure the initial communication from the client  and Dynomite.

**Comment by smukil** [comment]
@rajangamsj The dyno client has support for SSL. The server does not understand encrypted client connections at the moment however. We get around this by using ghost-tunnel on the server-side to do TLS termination:
https://github.com/square/ghostunnel


We will work on adding it natively as part of Dynomite in the future. You may also feel free to submit a patch if you want it sooner.
