### ISSUE TITLE
Unexpected behavior with "noreply"

### ISSUE THREAD

**Issue by mckelvin** [Netflix/dynomite#67]
The issue can be reproduced as follows:

```
$ cat ~/reproduce.py
import socket
import time


def main():
    val = str(int(time.time()))
    sock = socket.socket()
    sock.connect(('localhost', 8102))
    sock.send('delete foo noreply\r\n')
    sock.send('set foo 0 0 %d noreply\r\n%s\r\n' % (len(val), val))
    sock.send('get foo\r\n')
    resp = sock.recv(1024)
    try:
        assert 'foo' in resp
    except:
        print 'unexpected response: %s' % resp.replace('\r', r'\r').replace('\n', r'\n')
        raise
    finally:
        sock.close()


if __name__ == '__main__':
    main()
$ python ~/reproduce.py
unexpected response: END\r\n
Traceback (most recent call last):
  File "/home/mckelvin/reproduce.py", line 23, in <module>
    main()
  File "/home/mckelvin/reproduce.py", line 14, in main
    assert 'foo' in resp
AssertionError
$ python ~/reproduce.py
$ python ~/reproduce.py
unexpected response: END\r\n
Traceback (most recent call last):
  File "/home/mckelvin/reproduce.py", line 23, in <module>
    main()
  File "/home/mckelvin/reproduce.py", line 14, in main
    assert 'foo' in resp
AssertionError
```

I also did the same test on `facebook/mcrouter` and `twitter/twemproxy`. This will only happen on `Netflix/dynomite`. So I guess that's a bug.

**Comment by timiblossom** [comment]
@mckelvin I ran our python code against Redis itself and get a similar error:

mdo@ubuntu:~/workspace/dynomite/scripts$ python test.py 
unexpected response: -ERR unknown command 'delete'\r\n-ERR syntax error\r\n-ERR unknown command '1420276404'\r\n$-1\r\n
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    main()
  File "test.py", line 14, in main
    assert 'foo' in resp
AssertionError
mdo@ubuntu:~/workspace/dynomite/scripts$ 



Also, I can't find on Redis' set with noreply.  Can you point it out to me so I can explore it a bit?

**Comment by mckelvin** [comment]
@timiblossom Oh, I forget to mention this:the issue can only be reproduced with memcached(instead of Redis). Redis doesn't even support `norely`.

**Comment by timiblossom** [comment]
@mckelvin  I confirm that this is a bug on our side and we are working to address it.  Thanks

**Comment by timiblossom** [comment]
Fixed in master branch.

**Comment by mckelvin** [comment]
:beers:
