### ISSUE TITLE
Request a RPM dynomite file for installation

### ISSUE THREAD

**Issue by alochym01** [Netflix/dynomite#671]

**Comment by ipapapa** [comment]
We do not have an RPM produced because we use Ubuntu for our deployments. However, there are many folks that have successes producing RPMs. See https://github.com/Netflix/dynomite/issues/352. If you are interested in publishing an RPM for other folks to use that would be awesome.

**Comment by jkimalane** [comment]
Few weeks ago I created a rpm SPEC file for more convenient installation of dynomite daemon. I can share if you are still interested.

**Comment by ipapapa** [comment]
Absolutely!

**Comment by jkimalane** [comment]
No problem, here it is. Rather hackish implementation but it does its job and fits my needs. 
[https://github.com/jkimalane/dynomite-rpm](url)

**Comment by thias** [comment]
I'm also testing dynomite at the moment, and since it's on RHEL, I created my own rpm package:
https://github.com/thias/rpm-dynomite

**Comment by ipapapa** [comment]
Would it make sense to do a PR for a folder called `RPM`? Moreover, we might need some way to test it when an RPM is created that it works and the changes do not break the building (maybe by adding some part in the tests?).

**Comment by alochym01** [comment]
+1 to do PR for this issue :)
