### ISSUE TITLE
make command fails from

### ISSUE THREAD

**Issue by rituparnopal** [Netflix/dynomite#682]
Got the issue logged below while running "make" command after running the following steps-
$ git clone git@github.com:Netflix/dynomite.git
$ cd dynomite
$ autoreconf -fvi
$ ./configure --enable-debug=yes
$ make
$ src/dynomite -h

make[3]: Entering directory '/home/user/dynomite/src/hashkit'
gcc -DHAVE_CONFIG_H -I. -I../..  -I ../../src -I ../../contrib/murmur3  -Wall -Wshadow -Wpointer-arith -Winline -Wunused-function -Wunused-variable -Wunused-value -Wno-unused-parameter -Wno-unused-value -Wno-missing-prototypes -Wno-missing-declarations -Wconversion -Wsign-compare -Wstrict-prototypes -Wredundant-decls -Werror=implicit-function-declaration -g -O2 -MT dyn_crc16.o -MD -MP -MF .deps/dyn_crc16.Tpo -c -o dyn_crc16.o dyn_crc16.c
In file included from ../../src/dyn_core.h:30:0,
                 from dyn_crc16.c:23:
../../src/dyn_crypto.h:13:10: fatal error: openssl/bio.h: No such file or directory
 #include <openssl/bio.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:393: recipe for target 'dyn_crc16.o' failed
make[3]: *** [dyn_crc16.o] Error 1
make[3]: Leaving directory '/home/ritpal/dynomite/src/hashkit'
Makefile:689: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/ritpal/dynomite/src'
Makefile:483: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ritpal/dynomite'
Makefile:372: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by smukil** [comment]
You need the OpenSSL dev dependency in your system.

`sudo apt install libssl-dev` (on Ubuntu)
