### ISSUE TITLE
Dynomite SIGSEGV signal 11

### ISSUE THREAD

**Issue by effnnn** [Netflix/dynomite#687]
We are getting the following error running dynomite-v0.6.14 and redis. The redis logs show no indication that it went down.

Can anyone give us any input as to what can be done to avoid these errors?

> [2019-07-18 02:47:52.398] client_handle_response:240 looks like we already cleanedup the request for 55
> [2019-07-18 02:47:52.398] client_handle_response:240 looks like we already cleanedup the request for 56
> [2019-07-18 02:47:52.398] client_handle_response:240 looks like we already cleanedup the request for 59
> [2019-07-18 02:47:52.398] client_handle_response:240 looks like we already cleanedup the request for 62
> [2019-07-18 02:47:52.398] client_handle_response:240 looks like we already cleanedup the request for 65
> [2019-07-18 02:47:52.398] client_handle_response:240 looks like we already cleanedup the request for 68
> [2019-07-18 02:47:52.398] dn_assert:301 assert 'req->is_request' failed @ (dyn_server.c, 727)
> [2019-07-18 02:47:52.398] dn_assert:301 assert 'req->is_request' failed @ (dyn_server.c, 771)
> [2019-07-18 02:47:52.398] dn_assert:301 assert 'req->is_request' failed @ (dyn_server.c, 948)
> [2019-07-18 02:47:52.398] dn_assert:301 assert '(c_conn->type == CONN_CLIENT) || (c_conn->type == CONN_DNODE_PEER_CLIENT)' failed @ (dyn_server.c, 784)
> [2019-07-18 02:47:52.398] msg_local_one_rsp_handler:1052 ASSERTION FAILED: Received more than one response for dc_one.               <REQ 0x1a012d0 78:0::0 REQ_REDIS_HMSET, len:194> prev <RSP 0x1a5e4e0 81:0 RSP_REDIS_ERROR len:39> new rsp <RSP 0x1a6aff0 109:0 RSP_REDIS_STATUS len:5>
> [2019-07-18 02:47:52.398] dn_assert:301 assert '!req->selected_rsp' failed @ (dyn_client.c, 105
> 2)
> [2019-07-18 02:47:52.398] msg_local_one_rsp_handler:1052 ASSERTION FAILED: Received more than one response for dc_one. <REQ 0x1a62890 79:0::0 REQ_REDIS_HMSET, len:194> prev <RSP 0x1a5a130 84:0 RSP_REDIS_ERROR len:39> new rsp <RSP 0x1a16590 110:0 RSP_REDIS_STATUS len:5>
> [2019-07-18 02:47:52.398] dn_assert:301 assert '!req->selected_rsp' failed @ (dyn_client.c, 1052)
> [2019-07-18 02:47:52.398] msg_local_one_rsp_handler:1052 ASSERTION FAILED: Received more than one response for dc_one.               <REQ 0x19fcf00 82:0::0 REQ_REDIS_HMSET, len:194> prev <RSP 0x1a55d80 87:0 RSP_REDIS_ERROR len:39> new rsp <RSP 0x1a6f3a0 111:0 RSP_REDIS_STATUS len:5>
> [2019-07-18 02:47:52.398] dn_assert:301 assert '!req->selected_rsp' failed @ (dyn_client.c, 1052)
> [2019-07-18 02:47:52.398] msg_local_one_rsp_handler:1052 ASSERTION FAILED: Received more than one response for dc_one.               <REQ 0x19f8b30 85:0::0 REQ_REDIS_HMSET, len:194> prev <RSP 0x1a519d0 90:0 RSP_REDIS_ERROR len:39> new rsp <RSP 0x1a1a960 112:0 RSP_REDIS_STATUS len:5>
> [2019-07-18 02:47:52.398] dn_assert:301 assert '!req->selected_rsp' failed @ (dyn_client.c, 1052)
> [2019-07-18 02:47:52.398] msg_local_one_rsp_handler:1052 ASSERTION FAILED: Received more than one response for dc_one.               <REQ 0x19f4790 88:0::0 REQ_REDIS_HMSET, len:194> prev <RSP 0x1a4d620 93:0 RSP_REDIS_ERROR len:39> new rsp <RSP 0x1a73750 113:0 RSP_REDIS_STATUS len:5>
> [2019-07-18 02:47:52.398] dn_assert:301 assert '!req->selected_rsp' failed @ (dyn_client.c, 1052)
> [2019-07-18 02:47:52.398] msg_local_one_rsp_handler:1052 ASSERTION FAILED: Received more than one response for dc_one.               <REQ 0x1a49270 96:0::0 REQ_REDIS_HMSET, len:194> prev <RSP 0x19b7820 99:0 RSP_REDIS_ERROR len:39> new rsp <RSP 0x1a7beb0 117:0 RSP_REDIS_STATUS len:5>
> [2019-07-18 02:47:52.398] dn_assert:301 assert '!req->selected_rsp' failed @ (dyn_client.c, 1052)
> [2019-07-18 02:47:52.402] dn_assert:301 assert 'req->is_request' failed @ (dyn_server.c, 727)
> [2019-07-18 02:47:52.402] dn_assert:301 assert 'req->is_request' failed @ (dyn_server.c, 771)
> [2019-07-18 02:47:52.402] dn_assert:301 assert 'req->is_request' failed @ (dyn_server.c, 948)
> [2019-07-18 02:47:52.402] dn_assert:301 assert '(c_conn->type == CONN_CLIENT) || (c_conn->type == CONN_DNODE_PEER_CLIENT)' failed @ (dyn_server.c, 784)
> [2019-07-18 02:47:52.402] dn_assert:301 assert 'req->is_request' failed @ (dyn_server.c, 727)
> [2019-07-18 02:47:52.402] dn_assert:301 assert 'req->is_request' failed @ (dyn_server.c, 771)
> [2019-07-18 02:47:52.402] dn_assert:301 assert 'req->is_request' failed @ (dyn_server.c, 948)
> [2019-07-18 02:47:52.402] dn_stacktrace:286 [0] /lib64/libpthread.so.0(+0xf5d0) [0x7f09ee6b65d0]
> [2019-07-18 02:47:52.452] dn_stacktrace:286 [1] /usr/local/sbin/dynomite() [0x42632a]
> [2019-07-18 02:47:52.456] dn_stacktrace:286 [2] /usr/local/sbin/dynomite() [0x426be9]
> [2019-07-18 02:47:52.465] dn_stacktrace:286 [3] /usr/local/sbin/dynomite(msg_recv+0x456) [0x422cc6]
> [2019-07-18 02:47:52.474] dn_stacktrace:286 [4] /usr/local/sbin/dynomite(core_core+0xcf) [0x41641f]
> [2019-07-18 02:47:52.480] dn_stacktrace:286 [5] /usr/local/sbin/dynomite(event_wait+0x164) [0x43fdf4]
> [2019-07-18 02:47:52.488] dn_stacktrace:286 [6] /usr/local/sbin/dynomite(core_loop+0x16a) [0x41739a]
> [2019-07-18 02:47:52.495] dn_stacktrace:286 [7] /usr/local/sbin/dynomite(main+0x6a0) [0x40cdf0]
> [2019-07-18 02:47:52.508] dn_stacktrace:286 [8] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7f09edffa3d5]
> [2019-07-18 02:47:52.511] dn_stacktrace:286 [9] /usr/local/sbin/dynomite() [0x40d218]
> [2019-07-18 02:47:52.520] signal_handler:123 signal 11 (SIGSEGV) received, core dumping

**Comment by smukil** [comment]
Hi @effnnn ,

These errors are very likely fixed by the following commit:
https://github.com/Netflix/dynomite/commit/813c289787b367053d876bf6f20e35174ad71415

I will make a release shortly so that you can move to that.

**Comment by smukil** [comment]
@effnnn v0.6.15 has the fix. Please reopen if you continue to see issues.

https://github.com/Netflix/dynomite/tree/v0.6.15
