### ISSUE TITLE
Does dynomite support redis-cli --pipe option?

### ISSUE THREAD

**Issue by rajanarayan92** [Netflix/dynomite#690]
Assume there are 2 dynomite nodes, one in each datacenter with token "0".

I'm trying to load the redis AOF file in node-1 using below command. But the data is not written into redis, hence no replication as well.

> [root@datacenterone /]# cat appendonlyOrig.aof | redis-cli -h 10.54.79.66 -p 8102 --pipe
> All data transferred. Waiting for the last reply...
> Error reading from the server: Connection reset by peer
> 

Whereas I can execute this directly on redis server.

> [root@datacenterone /]# cat appendonlyOrig.aof | redis-cli -h 10.54.79.66 -p 6379 --pipe
> All data transferred. Waiting for the last reply...
> Last reply received from server.
> errors: 0, replies: 6

My question here is whether dynomite currently support such use cases?

**Comment by smukil** [comment]
@rajanarayan92 We don't support the --pipe mode at the moment. You're welcome to submit a patch to support it if you like.

On another note, to load from an AOF file, you can make the node load from the file on redis-server startup by putting the file in a pre-determined path:

http://download.redis.io/redis-stable/redis.conf
_AOF and RDB persistence can be enabled at the same time without problems.
If the AOF is enabled on startup Redis will load the AOF, that is the file
with the better durability guarantees._

**Comment by smukil** [comment]
Closing this. Please reopen if you have more questions.
