### ISSUE TITLE
How to resolve the conflict in Dynomite when clients write in 2 Data Centers?

### ISSUE THREAD

**Issue by zhaidongbo** [Netflix/dynomite#773]
Hi,
How to resolve the conflict in Dynomite when clients write in 2 Data Centers simultaneously?
I can't find any information, Could you help me? 
Thank you

**Comment by smukil** [comment]
Hi @zhaidongbo As per the wiki, last writer wins in this case, i.e. which ever client's write was last written in a quorum number of replicas.
