### ISSUE TITLE
Non-java clients

### ISSUE THREAD

**Issue by TwoUnderscorez** [Netflix/dynomite#779]
Am I missing something or is the only available client is for java?
I couldn't even find a python client on PyPI.
Is there maybe a way to use an existing client for Redis for C# or Python to interface with Dynomite (with a Redis backend)?

Thanks in advance!

**Comment by ipapapa** [comment]
Yes, you can use an existing Redis client with Dynomite. There is more information in the [Polyglot section](https://github.com/Netflix/dynomite/projects).

**Comment by TwoUnderscorez** [comment]
I see, thanks!
But I couldn't find any documentation on how I should connect to Dynomite with the Redis (or Memcached) client.
I tried to connect to 8102 but that didn't work. Is connecting to 22122 the way to do it?

**Comment by ipapapa** [comment]
Depends on the configuration on the YAML but if you use the default one you should be connecting to 8102 go through Dynomite. 22122 is directly Redis which the clients should not be using.

**Comment by TwoUnderscorez** [comment]
Finally got it to work. Thanks for your help!
My problem was the client. I was trying to connect to DB 1 (for whatever reason) with all kinds of configurations and with all kinds of clients for C# and Python when it hit me that I should try to connect to DB 0.Then it finally worked.
The problem is in `StackExchange.Redis` which basically did not work for me with Dynomite. The only library that I got to work that is async and supports .net core is `Rediska`.
