### ISSUE TITLE
This vs ElastiCache?

### ISSUE THREAD

**Issue by gitcatrat** [Netflix/dynomite#780]
Sorry about the question but what's the difference with AWS ElastiCache? When should I use this instead of ElastiCache?

**Comment by gitcatrat** [comment]
I looks like this project was created before some of the ElastiCache features and slowly becomes less useful in AWS?

I guess it could still be used in client datacenter or across AWS and datacenter.

**Comment by ipapapa** [comment]
My understanding of AWS ElastiCache is that it is a Redis deployment (probably with Redis Cluster). High availability by Redis Cluster is achieved by a primary/secondary deployment. Once your primary has an issue the secondary is elected to serve the traffic. In other words, per the CAP theorem the system is CP. Dynomite provides active-active and focuses on the AP. If a node goes nodes, there is no election but rather the client is automatically rerouted to the rest of the active nodes.

**Comment by gitcatrat** [comment]
@ipapapa Thanks for insights!
