### ISSUE TITLE
data sync

### ISSUE THREAD

**Issue by RainningCode** [Netflix/dynomite#79]
If I hope to the data sync between data center A and data center B in real time, what can I do?

**Comment by rbastic** [comment]
Can you clarify your question?

Because you cannot synchronize data in "real-time". No matter what system
you use

The network is neither reliable nor infinite. Latency is not zero.

http://en.wikipedia.org/wiki/Fallacies_of_distributed_computing

**Comment by timiblossom** [comment]
Do you mean data replication for write requests or data warm-up?
It is real time in the former case.
