### ISSUE TITLE
Dynomite Node Architecture

### ISSUE THREAD

**Issue by mfouilleul** [Netflix/dynomite#93]
![dynomite node](https://cloud.githubusercontent.com/assets/4102322/6461488/b16d3496-c1a0-11e4-808d-eea13164a006.png)

**Comment by timiblossom** [comment]
@mfouilleul  looks good :).  Do you mind to add this diagram somewhere here for Redis' installation/setup:  https://github.com/Netflix/dynomite/wiki/Getting+Started#setup-and-installation ?
Thanks.

**Comment by mfouilleul** [comment]
This page could be improve yes. There are some 404 on configuration file examples. Do you think can I add my scripts to? 

Florida - Get Seeds, HTTP service (Node.js):
```
var http = require('http');
var url = require('url');

var seeds_file_path_arg = process.argv.slice(2);

var seeds_file = require('fs');
var seeds_file_path = '/etc/dynomite/seeds.list';

if(typeof seeds_file_path_arg == 'undefined' || seeds_file_path_arg == null || seeds_file_path_arg  == ''){
  seeds_file_path = '/etc/dynomite/seeds.list';
} else{
  seeds_file_path = seeds_file_path_arg;
}

var server = http.createServer(function(req, res) {
  var path = url.parse(req.url).pathname;
  res.writeHead(200, {"Content-Type": "application/json"});
  if (path == '/REST/v1/admin/get_seeds') {
    data = seeds_file.readFileSync(seeds_file_path).toString();
    data_oneline = data.trim().replace(/\n/g, '|');
    var now = new Date();
    var jsonDate = now.toJSON();
    console.log(jsonDate + " - get_seeds [" + data_oneline + "]");
    res.write(data_oneline);
  }
  res.end();
});
server.listen(8080);
```

Choose tokens (Python):
```
#!/usr/bin/python
import os, sys

def usage():
  print "usage: python token.py <number of nodes>"
  sys.exit(1)

if len(sys.argv) != 2:
  print "error: Bad number of argument"
  usage()

try:
  nodes = int(sys.argv[1]);
except Exception:
  print "error: Bad type of argument"
  usage()

for i in range(0, nodes):
  t = i*(4294967295)/nodes
  print "Node " + str(i + 1) + ": " + str(t)
```

**Comment by timiblossom** [comment]
yes, you can add these 2 scripts in the scripts directory and send us a pull request. Thanks

**Comment by redboy1972** [comment]
This is a wonderful image.  It helped me understand a lot.  It clarified what the difference between which port was gossip and redis client.  It should be added as this is useful.

**Comment by mfouilleul** [comment]
Thanks @redboy1972

**Comment by ipapapa** [comment]
@mfouilleul any plan to work on this, or our recent presentations and related images cover it. Shall we close this issue?

**Comment by ipapapa** [comment]
@mfouilleul we have done some effort to create this diagram in some of our recent presentations (I have added the Youtube links on the Wiki). Hence, we're marking this question as Resolved. If you want to follow up with further questions let us know and we can either reopen the issue, or please create a new issue.
