### ISSUE TITLE
Version (in)sanity?

### ISSUE THREAD

**Issue by miketheman** [Netflix/dynomite#97]
There seems to be a mismatch between the versions as tagged here in git and the version string as reported by dynomite ltself.

```shellsession
# dynomite --version
This is dynomite-0.1.19
```

https://github.com/Netflix/dynomite/releases contains 0.3.0, 0.4.0

This is likely drive from the section here: https://github.com/Netflix/dynomite/blob/438b6dbbb49fbca64897d46badcc7dc1562da7b7/configure.ac#L1-L5 not being updated.

I don't know how the project wants to version itself, but it appears that there's some attempt at using git tags - so I'd propose that one be set and trump the other.
Also, if there's any way to get the build git hash in the version string for prerelase versions or such, that would be awesome.

Here's a method I read about, could likely be adapted: http://stackoverflow.com/a/1705263

**Comment by timiblossom** [comment]
@miketheman this seems like a cool way to maintain the version based on git hash.  We will explore this very soon.  Thanks for the suggestion.

**Comment by ipapapa** [comment]
@miketheman We have tried to be consistent in regards to version numbers. We have added tags in all new versions: https://github.com/Netflix/dynomite/tags If you have any recommendation please let me know.
